#include "json.hpp"
#include <fstream>
#include <iostream>
#include <vector>
#include <array>
#include <map>
#include <set>
#include <algorithm>
#include <cmath>
#include <chrono>
#include <stdexcept>
using nlohmann::json;using I=__int128_t;using Row=std::array<I,24>;using Mat=std::vector<Row>;
I absI(I x){return x<0?-x:x;} I gcdI(I a,I b){a=absI(a);b=absI(b);while(b){I t=a%b;a=b;b=t;}return a;}I mul(I a,I b){I x;if(__builtin_mul_overflow(a,b,&x))throw std::runtime_error("int128 checked overflow");return x;}I subI(I a,I b){I x;if(__builtin_sub_overflow(a,b,&x))throw std::runtime_error("int128 checked overflow");return x;}std::string si(I x){if(!x)return"0";bool n=x<0;x=absI(x);std::string s;while(x){s+=char('0'+x%10);x/=10;}if(n)s+='-';std::reverse(s.begin(),s.end());return s;}
void prim(Row&r){I g=0;for(I x:r)g=gcdI(g,x);if(g>1)for(I&x:r)x/=g;for(I x:r)if(x){if(x<0)for(I&y:r)y=-y;break;}}
Mat red(Mat in,int h=24){Mat out;std::vector<int> piv;for(Row r:in){for(int k=0;k<(int)out.size();k++)if(r[piv[k]]){I a=out[k][piv[k]],b=r[piv[k]];for(int c=0;c<h;c++)r[c]=subI(mul(r[c],a),mul(out[k][c],b));prim(r);}int c=0;while(c<h&&!r[c])c++;if(c==h)continue;prim(r);for(Row&q:out)if(q[c]){I a=r[c],b=q[c];for(int j=0;j<h;j++)q[j]=subI(mul(q[j],a),mul(r[j],b));prim(q);}out.push_back(r);piv.push_back(c);}std::sort(out.begin(),out.end(),[](const Row&a,const Row&b){int x=0,y=0;while(x<24&&!a[x])x++;while(y<24&&!b[y])y++;return x<y;});return out;}
Mat ker(Mat A,int h=24){A=red(A,h);std::set<int>p;for(Row&r:A){int c=0;while(c<h&&!r[c])c++;p.insert(c);}Mat B;for(int f=0;f<h;f++)if(!p.count(f)){I d=1;for(Row&r:A){int c=0;while(c<h&&!r[c])c++;if(r[f])d=mul(d/gcdI(d,r[c]),absI(r[c]));}Row v{};v[f]=d;for(Row&r:A){int c=0;while(c<h&&!r[c])c++;if(r[f])v[c]=-mul(r[f],d/r[c]);}prim(v);B.push_back(v);}return red(B,h);}
I dot(const Row&a,const Row&b){I x=0;for(int c=0;c<24;c++){I y=mul(a[c],b[c]);if(__builtin_add_overflow(x,y,&x))throw std::runtime_error("dot overflow");}return x;}
Mat parseMat(const json&j){Mat M;for(auto&r:j){Row a{};for(int c=0;c<24;c++)a[c]=r[c].get<long long>();M.push_back(a);}return M;}
struct Frame{Mat A,B;};std::vector<Frame> fr;std::map<std::string,int>interned;std::map<int,int>orig;std::map<std::pair<int,int>,int>cacheMeet;std::map<std::pair<int,int>,bool>cacheSub;
std::string key(const Mat&M){std::string s;for(const Row&r:M){for(I x:r){s+=si(x);s+=',';}s+=';';}return s;}
int addB(Mat B){B=red(B);std::string k=key(B);auto it=interned.find(k);if(it!=interned.end())return it->second;int id=fr.size();fr.push_back({ker(B),B});interned[k]=id;return id;}
int addA(Mat A){return addB(ker(A));}bool sub(int a,int b){if(a==b)return true;auto k=std::make_pair(a,b);if(cacheSub.count(k))return cacheSub[k];bool ok=fr[a].B.size()<=fr[b].B.size();if(ok)for(auto&u:fr[a].B)for(auto&v:fr[b].A)if(dot(u,v)){ok=false;break;}cacheSub[k]=ok;return ok;}
int meet(int a,int b){if(sub(a,b))return a;if(sub(b,a))return b;auto k=std::minmax(a,b);if(cacheMeet.count(k))return cacheMeet[k];Mat A=fr[a].A;A.insert(A.end(),fr[b].A.begin(),fr[b].A.end());return cacheMeet[k]=addA(A);}
int joinF(int a,int b){if(sub(a,b))return b;if(sub(b,a))return a;Mat B=fr[a].B;B.insert(B.end(),fr[b].B.begin(),fr[b].B.end());return addB(B);}
bool nondeg(int f){Mat B=fr[f].B,A=fr[f].A;int n=B.size();if(!n||n==24)return true;Mat U=n<=12?B:A;int d=U.size();std::vector<I>s(d);for(int i=0;i<d;i++)for(I x:U[i])s[i]+=x;Mat M;for(int i=0;i<d;i++){Row r{};for(int j=0;j<d;j++)r[j]=n<=12?subI(mul(9,dot(U[i],U[j])),mul(s[i],s[j])):mul(-15,dot(U[i],U[j]))+mul(s[i],s[j]);M.push_back(r);}return red(M,d).size()==d;}
json load(std::string p){std::ifstream f(p);json j;f>>j;return j;}
struct End{int i,f;};struct Edge{End a,b;};std::vector<Edge>edges;std::vector<std::vector<End>>outgoing,incoming;
void edge(End a,End b){edges.push_back({a,b});if(a.i>=0)outgoing[a.i].push_back(b);if(b.i>=0)incoming[b.i].push_back(a);if(a.i>=0&&b.i>=0&&a.i>=b.i)throw std::runtime_error("edge order");}
json histogram(const std::vector<int>&X){std::map<int,long long>H;long long mass=0;for(auto&e:edges){int a=e.a.i<0?e.a.f:X[e.a.i],b=e.b.i<0?e.b.f:X[e.b.i];if(!sub(a,b))throw std::runtime_error("nesting failure");int r=fr[b].B.size()-fr[a].B.size();H[r]++;mass+=r;}json z;z["mass"]=mass;for(auto[r,n]:H)z["histogram"][std::to_string(r)]=n;double E=0;for(auto[r,n]:H)if(r)E+=n*r*log(72.0/r);z["entropy"]=E;return z;}
struct Flow{struct Arc{int to,rev;double cap;};int n;std::vector<std::vector<Arc>>g;std::vector<int>lev,ptr;Flow(int n):n(n),g(n),lev(n),ptr(n){}void add(int u,int v,double c){if(c<=1e-12||u==v)return;g[u].push_back({v,(int)g[v].size(),c});g[v].push_back({u,(int)g[u].size()-1,0});}double dfs(int u,int t,double f){if(u==t)return f;for(int&i=ptr[u];i<(int)g[u].size();i++){auto&e=g[u][i];if(e.cap>1e-10&&lev[e.to]==lev[u]+1){double z=dfs(e.to,t,std::min(f,e.cap));if(z>1e-10){e.cap-=z;g[e.to][e.rev].cap+=z;return z;}}}return 0;}void run(int s,int t){while(true){std::fill(lev.begin(),lev.end(),-1);std::vector<int>q{s};lev[s]=0;for(int k=0;k<(int)q.size();k++)for(auto&e:g[q[k]])if(e.cap>1e-10&&lev[e.to]<0){lev[e.to]=lev[q[k]]+1;q.push_back(e.to);}if(lev[t]<0)break;std::fill(ptr.begin(),ptr.end(),0);while(dfs(s,t,1e12)>1e-10){}}}std::vector<bool>source(int s){std::vector<bool>seen(n,false);seen[s]=true;std::vector<int>q{s};for(int k=0;k<(int)q.size();k++)for(auto&e:g[q[k]])if(e.cap>1e-10&&!seen[e.to]){seen[e.to]=true;q.push_back(e.to);}return seen;}};
double ent(int r){return r?r*log(72.0/r):0;}
std::vector<int> majorantCut(const std::vector<int>&F,const std::vector<int>&M,json&receipt){int N=F.size();Flow flow(N+2);std::vector<double>u(N,0);int hard=0,allowed=0;double total=0;std::vector<std::pair<int,int>>arcs;for(auto&e:edges){int i=e.a.i,j=e.b.i;int a=i<0?e.a.f:F[i],b=j<0?e.b.f:F[j];bool ai=i>=0&&F[i]!=M[i],bj=j>=0&&F[j]!=M[j];int da=fr[a].B.size(),db=fr[b].B.size();double E00=ent(db-da);if(!ai&&!bj)continue;if(ai&&!bj){u[i]+=ent(db-fr[M[i]].B.size())-E00;continue;}if(!ai&&bj){u[j]+=ent(fr[M[j]].B.size()-da)-E00;continue;}int DMA=fr[M[i]].B.size(),DMB=fr[M[j]].B.size();double E01=ent(DMB-da),E11=ent(DMB-DMA);u[j]+=E01-E00;u[i]+=E11-E01;if(!sub(M[i],F[j])){arcs.push_back({i,j});hard++;}else{double E10=ent(db-DMA);double defect=E00+E11-E01-E10;if(defect<-1e-8)throw std::runtime_error("concavity defect sign");allowed++;total+=std::max(0.0,defect);}}
double cap=1;for(double z:u)cap+=fabs(z);for(auto[i,j]:arcs)flow.add(i,j,cap);for(int i=0;i<N;i++){if(u[i]>0)flow.add(i,N+1,u[i]);if(u[i]<0)flow.add(N,i,-u[i]);}flow.run(N,N+1);auto selected=flow.source(N);auto X=F;double proxy=0;int n=0;for(int i=0;i<N;i++)if(selected[i]&&F[i]!=M[i]){X[i]=M[i];n++;proxy+=u[i];}receipt={{"selected",n},{"proxy_delta",proxy},{"forbidden10_edges",hard},{"feasible10_edges",allowed},{"total_concavity_majorant",total}};return X;}
int main(int argc,char**argv){try{std::string D=argv[1],O=argv[2];json w=load(D+"/word_p12.json"),g=load(D+"/graph_p12.json"),fj=load(D+"/frames_p12.json"),k=load(D+"/kchron_p12.json"),sn=load(D+"/sinks.json");std::set<int>need;for(auto&[key,z]:fj["frames"].items()){int old=std::stoi(key);int id=z.contains("b")?addB(parseMat(z["b"])):addA(parseMat(z["a"]));if((int)fr[id].B.size()!=z["dim"].get<int>())throw std::runtime_error("rank input");orig[old]=id;}std::cout<<"frames "<<fr.size()<<std::endl;int N=w["ops"].size(),v=g["v"],R=18908,full=orig[w["full_frame"]];int empty=addB({});std::vector<int>F;for(auto z:w["op_frame"])F.push_back(orig[z.get<int>()]);for(auto&z:load(D+"/current-bases.json"))F[z[0].get<int>()]=addB(parseMat(z[1]));outgoing.resize(N);incoming.resize(N);std::vector<std::vector<int>> role(R);std::map<int,int>start,root;std::map<int,json>gauge;std::set<int>phase,deleted,donor;std::map<int,int>recipient,readtime;for(auto&[n,s]:w["sources"].items())start[s.get<int>()]=orig[w["source_frame"][std::stoi(n)].get<int>()];for(auto&z:w["gauges"]){int s=z["role"];gauge[s]=z;start[s]=orig[z["frame"].get<int>()];}for(int j=0;j<(int)w["rootroles"].size();j++)root[w["rootroles"][j].get<int>()]=orig[w["root_frame"][j].get<int>()];for(auto&e:sn)deleted.insert(w["rootroles"][e["root"].get<int>()].get<int>());for(auto&p:w["pairs"]){int d=p[0],b=p[1];donor.insert(b);recipient[d]=b;}for(auto x:w["phase1"])phase.insert(x.get<int>());std::vector<int>rest;for(int i=0;i<N;i++){for(int p=0;p<2;p++)role[w["ops"][i][p].get<int>()].push_back(i);if(!phase.count(i))rest.push_back(i);}for(auto&[s,z]:gauge){std::string q=std::to_string(s);readtime[s]=(w["reads"].contains(q)?w["reads"][q].get<int>():phase.size())-phase.size();}
std::set<int>omitted;std::map<int,json>borrow;std::map<int,json>partnerByPassive;for(auto z:k["entries"])partnerByPassive[z["passive"].get<int>()]=z;if(w.contains("omitted_ops"))for(auto x:w["omitted_ops"])omitted.insert(x.get<int>());if(w.contains("borrowed_sources"))for(auto z:w["borrowed_sources"])borrow[z["role"].get<int>()]=z;
auto path=[&](int s){int initial=start.count(s)?start[s]:empty;bool isBorrow=borrow.count(s),inserted=false;int early=-1,mix=-1;if(isBorrow){auto b=borrow[s];int n=b["source"];initial=orig[w["source_frame"][n].get<int>()];early=b["early"];mix=orig[partnerByPassive[n]["mix_frame"].get<int>()];if(start.count(s))throw std::runtime_error("borrowed gauge/source auxiliary");}std::vector<End>p{{-1,initial}};for(int i:role[s]){if(omitted.count(i))continue;if(isBorrow&&!inserted&&i>=early){p.push_back({-1,mix});inserted=true;}p.push_back({i,F[i]});}if(isBorrow&&!inserted){p.push_back({-1,mix});inserted=true;}if(root.count(s))p.push_back({-1,root[s]});return p;};for(int s=0;s<R;s++){if(donor.count(s)||deleted.count(s))continue;auto p=path(s);if(recipient.count(s)){int b=recipient[s];p.push_back({-1,orig[gauge[b]["frame"].get<int>()]});auto q=path(b);p.insert(p.end(),q.begin()+1,q.end());}p.push_back({-1,full});for(int j=1;j<(int)p.size();j++)edge(p[j-1],p[j]);}
std::map<int,std::vector<int>>at;for(auto it=w["gauges"].rbegin();it!=w["gauges"].rend();++it){int s=(*it)["role"];at[readtime[s]].push_back(s);}std::map<int,json>bywrite,after;for(auto&e:sn){int s=w["rootroles"][e["root"].get<int>()];std::vector<int>writes;for(int i:role[s])if(w["ops"][i][0].get<int>()==s)writes.push_back(i);for(int i:writes)bywrite[i]=e;after[writes.back()]=e;}std::vector<End>cur(v,{-1,empty});auto move=[&](int t,End p){edge(cur[t],p);cur[t]=p;};for(int p=0;p<(int)rest.size();p++){for(int s:at[p])for(auto t:gauge[s]["targets"])move(t.get<int>(),{-1,orig[gauge[s]["frame"].get<int>()]});int i=rest[p];if(bywrite.count(i))move(bywrite[i]["pivot"].get<int>(),{i,F[i]});if(after.count(i)){auto&e=after[i];for(auto t:g["roots"][e["root"].get<int>()]["targets"])move(t.get<int>(),{-1,orig[w["root_frame"][e["root"].get<int>()].get<int>()]});}}
for(int s:at[rest.size()])for(auto t:gauge[s]["targets"])move(t.get<int>(),{-1,orig[gauge[s]["frame"].get<int>()]});std::map<int,std::vector<json>>delivery;for(auto&e:k["entries"])delivery[e["deliver_after_root"].get<int>()].push_back(e);for(int j=0;j<(int)g["roots"].size();j++){auto&r=g["roots"][j];int s=w["rootroles"][j];if(r["kind"]=="side"&&!deleted.count(s))for(auto t:r["targets"])move(t.get<int>(),{-1,orig[w["root_frame"][j].get<int>()]});for(auto&e:delivery[j])for(auto t:e["receivers"])move(t.get<int>(),{-1,orig[e["deliver_frame"].get<int>()]});}for(int t=0;t<v;t++){Row cov{};for(int c=0;c<24;c++)cov[c]=-1;for(auto c:g["labels"][t])cov[c.get<int>()]+=3;move(t,{-1,addA({cov})});}
json ans;ans["current"]=histogram(F);std::cout<<"graph "<<N<<" "<<edges.size()<<" current "<<ans["current"].dump()<<std::endl;std::vector<int>X=F;std::set<int>frozen=omitted;int rounds=0;while(true){X=F;int added=0;for(int i=N-1;i>=0;i--){if(frozen.count(i))continue;int f=full;for(End z:outgoing[i])f=meet(f,z.i<0?z.f:X[z.i]);if(!sub(F[i],f))throw std::runtime_error("greatest below current");if(!nondeg(f)){frozen.insert(i);added++;}else X[i]=f;}rounds++;std::cout<<"round "<<rounds<<" degenerate frozen "<<added<<std::endl;if(!added)break;if(rounds>50)throw std::runtime_error("freeze limit");}ans["greatest"]=histogram(X);std::vector<int>M=X;json cut;X=majorantCut(F,M,cut);ans["majorant_cut"]=cut;ans["selected"]=histogram(X);std::cout<<"CUT "<<cut.dump()<<" actual "<<ans["selected"].dump()<<std::endl;ans["degenerate_frozen"]=frozen.size();auto oldF=F;F=X;std::vector<int>V(g["args"].size());for(int n=0;n<v;n++){Row chi{};for(auto c:g["labels"][n])chi[c.get<int>()]=1;V[n]=addB({chi});}for(int n=v;n<(int)V.size();n++)V[n]=joinF(V[g["args"][n][0].get<int>()],V[g["args"][n][1].get<int>()]);auto least=F;int leastFrozen=0;for(int i=0;i<N;i++){int z=V[w["ops"][i][2].get<int>()];for(auto e:incoming[i])z=joinF(z,e.i<0?e.f:least[e.i]);if(!sub(z,F[i]))throw std::runtime_error("least exceeds current");if(!nondeg(z)){z=F[i];leastFrozen++;}least[i]=z;}ans["least"]=histogram(least);ans["least_frozen"]=leastFrozen;
// Reverse every edge and compare annihilator frames; this converts a contraction
// schedule to an expansion schedule while preserving each literal rank gap.
auto savedEdges=edges;auto dualF=F,dualM=least;for(int i=0;i<N;i++){dualF[i]=addB(fr[F[i]].A);dualM[i]=addB(fr[least[i]].A);}for(auto&e:edges){std::swap(e.a,e.b);if(e.a.i<0)e.a.f=addB(fr[e.a.f].A);if(e.b.i<0)e.b.f=addB(fr[e.b.f].A);}json meetCut;auto dualX=majorantCut(dualF,dualM,meetCut);edges=savedEdges;for(int i=0;i<N;i++)X[i]=dualX[i]==dualM[i]?least[i]:F[i];ans["least_cut"]=meetCut;ans["final"]=histogram(X);F=oldF;std::cout<<"LEAST "<<ans["least"].dump()<<" CUT "<<meetCut.dump()<<" FINAL "<<ans["final"].dump()<<std::endl;int changes=0;json bases=json::array();for(int i=0;i<N;i++)if(!sub(F[i],X[i])||!sub(X[i],F[i])){changes++;json M=json::array();for(auto&r:fr[X[i]].B){json row=json::array();for(I x:r){if(x<LLONG_MIN||x>LLONG_MAX)throw std::runtime_error("witness beyond64");row.push_back((long long)x);}M.push_back(row);}bases.push_back({i,M});}ans["changes"]=changes;std::ofstream(O+"/greatest-summary.json")<<ans.dump(2)<<"\n";std::ofstream(O+"/greatest-bases.json")<<bases.dump()<<"\n";std::cout<<ans.dump(2)<<std::endl;return 0;}catch(std::exception&e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}