#include <bits/stdc++.h>
using namespace std;
const int p=12,h=24;using Mask=uint32_t;
int pc(Mask x){return __builtin_popcount(x);} Mask pairmask(int i){return 3u<<(2*i);} Mask z(int i,int j,int e){return pairmask(i)|(1u<<(2*j+e));}
vector<Mask> good,bad; vector<array<int,3>> indexT;
int rankmod(vector<Mask> rows,int prime=1000003){vector<array<long long,h>> M;for(auto x:rows){array<long long,h>a{};for(int j=0;j<h;j++)a[j]=(x>>j)&1;M.push_back(a);}int r=0;auto power=[&](long long a,int k){long long v=1;while(k){if(k&1)v=v*a%prime;a=a*a%prime;k>>=1;}return v;};for(int j=0;j<h&&r<(int)M.size();j++){int q=r;while(q<(int)M.size()&&!M[q][j])q++;if(q==(int)M.size())continue;swap(M[r],M[q]);long long inv=power(M[r][j],prime-2);for(int k=j;k<h;k++)M[r][k]=M[r][k]*inv%prime;for(int i=r+1;i<(int)M.size();i++){auto f=M[i][j];if(f)for(int k=j;k<h;k++)M[i][k]=(M[i][k]-f*M[r][k]%prime+prime)%prime;}r++;}return r;}
void cap(Mask target,const vector<Mask>&s){for(auto x:s)if(pc(x&target)!=1)throw runtime_error("forbidden cap");}
int main(int argc,char**argv){ofstream out(argc>1?argv[1]:"hybrid-cap-checks.txt");for(int a=0;a<p;a++)for(int b=a+1;b<p;b++)for(int c=b+1;c<p;c++)for(int e=0;e<8;e++){Mask t=(1u<<(2*a+(e&1)))|(1u<<(2*b+((e>>1)&1)))|(1u<<(2*c+((e>>2)&1)));good.push_back(t);indexT.push_back({a,b,c});}for(int i=0;i<p;i++)for(int j=0;j<p;j++)if(i!=j)for(int e=0;e<2;e++)bad.push_back(z(i,j,e));long long checks=0,caps=0;
set<int> ug,vg,ub,vb,wb,gb1,gb2,gb3;
for(int a=0;a<(int)good.size();a++){Mask t=good[a];auto T=indexT[a];vector<vector<Mask>> groups;for(int i:T){vector<Mask>u;for(int j=0;j<p;j++)if(find(T.begin(),T.end(),j)==T.end())for(int e=0;e<2;e++)u.push_back(z(i,j,e));ug.insert(rankmod(u));groups.push_back(u);}for(int j:T){int e=(t>>(2*j+1))&1;vector<Mask>v;for(int i=0;i<p;i++)if(find(T.begin(),T.end(),i)==T.end())v.push_back(z(i,j,e));vg.insert(rankmod(v));groups.push_back(v);}for(int i:T)for(int j:T)if(i!=j){int e=(t>>(2*j+1))&1;groups.push_back({z(i,j,1-e)});}for(auto&s:groups){cap(t,s);caps+=s.size();}for(auto s:bad){int n=0;for(auto&q:groups)n+=count(q.begin(),q.end(),s);if(n!=int(pc(t&s)==1))throw runtime_error("bad to good coefficient");checks++;}}
for(int i=0;i<p;i++)for(int j=0;j<p;j++)if(i!=j)for(int e=0;e<2;e++){Mask t=z(i,j,e);vector<Mask>U,W,V;for(int a=0;a<p;a++)if(a!=i&&a!=j){for(int f=0;f<2;f++){U.push_back(z(j,a,f));W.push_back(z(a,i,f));}V.push_back(z(a,j,e));}ub.insert(rankmod(U));wb.insert(rankmod(W));vb.insert(rankmod(V));vector<vector<Mask>>groups={U,W,V};for(auto&s:groups){cap(t,s);caps+=s.size();}for(auto s:bad){int n=0;for(auto&q:groups)n+=count(q.begin(),q.end(),s);if(n!=int(pc(t&s)==1))throw runtime_error("bad to bad coefficient");checks++;}
vector<Mask>A,B,C;for(auto s:good){bool in_i=pc(s&pairmask(i)),in_j=pc(s&pairmask(j));if(in_i&&!in_j)A.push_back(s);if(!in_i&&(s&(1u<<(2*j+e))))B.push_back(s);if(in_i&&(s&(1u<<(2*j+1-e))))C.push_back(s);}groups={A,B,C};for(auto&s:groups){cap(t,s);caps+=s.size();}gb1.insert(rankmod(A));gb2.insert(rankmod(B));gb3.insert(rankmod(C));for(auto s:good){int n=0;for(auto&q:groups)n+=count(q.begin(),q.end(),s);if(n!=int(pc(t&s)==1))throw runtime_error("good to bad coefficient");checks++;}}
vector<Mask>full=good;full.insert(full.end(),bad.begin(),bad.end());sort(full.begin(),full.end());if(full.size()!=2024||adjacent_find(full.begin(),full.end())!=full.end())throw runtime_error("not full triples");long long universal=0;for(auto t:full)for(auto s:full){int inter=pc(t&s);if(((inter%2)^(inter==1))!=int(t==s))throw runtime_error("full decoder");universal++;}
out<<"PASS exact cap-compatible partitions, full triple mod2 decoder\n";out<<"good="<<good.size()<<" bad="<<bad.size()<<" block_entries="<<checks<<" cap_memberships="<<caps<<" universal_entries="<<universal<<"\n";auto show=[&](string n,set<int>s){out<<n;for(auto x:s)out<<" "<<x;out<<"\n";};show("bad_to_good_U",ug);show("bad_to_good_V",vg);show("bad_to_bad_U",ub);show("bad_to_bad_W",wb);show("bad_to_bad_V",vb);show("good_to_bad_A",gb1);show("good_to_bad_B",gb2);show("good_to_bad_C",gb3);out<<"Ranks computed modulo1000003 are lower bounds overQ; the accompanying explicit span constraints give matching upper bounds. These are decoder/cap checks, NOT paid supplier closure.\n";cout<<"PASS "<<checks+universal<<" decoder entries; "<<caps<<" literal cap memberships\n";}