#!/usr/bin/env python3
"""Find gzip-container hashing in a checkout, and classify it.

The failure this audits: a package writes a gzip container with `gzip.compress(...)`
(or `GzipFile`), hashes the *compressed* bytes, and requires that hash to equal a
value committed or pinned when the container was produced in someone else's
environment.  The deflate stream of a gzip container depends on the writing
interpreter and zlib build, so that check can fail on unchanged inputs.  Observed:
#202's headline verifier stops with `Canonical certificate does not reproduce` on
CPython 3.13.16 with the pinned numpy/scipy (independent replay, PR #214), while
#194 -- #202 one commit earlier with unchanged lift inputs -- passes in the same
environment.  PR #212's pinned `baseline-pr200.tar.gz` shows the same effect in the
other direction: its tar payload reproduces byte for byte from the commit, its
container does not.

Two shapes are fine, and both are already used in this repository:

  * compare the payload: `gzip.decompress` before comparing, as #194's regeneration
    check does --
        if name.endswith('.gz'):  # gzip bytes depend on the zlib build
            old, data = gzip.decompress(old), gzip.decompress(data)
        require(old == data, ...)
    and as #194's `bit/prove.py` does (`assert record == json.loads(gzip.decompress(...))`).
  * pin a payload hash or the semantic fields: #217's `expected-bit.json` pins the
    payload hashes of `graph_p12.json`, `word_p12.json`, `frames_p12.json`; #207's
    `verify_inner.py` compares `exact_scalar_program_sha256` and the complex profile's
    fields instead of the lift container.

A third fine shape is pinning the sha256 of a *committed* `.gz` file: those bytes are
fixed in the repository and are never regenerated by a check.

This scanner is a heuristic reader, not a proof.  It reports three things per file:
whether a container is written, whether a container path is hashed, and whether that
digest is compared in the same file.  Cross-file comparisons (a digest recorded in
one file and required in another) have to be read by hand; the note lists them.

Usage:
    python3 gzip_hash_audit.py ROOT [ROOT ...]
    python3 gzip_hash_audit.py --strict ROOT      # exit 1 if a container digest is hashed
"""
import argparse
import re
import sys
from pathlib import Path

WRITE = re.compile(r'gzip\.compress|GzipFile\(|gzip\.open\([^\n]*[\'"][wax]')
GZ_PATH = re.compile(r'(\w+)\s*=\s*[^\n]*[\'"][^\'"\n]*\.gz|with_suffix\(\s*[\'"][^\'"\n]*\.gz')
HASH_CALL = re.compile(r'\b(digest|sha256|sha1)\s*\(')
COMPARE = re.compile(r'(==|!=)[^\n]*\b\w*(_sha256|_sha1|digest)\b|\b\w*(_sha256|_sha1)\b[^\n]*(==|!=)')
SKIP_DIRS = {'.git', '.work', '__pycache__', '.venv', 'node_modules', 'site-packages'}


def classify(path):
    try:
        text = path.read_text(errors='replace')
    except OSError:
        return None
    if 'gzip' not in text and 'GzipFile' not in text:
        return None
    lines = text.splitlines()
    writes = [n for n, line in enumerate(lines, 1) if WRITE.search(line)]
    gz_vars = set()
    for line in lines:
        for name in re.findall(r'(\w+)\s*=\s*[^\n]*[\'"][^\'"\n]*\.gz', line):
            gz_vars.add(name)
        for name in re.findall(r'(\w+)\s*=\s*[^\n]*with_suffix\(\s*[\'"][^\'"\n]*\.gz', line):
            gz_vars.add(name)
    hashes, evidence = [], []
    for n, line in enumerate(lines, 1):
        if not HASH_CALL.search(line):
            continue
        if '.gz' in line or any(re.search(r'\b%s\b' % re.escape(v), line) for v in gz_vars):
            hashes.append(n)
            evidence.append('%s:%d: %s' % (path.name, n, line.strip()[:160]))
    compares = [n for n, line in enumerate(lines, 1) if COMPARE.search(line)]
    if not writes and not hashes:
        return None
    return dict(path=str(path), writes=writes, hashes=hashes, compares=compares,
                decompress=bool(re.search(r'gzip\.decompress', text)), evidence=evidence[:4])


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('roots', nargs='+', type=Path)
    ap.add_argument('--strict', action='store_true')
    args = ap.parse_args()
    risky = 0
    for root in args.roots:
        root = root.resolve()
        print('=== %s' % root)
        for path in sorted(root.rglob('*.py')):
            if any(part in SKIP_DIRS for part in path.parts):
                continue
            info = classify(path)
            if info is None:
                continue
            if info['hashes'] and not info['decompress']:
                flag, risky = 'RISK', risky + 1
            elif info['hashes']:
                flag = 'MIX '
            else:
                flag = '    '
            print('  %s writes=%d container_digest=%d compared_here=%d decompress=%s  %s'
                  % (flag, len(info['writes']), len(info['hashes']), len(info['compares']),
                     info['decompress'], info['path']))
            for line in info['evidence']:
                print('        %s' % line)
        print('  scanned .py files: %d' % sum(1 for _ in root.rglob('*.py')))
    if args.strict and risky:
        print('FAIL %d file(s) hash a container path with no decompress-compare' % risky)
        return 1
    print('OK scanned; %d risky file(s)' % risky)
    return 0


if __name__ == '__main__':
    sys.exit(main())
