#include <algorithm>
#include <cassert>
#include <boost/multiprecision/cpp_int.hpp>
using Q=boost::multiprecision::cpp_rational;
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <vector>
#include "json.hpp"
using namespace std;using J=nlohmann::json;struct Ev{int k,a,b,c,f,z;};struct Frame{int d;vector<vector<long long>>B,A;};
int main(int argc,char**argv){string dir=argv[1],outdir=argv[3];J st,fj,cc;ifstream(dir+"/249-states.json")>>st;ifstream(dir+"/frames.json")>>fj;ifstream(argv[2])>>cc;map<int,Frame>fs;int nextid=200000;for(auto it=fj["frames"].begin();it!=fj["frames"].end();it++){Frame f;f.d=it.value()["dim"];f.B=it.value()["B"].get<vector<vector<long long>>>();f.A=it.value()["A"].get<vector<vector<long long>>>();fs[stoi(it.key())]=move(f);}fj.clear();map<pair<int,int>,bool>cache;auto sub=[&](int a,int b){auto key=make_pair(a,b);auto it=cache.find(key);if(it!=cache.end())return it->second;bool ok=fs[a].d<=fs[b].d;if(ok)for(auto&x:fs[a].B){for(auto&y:fs[b].A){__int128 t=0;for(int i=0;i<24;i++)t+=(__int128)x[i]*y[i];if(t){ok=false;break;}}if(!ok)break;}return cache[key]=ok;};vector<Ev>ev;Ev x;ifstream in(dir+"/249-records.bin",ios::binary);while(in.read((char*)&x,sizeof x))ev.push_back(x);int n=st["n"],v=st["v"],zero=st["ZERO"],full=st["FULL"],cut=-1;for(int i=0;i<(int)ev.size();i++)if(ev[i].k==1&&ev[i].a==3491&&ev[i].b==3488&&ev[i].c==-1&&ev[i].z==25){if(cut>=0)throw runtime_error("ambiguous cut");cut=i;}if(cut<0)throw runtime_error("cut absent");vector<int>ini(n+1,zero),fin(n+1,full);for(auto it=st["initial"].begin();it!=st["initial"].end();it++)ini[stoi(it.key())]=it.value();for(auto it=st["final"].begin();it!=st["final"].end();it++)fin[stoi(it.key())]=it.value();J chosen=J::array(),newframes=J::object();set<int>used;struct Gauge{vector<int>partners;int F;int cut;};map<int,Gauge>gauges;long long totaldim=0,basisgates=0;
J candidates=cc.is_array()?cc:cc["candidates"];for(auto &z:candidates){if(z.contains("roles")){int p=z["pivot"];z["a"]=p;vector<int>ds;for(int r:z["roles"])if(r!=p)ds.push_back(r);z["partners"]=ds;}}sort(candidates.begin(),candidates.end(),[&](const J&a,const J&b){auto key=[&](const J&z){bool t=z.contains("roles");return make_tuple(z.value("cut",cut),t?z["dim"].get<int>():z["E_dimension"].get<int>(),t?z["pivot"].get<int>():z["a"].get<int>());};return key(a)<key(b);});set<int>baseused;for(auto z:candidates){baseused.insert(z["a"].get<int>());for(int r:z["partners"])baseused.insert(r);}for(int file=4;file<argc;file++){J q;ifstream(argv[file])>>q;for(auto z:q["candidates"]){bool ok=true;for(int r:z["roles"])if(baseused.count(r))ok=false;if(!ok)continue;for(int r:z["roles"])baseused.insert(r);candidates.push_back(z);}}
set<int>pivotset,donorset;for(auto z:candidates){int a=z.contains("roles")?z["pivot"].get<int>():z["a"].get<int>();if(!pivotset.insert(a).second)throw runtime_error("duplicate pivot");vector<int>r=z.contains("roles")?z["roles"].get<vector<int>>():vector<int>{a,z["b"].get<int>()};for(int b:r)if(b!=a)donorset.insert(b);}for(int p:pivotset)if(donorset.count(p))throw runtime_error("non-nilpotent basis support");

for(auto z:candidates){int ci=z.value("cut",cut);bool triple=z.contains("roles");int a=triple?z["pivot"].get<int>():z["a"].get<int>();vector<int>members=triple?z["roles"].get<vector<int>>():vector<int>{a,z["b"].get<int>()};int ed=triple?z["dim"].get<int>():z["E_dimension"].get<int>();bool skip=false;for(int r:members)if(ini[r]!=zero||fin[r]!=full)skip=true;if(skip)throw runtime_error("selected initial or final frame changed");if(!triple&&!z["new_targets"].empty())continue;
Frame f;f.d=ed;auto clearrow=[&](vector<Q> r){using I=boost::multiprecision::cpp_int;I d=1;for(auto x:r){I a=d,b=denominator(x);while(b!=0){I t=a%b;a=b;b=t;}d=d/a*denominator(x);}vector<long long>v;for(auto x:r){Q q=x*d;I n=numerator(q);if(n>LLONG_MAX||n<LLONG_MIN)throw runtime_error("cleared coordinate overflow");v.push_back(n.convert_to<long long>());}return v;};for(auto rr:z["basis"]){vector<Q>r;for(auto vv:rr){string t=vv.is_string()?vv.get<string>():to_string(vv.get<long long>());auto k=t.find('/');using I=boost::multiprecision::cpp_int;r.push_back(k==string::npos?Q(I(t)):Q(I(t.substr(0,k)))/I(t.substr(k+1)));}f.B.push_back(clearrow(r));}
// Exact ordinary annihilator. Frame nondegeneracy is independently audited by the bank checker.
vector<vector<Q>>A;for(auto rr:f.B){vector<Q>r;for(auto x:rr)r.push_back(Q(x));A.push_back(r);}vector<int>piv;int rr=0;for(int c=0;c<24;c++){int k=rr;while(k<(int)A.size()&&A[k][c]==0)k++;if(k==(int)A.size())continue;swap(A[k],A[rr]);Q q=A[rr][c];for(int j=0;j<24;j++)A[rr][j]/=q;for(int i=0;i<(int)A.size();i++)if(i!=rr){q=A[i][c];for(int j=0;j<24;j++)A[i][j]-=q*A[rr][j];}piv.push_back(c);rr++;}if(rr!=ed)throw runtime_error("dependent entrance basis");for(int c=0;c<24;c++)if(find(piv.begin(),piv.end(),c)==piv.end()){vector<Q>r(24);r[c]=1;for(int i=0;i<rr;i++)r[piv[i]]=-A[i][c];f.A.push_back(clearrow(r));}
int F=nextid++;fs[F]=f;vector<int>partners;for(int r:members){int first=-1;for(int i=ci+1;i<(int)ev.size();i++){auto e=ev[i];if(e.k==1&&(e.a==r||e.b==r)){first=e.f;break;}if(e.k==2&&e.a==r){first=e.c;break;}}if(first<0||!sub(F,first))throw runtime_error("false actual first-frame intersection");for(int i=0;i<=ci;i++){auto e=ev[i];if(e.k&&((e.k==1&&e.a==r)||(e.k!=1&&(e.a==r||e.b==r))))throw runtime_error("cohort touched before cut");if(e.k==1&&e.b==r&&!(e.z==4&&e.f==zero&&e.a>=v&&e.a<2*v))throw runtime_error("bad prefix read");}used.insert(r);if(r!=a)partners.push_back(r);}
gauges[a]={partners,F,ci};z["cut"]=ci;totaldim+=ed;basisgates+=2*partners.size();z["a"]=a;z["partners"]=partners;z["E_dimension"]=ed;z["new_frame_id"]=F;z["role_a"]=st["regs"][a-2*v];z["basis"]=J::array();for(auto r:f.B){J row=J::array();for(auto x:r)row.push_back(to_string(x));z["basis"].push_back(row);}chosen.push_back(z);newframes[to_string(F)]={{"B",f.B},{"A",f.A},{"dim",ed}};}
if(chosen.empty())throw runtime_error("no selected pairs");vector<int>gorder;for(auto[a,g]:gauges)gorder.push_back(a);sort(gorder.begin(),gorder.end(),[&](int a,int b){return make_pair(fs[gauges[a].F].d,a)<make_pair(fs[gauges[b].F].d,b);});vector<int>state=ini;for(auto&[a,bf]:gauges)state[a]=bf.F;vector<int>newini=state;vector<Ev>out;long long removed=0,weighted=0;map<int,long long>H,oldH;for(auto e:ev){if(e.k==0&&e.f)oldH[e.f]++;else if(e.k==2)oldH[e.z]++;}auto moveTo=[&](int s,int f){if(state[s]==f)return;if(!sub(state[s],f)){cerr<<"bad move "<<s<<" "<<state[s]<<" "<<f<<"\n";throw runtime_error("non-nesting");}int r=fs[f].d-fs[state[s]].d;out.push_back({0,s,state[s],f,r,0});if(r)H[r]++;state[s]=f;};auto add=[&](int a,int b,int c,int f,int z){moveTo(a,f);moveTo(b,f);out.push_back({1,a,b,c,f,z});weighted+=abs(c);};for(int i=0;i<(int)ev.size();i++){auto e=ev[i];if(e.k==1){if(gauges.count(e.b)&&e.z==4&&e.f==zero&&i<=gauges[e.b].cut){removed++;}else add(e.a,e.b,e.c,e.f,e.z);}else if(e.k==2){moveTo(e.a,e.c);state[e.b]=e.f;out.push_back(e);H[e.z]++;}else if(e.k==3){if(state[e.a]!=e.c||state[e.b]!=e.f)throw runtime_error("copy endpoint");out.push_back(e);}for(int a:gorder)if(i==gauges[a].cut){auto bf=gauges[a];for(int b:bf.partners)add(b,a,1,bf.F,28);}}
for(int s=0;s<n;s++)moveTo(s,fin[s]);for(auto&[a,bf]:gauges)for(int b:bf.partners)add(b,a,-1,full,29);for(int s=0;s<n;s++)if(state[s]!=fin[s])throw runtime_error("final frame mismatch");
// Full arbitrary formal F2 columns. COPY has its actual own temporary row.
auto replay=[&](const vector<Ev>&word,bool reverse,int omitcat){int words=(n+63)/64;vector<uint64_t>M((size_t)(n+1)*words);auto row=[&](int s){return &M[(size_t)s*words];};for(int s=0;s<n;s++)row(s)[s/64]|=1ull<<(s%64);for(int k=0;k<(int)word.size();k++){auto e=word[reverse?word.size()-1-k:k];if(e.z==omitcat&&e.k==1)continue;if(e.k==1&&(e.c&1)){for(int j=0;j<words;j++)row(e.a)[j]^=row(e.b)[j];}else if(e.k==(reverse?3:2)){copy(row(e.a),row(e.a)+words,row(e.b));}else if(e.k==(reverse?2:3)){for(int j=0;j<words;j++)if(row(e.a)[j]!=row(e.b)[j])throw runtime_error("copy erase mismatch");}}long long bad=0;for(int s=0;s<n;s++)for(int j=0;j<words;j++){uint64_t expected=(s/64==j)?1ull<<(s%64):0;if(s>=v&&s<2*v&&(s-v)/64==j)expected^=1ull<<((s-v)%64);bad+=row(s)[j]!=expected;}return bad;};if(replay(out,false,-1)||replay(out,true,-1))throw runtime_error("full columns fail");auto badQ=replay(out,false,28),badQi=replay(out,false,29);if(!badQ||!badQi)throw runtime_error("vacuous control");long long mass=0,oldmass=0;J hist=J::object(),delta=J::object();for(auto[r,c]:H){hist[to_string(r)]=c;mass+=r*c;}for(auto[r,c]:oldH)oldmass+=r*c;set<int>rs;for(auto[r,c]:H)rs.insert(r);for(auto[r,c]:oldH)rs.insert(r);for(int r:rs)if(H[r]!=oldH[r])delta[to_string(r)]=H[r]-oldH[r];if(oldmass-mass!=totaldim)throw runtime_error("rank bill mismatch");ofstream bout(outdir+"/COHORT249-RECORDS.bin",ios::binary);bout.write((char*)out.data(),out.size()*sizeof(Ev));J ii=J::object();for(int s=0;s<n;s++)ii[to_string(s)]=newini[s];ofstream(outdir+"/COHORT249-INITIAL.json")<<ii.dump()<<"\n";ofstream(outdir+"/COHORT249-FRAMES.json")<<newframes.dump()<<"\n";ofstream(outdir+"/COHORT249-SELECTION.json")<<chosen.dump(2)<<"\n";J receipt={{"status","PASS_FULL_CURRENT249_COHORT_REWRITE_F2_COLUMNS_AND_FRAMES"},{"new_gauges",chosen.size()},{"new_entrance_rank",totaldim},{"cut_record",cut},{"old_records",ev.size()},{"new_records",out.size()},{"removed_initial_reads",removed},{"added_Q_Qinverse_passes",basisgates},{"forward_formal_columns",n},{"inverse_formal_columns",n},{"omitted_Q_nonzero_wrong_words",badQ},{"omitted_Qinverse_nonzero_wrong_words",badQi},{"histogram",hist},{"delta",delta},{"old_rank_mass",oldmass},{"new_rank_mass",mass},{"new_gram_audit_external",true},{"bank_completion_not_replayed",true},{"global_kappa_claimed",false}};ofstream(outdir+"/COHORT249-REPLAY.json")<<receipt.dump(2)<<"\n";cerr<<"PASS "<<chosen.size()<<" pairs, mass "<<oldmass<<" -> "<<mass<<" removed reads "<<removed<<"\n";}



