#include <boost/multiprecision/cpp_int.hpp>
#include "json.hpp"
#include <fstream>
#include <iostream>
#include <map>
#include <cmath>
#include <stdexcept>
using namespace std;using namespace boost::multiprecision;using J=nlohmann::json;using Q=cpp_rational;using I=cpp_int;
Q parse(string s){auto p=s.find('/');return p==string::npos?Q(I(s)):Q(I(s.substr(0,p)))/I(s.substr(p+1));}
Q get(J j){return j.is_string()?parse(j.get<string>()):Q(j.get<long long>());}
J load(string p){ifstream f(p);if(!f)throw runtime_error(p);J j;f>>j;return j;}
Q down(Q x){I d=I(1)<<224;return Q(I(numerator(x)*d/denominator(x)))/d;}
Q up(Q x){I d=I(1)<<224;return Q(I((numerator(x)*d+denominator(x)-1)/denominator(x)))/d;}
pair<Q,Q> logbase(Q x){Q z=(x-1)/(x+1),t=z,s=0;for(int i=0;i<48;i++){s+=2*t/(2*i+1);t*=z*z;}return {down(s),up(s+2*t/(97*(1-z*z)))};}
pair<Q,Q> logbound_raw(Q x){int k=0;while(x>=2){x/=2;k++;}auto [l,u]=logbase(x);auto [a,b]=logbase(Q(2));return {down(l+k*a),up(u+k*b)};}
pair<Q,Q> logbound(Q x){static map<Q,pair<Q,Q>> cache;auto it=cache.find(x);if(it!=cache.end())return it->second;return cache[x]=logbound_raw(x);}
pair<Q,Q> expbound(Q l,Q u){if(l<0||u>=Q(1)/10)throw runtime_error("exp domain");Q tl=1,tu=1,sl=1,su=1;for(int i=1;i<=32;i++){tl=down(tl*l/i);tu=up(tu*u/i);sl=down(sl+tl);su=up(su+tu);}return {sl,up(su+tu*u/33/(1-u/34))};}
pair<Q,Q> moment(map<int,long long>H,int m,int W,Q a){Q lo=0,hi=0;for(auto [r,n]:H){auto[l,u]=logbound(Q(m)/r);auto[e,f]=expbound(a*l,a*u);Q w=Q(r*n)/(m*W);lo+=w*e;hi+=w*f;}return {down(lo),up(hi)};}
map<string,Q> assembly(Q a,Q b,Q k,Q guard,Q rowgap){Q eta=Q(1)/parse("1000000000000"),beta=Q(1)/parse("1000000000"),tau=1-a,sigma=1-b,q=a*(1-2*eta),lp=1-q,lam=(tau+lp)/2,c=q+eta/4,eps=(1-eta)/(1+q),mi=eps*q,r=(mi+1-eps)/2,delta=eta/8,internal=tau+(1-beta)*max(Q(sigma-tau),Q(0)),leaf=sigma+beta*(1-sigma);map<string,Q>s={
{"bit_positive",a},{"complex_above_bit",b-a},{"complex_below_1_32",Q(1)/32-b},{"beta_positive",beta},{"beta_below_one",1-beta},{"leaf_above_bit",(1-beta)*b-a},
{"q_positive",q},{"q_below_internal",1-internal-q},{"q_below_leaf",1-leaf-q},{"c_positive",c},{"c_below_one",1-c},{"reservations",c-q},{"lambda_tau",lam-tau},{"lambda_sigma",lam-sigma},{"lambda_internal",lam-internal},{"lp_lambda",lp-lam},{"compact_leaf",lp-leaf},{"compact_reservations",lp-(1-c)},{"lp_below_one",q},
{"eps_positive",eps},{"eps_below_one",1-eps},{"guard_width",1-eps},{"K_geometry",1-eps*(1+c)},{"K_log",eps*c},{"record_suffix",1-eps},{"phase_local",1-eps-delta},{"phase_boundary",r-delta},{"gamma_sublinear",1-eps-r},{"cell_band",eps-(1-r)/2},{"prime_pack",1-eps},{"alpha_positive",r},{"alpha_one",1-r},{"alpha_fourth",Q(1)/4-r},{"delta_positive",delta},{"delta_eighth",Q(1)/8-delta},{"record_fallback",eps-a},{"small_field",1-eps-mi},{"artificial",8-eps+r-delta-mi},{"literal_guard",guard},{"row_gap",rowgap}};
vector<Q> margins={1-eps,a,mi,a,min(Q(1-eps-delta),Q(r-delta)),1-eps-delta,eps};for(int i=0;i<7;i++)s["margin"+to_string(i)]=margins[i]-k;return s;}

pair<Q,Q> momentbad(map<int,long long>H,int m,int W,Q a){auto[l,u]=moment(H,m,W,a);long long N=0;for(auto[r,n]:H)N+=n;auto[fl,fu]=moment({{1,32LL*m*m*N}},m,W,a);return{l+fl/parse("10000000000000000"),u+fu/parse("10000000000000000")};}
J price(map<int,long long>H,int W){long double l=.0007L,u=.000747L;auto app=[&](long double a){long double z=0,N=0;for(auto[r,n]:H){z+=(long double)n/W*pow((long double)r/120,1-a);N+=n;}return z+1e-16L*32*120*120*N/W*pow(1.L/120,1-a);};for(int i=0;i<80;i++){long double a=(l+u)/2;if(app(a)<1)l=a;else u=a;}long long proposal=(long long)(l*1e18L),low=proposal-10000,high=proposal+10000;Q grid=parse("1000000000000000000");if(momentbad(H,120,W,Q(low)/grid).second>=1||momentbad(H,120,W,Q(high)/grid).first<=1)throw runtime_error("proposal bracket");while(high-low>1){long long z=low+(high-low)/2;auto[a,b]=momentbad(H,120,W,Q(z)/grid);if(b<1)low=z;else if(a>1)high=z;else throw runtime_error("insufficient interval precision");}Q c=Q(low)/grid;auto[ml,mu]=momentbad(H,120,W,c);auto[nl,nu]=momentbad(H,120,W,c+1/grid);if(!(mu<1&&nl>1))throw runtime_error("coarse grid");Q bit=parse("384599/10000000000");J chain=J::array({bit.str()});for(int i=0;i<3;i++){bit=(1-c)*c+c*bit;chain.push_back(bit.str());}Q b=parse("747454944651775/1000000000000000000"),eta=parse("1/1000000000000"),q=bit*(1-2*eta),bound=(1-eta)*q/(1+q);I z=(numerator(bound)*I("1000000000000000000")-1)/denominator(bound);Q k=Q(z)/grid;auto constraints=assembly(bit,b,k,1,Q(1000000)-Q(51*20161)/25),adj=assembly(bit,b,k+1/grid,1,Q(1000000)-Q(51*20161)/25);int pass=0,fail=0;for(auto[name,x]:constraints)pass+=x>0;for(auto[name,x]:adj)fail+=x<=0;if(pass!=47||!fail)throw runtime_error("assembly");long long mass=0,count=0;J h=J::object();for(auto[r,n]:H){mass+=r*n;count+=n;h[to_string(r)]=n;}return{{"stock",W},{"histogram",h},{"rank_mass",mass},{"calls",count},{"deficit",120LL*W-mass},{"coarse",c.str()},{"coarse_decimal",c.convert_to<double>()},{"moment_upper",mu.str()},{"next_coarse_moment_lower",nl.str()},{"bootstrap_chain",chain},{"ordinary_bit",bit.str()},{"kappa",k.str()},{"kappa_decimal",k.convert_to<double>()},{"positive_constraints",pass},{"next_kappa_rejected",fail}};}
int main(int argc,char**argv){if(argc!=4)throw runtime_error("args RECORDS_RECEIPT BANK_RECEIPT OUTPUT");auto rec=load(argv[1]),bank=load(argv[2]);map<int,long long>H;for(auto it=rec["histogram"].begin();it!=rec["histogram"].end();it++)H[stoi(it.key())]=120*it.value().get<long long>();for(int r:{4,23,46,50})H[r]+=48*1760;auto old=H;for(auto it=rec["delta"].begin();it!=rec["delta"].end();it++)old[stoi(it.key())]-=120*it.value().get<long long>();int W=bank["normalized_stock"],R=bank["actual_helper_roles"],S=rec["new_entrance_rank"];int endpoint=bank.value("endpoint_rank_deficit",0);if(W!=119374+24*R-endpoint-S)throw runtime_error("stock binding");J baseline=price(old,W+S+endpoint),candidate=price(H,W);if(baseline["deficit"]!=105600||candidate["deficit"]!=105600)throw runtime_error("fixed deficit");J out={{"status","PASS_EXACT_SOURCE_BOUND_CONDITIONAL_PRICING_47_AND_ADJACENT_CONTROLS"},{"baseline",baseline},{"cohort_candidate",candidate},{"bank_completion_required",true},{"finite_bill_and_all_size_interfaces_not_reproved",true}};ofstream(argv[3])<<out.dump(2)<<"\n";cerr<<"BASE "<<baseline["kappa"]<<" NEW "<<candidate["kappa"]<<"\n";}

