#include <bits/stdc++.h>
#include <json.hpp>
#include <boost/multiprecision/cpp_int.hpp>
using namespace std;using J=nlohmann::json;using Z=boost::multiprecision::cpp_int;using Q=boost::multiprecision::cpp_rational;using M=vector<vector<Q>>;
struct E{int k,a,b,c,f,z;};J ld(string p){ifstream f(p);if(!f)throw runtime_error("missing "+p);J j;f>>j;return j;}Q rat(J j){return j.is_string()?Q(j.get<string>()):Q(j.get<long long>());}M mat(J j){M a;for(auto r:j){vector<Q>v;for(auto x:r)v.push_back(rat(x));a.push_back(v);}return a;}
M rref(M a,vector<int>&p){int row=0;for(int c=0;c<24&&row<a.size();c++){int t=row;while(t<a.size()&&a[t][c]==0)t++;if(t==a.size())continue;swap(a[t],a[row]);Q z=a[row][c];for(auto&x:a[row])x/=z;for(int i=0;i<a.size();i++)if(i!=row){Q x=a[i][c];for(int j=0;j<24;j++)a[i][j]-=x*a[row][j];}p.push_back(c);row++;}a.resize(row);return a;}
M nullspace(M b){vector<int>p;auto a=rref(b,p);M out;for(int c=0;c<24;c++)if(find(p.begin(),p.end(),c)==p.end()){vector<Q>v(24);v[c]=1;for(int i=0;i<p.size();i++)v[p[i]]=-a[i][c];out.push_back(v);}return out;}
J integerRows(M a){J out=J::array();for(auto r:a){Z den=1;for(Q q:r){Z d=denominator(q);den=boost::multiprecision::lcm(den,d);}vector<Z>v;Z g=0;for(Q q:r){Z z=numerator(Q(q*den));g=boost::multiprecision::gcd(g,abs(z));v.push_back(z);}J row=J::array();for(Z x:v)row.push_back((x/g).convert_to<long long>());out.push_back(row);}return out;}
Q det(M a){int n=a.size();Q d=1;for(int c=0;c<n;c++){int t=c;while(t<n&&a[t][c]==0)t++;if(t==n)return 0;if(t!=c){swap(a[t],a[c]);d=-d;}Q p=a[c][c];d*=p;for(int i=c+1;i<n;i++){Q z=a[i][c]/p;for(int j=c;j<n;j++)a[i][j]-=z*a[c][j];}}return d;}
int main(int ac,char**av){if(ac!=6)throw runtime_error("args base_export actual_cohort old_to_new witness output");string base=av[1],src=av[2],out=av[5];filesystem::create_directories(out);auto st=ld(base+"/249-states.json"),fs=ld(base+"/frames.json")["frames"],nf=ld(src+"/COHORT249-FRAMES.json"),ini=ld(src+"/COHORT249-INITIAL.json"),fin=st["final"],mp=ld(av[3]),sel=ld(av[4]);for(auto it=nf.begin();it!=nf.end();it++)fs[it.key()]=it.value();if(filesystem::exists(src+"/COHORT249-FINAL.json"))fin=ld(src+"/COHORT249-FINAL.json");int n=st["n"],v=st["v"],zero=st["ZERO"];vector<E>raw;E e;ifstream f(src+"/COHORT249-RECORDS.bin",ios::binary);while(f.read((char*)&e,sizeof e))raw.push_back(e);int cut=-1;map<int,long long>oldH;set<pair<int,int>>oldpairs;for(int j=0;j<raw.size();j++){auto e=raw[j];if(e.k==3||(e.k==1&&e.f==zero&&((e.a>=v&&e.a<2*v)||(e.b>=v&&e.b<2*v))))cut=j;if(e.k==0){if(e.f)oldH[e.f]++;oldpairs.insert({e.b,e.c});}if(e.k==2)oldH[e.z]++;}
map<int,J>chosen;J rejected=J::array();for(auto en:sel["entries"]){int old=en["stream"],h=mp.at(to_string(old));string reason;if(h<0)reason="removed sink";else if(ini.at(to_string(h))!=zero)reason="already gauged kernel";else if(fin.at(to_string(h))!=st["FULL"])reason="nonfull endpoint";else if(st["regs"][h-2*v]!=en["role"])throw runtime_error("virtual binding");vector<int>reads;set<int>targets;for(int j=0;j<=cut&&reason.empty();j++){auto e=raw[j];if(e.k==1){if(e.a==h)reason="helper written before cut";if(e.b==h){if(e.z!=4||e.f!=zero||e.a<v||e.a>=2*v||abs(e.c)!=1)reason="noninitial helper read before cut";reads.push_back(j);targets.insert(e.a);}}if(e.k==2&&e.a==h)reason="helper copied before cut";}
set<int>expected;for(int t:en["targets"])expected.insert(v+t);if(reason.empty()&&(reads.size()!=4||targets!=expected))reason="dirty read set mismatch";
if(reason.empty())for(int j=reads.front();j<=cut&&reason.empty();j++){auto e=raw[j];if(e.k==1&&targets.count(e.b))reason="target source in commutation interval";if(e.k==2&&targets.count(e.a))reason="target copy in commutation interval";}
if(!reason.empty()){rejected.push_back({{"old_stream",old},{"stream",h},{"reason",reason}});continue;}en["stream"]=h;en["old_stream"]=old;en["reads"]=reads;chosen[h]=en;}
J screen={{"status","SCREENED_ACTUAL_WORD"},{"cut",cut},{"chosen",chosen},{"rejected",rejected}};ofstream(out+"/SCREEN.json")<<screen.dump(2);cout<<"SURVIVORS "<<chosen.size()<<" rejected "<<rejected.size()<<endl;if(chosen.empty())return 0;
int next=0;for(auto it=fs.begin();it!=fs.end();it++)next=max(next,stoi(it.key())+1);J extra=J::object(),dets=J::array();int sumrank=0;for(auto&[h,en]:chosen){M B=mat(en["basis"]);vector<int>p;rref(B,p);int rank=en["rank"];if(p.size()!=rank)throw runtime_error("rank");M gram(rank,vector<Q>(rank));for(int i=0;i<rank;i++)for(int j=0;j<rank;j++)for(int k=0;k<24;k++)for(int l=0;l<24;l++)gram[i][j]+=B[i][k]*B[j][l]*(Q(k==l)-Q(1)/9);Q g=det(gram);if(g==0)throw runtime_error("singular gram");auto A=integerRows(nullspace(B));J frame={{"B",en["basis"]},{"A",A},{"dim",rank}};fs[to_string(next)]=frame;nf[to_string(next)]=frame;extra[to_string(next)]=frame;ini[to_string(h)]=next;en["frame"]=next++;sumrank+=rank;dets.push_back({{"role",h},{"gram_determinant",g.str()}});}
map<pair<int,int>,bool>cache;auto sub=[&](int a,int b){auto k=make_pair(a,b);if(cache.count(k))return cache[k];auto&A=fs.at(to_string(a));auto&B=fs.at(to_string(b));bool ok=A["dim"].get<int>()<=B["dim"].get<int>();if(ok)for(auto u:A["B"])for(auto w:B["A"]){Q z=0;for(int i=0;i<24;i++)z+=rat(u[i])*rat(w[i]);if(z!=0)ok=false;}return cache[k]=ok;};auto dim=[&](int f){return fs.at(to_string(f))["dim"].get<int>();};
set<int>skip;vector<E>reads;for(auto[h,en]:chosen)for(int j:en["reads"])skip.insert(j);for(int j:skip)reads.push_back(raw[j]);vector<int>state(n+1);for(int i=0;i<n;i++)state[i]=ini.at(to_string(i));vector<E>word;map<int,long long>H;set<pair<int,int>>changed;auto move=[&](int a,int f){int old=state[a];if(old==f)return;if(!oldpairs.count({old,f})){if(!sub(old,f))throw runtime_error("nonnested role="+to_string(a)+" old="+to_string(old)+" new="+to_string(f));changed.insert({old,f});}int r=dim(f)-dim(old);if(r<0)throw runtime_error("ranknegative");word.push_back({0,a,old,f,r,0});state[a]=f;if(r)H[r]++;};int tmp=-1;
for(int j=0;j<raw.size();j++){auto e=raw[j];if(e.k==0||skip.count(j))continue;if(e.k==1){move(e.a,e.f);move(e.b,e.f);word.push_back(e);}else if(e.k==2){if(tmp!=-1||e.b!=n)throw runtime_error("copy");move(e.a,e.c);state[n]=e.f;tmp=e.a;H[e.z]++;word.push_back(e);}else{if(e.k!=3||tmp!=e.a||state[e.a]!=e.c||state[n]!=e.f)throw runtime_error("discard");tmp=-1;word.push_back(e);}if(j==cut){if(tmp!=-1)throw runtime_error("cutcopy");for(auto r:reads){r.f=chosen.at(r.b)["frame"];if(state[r.b]!=r.f)throw runtime_error("source moved before cut");move(r.a,r.f);word.push_back(r);}}}
for(int a=0;a<n;a++)move(a,fin.at(to_string(a)));if(tmp!=-1)throw runtime_error("unclearedcopy");
// Exact integers for every transported independent dirty input.
auto intcols=[&](vector<E>&ev){int d=chosen.size();vector<Z>M((size_t)(n+1)*d);int k=0;for(auto[h,en]:chosen)M[(size_t)h*d+k++]=1;for(auto e:ev){if(e.k==1)for(int c=0;c<d;c++)M[(size_t)e.a*d+c]+=e.c*M[(size_t)e.b*d+c];if(e.k==2)for(int c=0;c<d;c++)M[(size_t)e.b*d+c]=M[(size_t)e.a*d+c];if(e.k==3)for(int c=0;c<d;c++)if(M[(size_t)e.a*d+c]!=M[(size_t)e.b*d+c])throw runtime_error("integercopy");}M.resize((size_t)n*d);return M;};if(intcols(raw)!=intcols(word))throw runtime_error("integercolumnsequality");
auto f2=[&](bool rev,bool omit=false){int nw=(n+63)/64;vector<uint64_t>M((size_t)(n+1)*nw);auto row=[&](int a){return &M[(size_t)a*nw];};for(int i=0;i<n;i++)row(i)[i/64]=1ull<<(i%64);for(int j=0;j<word.size();j++){auto e=word[rev?word.size()-1-j:j];if(omit&&e.k==1&&e.z==4&&chosen.count(e.b)&&e.f==chosen.at(e.b)["frame"].get<int>())continue;if(e.k==1&&(e.c&1))for(int k=0;k<nw;k++)row(e.a)[k]^=row(e.b)[k];if(e.k==(rev?3:2))copy(row(e.a),row(e.a)+nw,row(e.b));if(e.k==(rev?2:3))for(int k=0;k<nw;k++)if(row(e.a)[k]!=row(e.b)[k])throw runtime_error("f2copy");}long long bad=0;for(int i=0;i<n;i++)for(int k=0;k<nw;k++){uint64_t x=i/64==k?1ull<<(i%64):0;if(i>=v&&i<2*v&&(i-v)/64==k)x^=1ull<<((i-v)%64);if(row(i)[k]!=x)bad++;}return bad;};if(f2(false)||f2(true))throw runtime_error("F2column");long long omitted=f2(false,true);if(!omitted)throw runtime_error("vacuous omission control");
map<int,long long>delta=H;for(auto[r,k]:oldH)delta[r]-=k;long long mass=0,dm=0;J hd=J::object(),dd=J::object();for(auto[r,k]:H){mass+=r*k;hd[to_string(r)]=k;}for(auto[r,k]:delta)if(k){dm+=r*k;dd[to_string(r)]=k;}if(dm!=-sumrank)throw runtime_error("rankmass mismatch");J rec={{"status","PASS_ACTUAL_WORD_DIRTY_TRANSPORT_SIGNED_COMMUTATION_INTEGER_COLUMNS_AND_F2"},{"entries",chosen},{"rejected",rejected},{"new_entrances",chosen.size()},{"new_entrance_rank",sumrank},{"relocated_reads",reads.size()},{"cut",cut},{"rank_mass",mass},{"histogram",hd},{"delta",dd},{"new_frame_determinants",dets},{"changed_pairs",changed},{"all_selected_integer_columns_equal",true},{"forward_inverse_all_F2_columns",n},{"omitted_transport_wrong_words",omitted},{"banked_or_priced",false}};
auto save=[&](string s,J j){ofstream f;f.exceptions(ios::badbit|ios::failbit);f.open(out+"/"+s);f<<j.dump(2)<<"\n";};save("ENTRANCE-TRANSPORT.json",rec);save("COHORT249-INITIAL.json",ini);save("COHORT249-FINAL.json",fin);save("COHORT249-FRAMES.json",nf);save("NEW-ENTRANCE-FRAMES.json",extra);ofstream bo;bo.exceptions(ios::badbit|ios::failbit);bo.open(out+"/COHORT249-RECORDS.bin",ios::binary);bo.write((char*)word.data(),word.size()*sizeof(E));bo.close();if(filesystem::exists(src+"/COHORT249-REPLAY.json")){auto prior=ld(src+"/COHORT249-REPLAY.json");auto total=prior["delta"];for(auto it=dd.begin();it!=dd.end();it++)total[it.key()]=total.value(it.key(),0LL)+it.value().get<long long>();vector<string>erase;for(auto it=total.begin();it!=total.end();it++)if(it.value()==0)erase.push_back(it.key());for(auto k:erase)total.erase(k);prior["delta"]=total;prior["histogram"]=hd;prior["actual_kernel_entrance_rank"]=prior["new_entrance_rank"];prior["new_entrance_rank"]=prior["new_entrance_rank"].get<int>()+sumrank;prior["transported_entrance_rank"]=sumrank;prior["actual_kernel_gauges"]=prior["new_gauges"];prior["new_gauges"]=prior["new_gauges"].get<int>()+chosen.size();prior["transported_gauges"]=chosen.size();prior["new_rank_mass"]=mass;prior["new_records"]=word.size();prior["transport_cut"]=cut;prior["status"]="PASS_KERNEL_AND_RETIMING_AND_TRANSPORT_COMPOSITION";prior["inherited_control_scope"]="Q controls refer to source kernel word; transport columns and omission control supplied separately";prior["transport_receipt"]="ENTRANCE-TRANSPORT.json";save("COHORT249-REPLAY.json",prior);}if(filesystem::exists(src+"/COHORT249-SELECTION.json"))filesystem::copy_file(src+"/COHORT249-SELECTION.json",out+"/COHORT249-SELECTION.json",filesystem::copy_options::overwrite_existing);cout<<"PASS newrank="<<sumrank<<" mass="<<mass<<" delta="<<dd.dump()<<endl;
}
