#include "json.hpp"
#include <fstream>
#include <iostream>
#include <vector>
#include <map>
#include <stdexcept>
using J=nlohmann::json;
struct P{int kind,a,b,c,f,z;};struct E{int kind,dst,src,coefficient;};
void need(bool ok,const char*s){if(!ok)throw std::runtime_error(s);}J load(const std::string&p){std::ifstream f(p);need(bool(f),"JSON missing");J j;f>>j;return j;}
int main(int argc,char**argv){try{need(argc==5,"usage INPUT_RAW_PHYSICAL_RECORDS PHYSICAL_JSON RAW_JSON OUTPUT_PREFIX");J ph=load(argv[2]),raw=load(argv[3]);int n=ph["physical_registers"],R=ph["independent_dirty_registers"];need(n==20107&&R==16587&&ph["source_heads"]==527,"actual527 dimensions");std::ifstream f(argv[1],std::ios::binary|std::ios::ate);need(bool(f),"physical records missing");size_t bytes=f.tellg();need(bytes%sizeof(P)==0,"6-field physical record size");std::vector<P> p(bytes/sizeof(P));f.seekg(0);f.read((char*)p.data(),bytes);std::vector<E> e;std::map<int,long long>hist;long long mass=0,moves=0,adds=0,copies=0;bool open=false;int center=-1;for(auto r:p){if(r.kind==0){need(r.a>=0&&r.a<n&&r.f>=0,"physical MOVE shape");if(r.f){hist[r.f]++;mass+=r.f;}moves++;}
else if(r.kind==1){need(r.a>=0&&r.a<n&&r.b>=0&&r.b<=n&&r.a!=r.b,"physical ADD endpoints");need(r.b!=n||open,"copy work lifetime");need(!open||r.a!=center,"center source immutable");e.push_back({0,r.a,r.b,r.c});adds++;}
else if(r.kind==2){need(!open&&r.a>=0&&r.a<n&&r.b==n&&r.z==22,"fresh COPY shape");open=true;center=r.a;e.push_back({1,n,r.a,0});hist[r.z]++;mass+=r.z;copies++;}
else if(r.kind==3){need(open&&r.a==center&&r.b==n&&r.z==22,"DISCARD source binding");e.push_back({2,n,r.a,0});open=false;center=-1;}
else need(false,"physical opcode");}need(!open&&copies==24,"copy block completion");need(adds==ph["weighted_scalar_events"],"scalar count binding");J hh=J::object();for(auto[k,v]:hist)hh[std::to_string(k)]=v;need(hh==ph["paid_histogram"]&&mass==ph["paid_rank_mass"],"independent complete physical rank ledger");need(hh==raw["one_stage_helper_histogram_including_copies"],"fresh raw complete histogram binding");need(mass==434502,"expected actual527rankmass");std::string out=argv[4];std::ofstream ef(out+".events.bin",std::ios::binary);ef.write((char*)e.data(),e.size()*sizeof(E));ef.close();J result={{"status","PASS_NATIVE527_PHYSICAL_SCALAR_EXTRACTION_AND_FULL_PAID_LEDGER"},{"v",1760},{"independent_dirty_registers",R},{"local_live_registers",n},{"temporary_local_id",n},{"events",e.size()},{"event_record_bytes",sizeof(E)},{"physical_events",p.size()},{"physical_move_events",moves},{"local_scalar_additions",adds},{"copied_centers",copies},{"source_aliases",527},{"paid_histogram",hh},{"paid_rank_mass",mass},{"source527_scalar_digest",ph["scalar_projection_sha256"]},{"source527_tagged_digest",ph["tagged_scalar_sha256"]},{"scope","Independent native conversion of fresh public527 physical records, checking complete paid histogram and all scalar addresses/copy lifetimes; monotone frame and prime admission supplied by fresh physical527/prime replay; all-column global controller checked independently by native C++."}};std::ofstream(out)<<result.dump(2);std::cout<<result.dump(2)<<"\n";}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 2;}}
