// Independent literal audit adapted with OpenAI Codex assistance; Apache-2.0.
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>
#include <json.hpp>
using namespace std;using J=nlohmann::json;using Row=vector<int>;struct F{int d;vector<Row>B,A;};struct E{int op,x,y,c,f,z;};
void ck(bool b,string s){if(!b)throw runtime_error(s);}J rd(string p){ifstream in(p);J j;in>>j;return j;}
int main(int argc,char**argv){ck(argc==5,"arguments");string p=argv[1],out=argv[2],pkg=argv[3];J st=rd(p+"/249-states.json"),frames=rd(p+"/frames.json")["frames"],ini=rd(p+"/COHORT249-INITIAL.json"),fin=rd(p+"/COHORT249-FINAL.json"),tiling=rd(pkg+"/stages/bank-tiling.json");int n=st["n"],v=st["v"],h=rd(p+"/frames.json")["h"];int T=tiling.at("physical_replicas"),m=5*h;map<int,F>fs;for(auto it=frames.begin();it!=frames.end();++it){F f;f.d=it.value()["dim"];f.A=it.value()["A"].get<vector<Row>>();f.B=it.value()["B"].get<vector<Row>>();ck(f.A.size()+f.B.size()==h&&f.B.size()==f.d,"frame dimensions");for(auto rows:{f.A,f.B})for(auto row:rows){ck(row.size()==h,"row width");for(int x:row)ck(abs(x)<=7,"coefficient guard");}fs.emplace(stoi(it.key()),f);}ifstream raw(p+"/COHORT249-RECORDS.bin",ios::binary);raw.seekg(0,ios::end);auto bytes=raw.tellg();raw.seekg(0);ck(bytes%24==0,"record width");vector<E>es(bytes/24);raw.read((char*)es.data(),bytes);ck(raw.good(),"read");
map<int,int>initial,final,state;for(auto it=ini.begin();it!=ini.end();++it)initial[stoi(it.key())]=it.value();for(auto it=fin.begin();it!=fin.end();++it)final[stoi(it.key())]=it.value();ck(initial.size()==n&&final.size()==n,"role census");state=initial;
set<pair<int,int>>pairs;auto subset=[&](int a,int b){if(a==b)return;pair<int,int>pr{a,b};if(!pairs.insert(pr).second)return;F&A=fs.at(a),&B=fs.at(b);ck(A.d<=B.d,"nonnested dimension");for(auto x:A.B)for(auto y:B.A){int dot=0;for(int k=0;k<h;k++)dot+=x[k]*y[k];ck(dot==0,"forward containment / reflected annihilator");}};
map<int,long long>paid,required,reflected;vector<vector<int>>needs(n);map<int,int>coeff;long long adds=0,moves=0,copies=0,erasures=0;int temp=-1;for(auto e:es){if(e.op==0){ck(state.at(e.x)==e.y,"MOVE predecessor");subset(e.y,e.c);ck(fs.at(e.c).d-fs.at(e.y).d==e.f,"MOVE gap");ck(fs.at(e.y).A.size()-fs.at(e.c).A.size()==e.f,"reflected MOVE gap");state[e.x]=e.c;if(e.f)paid[e.f]++;moves++;}else if(e.op==1){ck(e.x!=e.y&&(e.c%2)!=0,"scalar contract");ck(e.x<n,"temporary target prohibited");if(temp>=0)ck(e.x!=temp,"borrowed source mutated");ck(state.at(e.x)==e.f&&state.at(e.y)==e.f,"common frame");needs[e.x].push_back(e.f);if(e.y<n)needs[e.y].push_back(e.f);else ck(e.y==n&&temp>=0&&e.f==int(st["ZERO"]),"temp read");coeff[e.c]++;adds++;}else if(e.op==2){ck(temp==-1&&e.y==n&&state.at(e.x)==e.c&&e.f==int(st["ZERO"])&&e.z==h-2,"COPY contract");state[e.y]=e.f;needs[e.x].push_back(e.c);temp=e.x;copies++;paid[e.z]++;required[e.z]++;reflected[e.z]++;}else if(e.op==3){ck(temp==e.x&&e.y==n&&state.at(e.x)==e.c&&state.at(n)==e.f,"ERASE contract");state.erase(n);temp=-1;erasures++;}else throw runtime_error("opcode");}ck(temp==-1&&state==final,"actual endpoints");
for(int r=0;r<n;r++){vector<int>path{initial.at(r)};path.insert(path.end(),needs[r].begin(),needs[r].end());path.push_back(final.at(r));for(int k=1;k<path.size();k++){int a=path[k-1],b=path[k];subset(a,b);int d=fs.at(b).d-fs.at(a).d;if(d)required[d]++;}for(int k=path.size()-1;k>0;k--){int a=path[k],b=path[k-1];subset(b,a);int d=int(fs.at(b).A.size())-int(fs.at(a).A.size());ck(d>=0,"reflected required gap");if(d)reflected[d]++;}}ck(required==paid&&reflected==paid,"independent required ledger census");
int nw=(n+1+63)/64;auto replay=[&](bool rev,bool omit){vector<vector<uint64_t>>rows(n+1,vector<uint64_t>(nw));for(int r=0;r<=n;r++)rows[r][r/64]|=1ull<<(r%64);int borrowed=-1;int restoreCat=atoi(argv[4]);for(int k=0;k<es.size();k++){E e=es[rev?es.size()-1-k:k];if(e.op==1){if(omit&&e.z==restoreCat)continue;for(int j=0;j<nw;j++)rows[e.x][j]^=rows[e.y][j];}else if(e.op==(rev?3:2)){ck(borrowed==-1,"replay temp");rows[n]=rows[e.x];borrowed=e.x;}else if(e.op==(rev?2:3)){ck(borrowed==e.x&&rows[n]==rows[e.x],"erase scalar restoration");borrowed=-1;}}
int bad=0;for(int r=0;r<n;r++){rows[r][r/64]^=1ull<<(r%64);if(r>=v&&r<2*v)rows[r][(r-v)/64]^=1ull<<((r-v)%64);bool wrong=any_of(rows[r].begin(),rows[r].end(),[](uint64_t x){return x;});bad+=wrong;}ck(borrowed==-1,"temp replay complete");if(omit)ck(bad>0,"restoration omission must fail");else ck(bad==0,"all-column endpoint");return bad;};int fw=replay(false,false),iv=replay(true,false),om=replay(false,true);
map<int,int>census;int deleted=0;long long rankMass=0;for(int r=2*v;r<n;r++){int a=initial.at(r),b=final.at(r);subset(a,b);int d=fs.at(b).d-fs.at(a).d;census[d]++;rankMass+=d;if(!d)deleted++;}J censusJ=J::object();for(auto[r,c]:census)if(r)censusJ[to_string(r)]=c;ck(censusJ==tiling["census"],"residual census tiling");map<int,long long>slots;int banks=0;for(auto pat:tiling["patterns"]){int count=pat["count"],width=0;for(int w:pat["widths"]){slots[w]+=count;width+=w;}ck(width==m,"bank width");banks+=count;}for(auto[r,c]:census)if(r)ck(slots[r]==1ll*T*c,"T_ADAPTED exact supply");ck(rankMass*T==1ll*m*banks,"bank conservation");long long stock=4ll*v*T+5ll*banks;map<int,long long>paidCounts=paid;long long paidcalls=0,paidmass=0;for(auto[r,c]:paid){paidcalls+=c;paidmass+=r*c;}J result={{"status","PASS_INDEPENDENT_LITERAL_COMBINED_WORD_ENDPOINTS_REFLECTIONS_T_ADAPTED_CENSUS"},{"records",es.size()},{"scalar_ADDs",adds},{"signed_coefficients",coeff},{"moves",moves},{"copies",copies},{"erasures",erasures},{"paid_calls",paidcalls},{"paid_rank_mass",paidmass},{"paid_histogram",paid},{"required_histogram",required},{"reflected_histogram",reflected},{"unique_nonsame_frame_pairs",pairs.size()},{"forward_wrong_rows",fw},{"inverse_wrong_rows",iv},{"omission_wrong_rows",om},{"residual_census",censusJ},{"deleted_roles",deleted},{"endpoint_rank_mass_per_replica",rankMass},{"banks_per_stage",banks},{"literal_stock",stock},{"normalized_stock",stock/5},{"scope","Independent actual binary and endpoint ledger audit; finite prime chart and exact price checked in native pipeline."}};ofstream(out+"/RESULT.json")<<result.dump(2)<<"\n";cout<<result.dump(2)<<endl;
}
