#include "frame-algebra.hpp"
#include <climits>
I determinant(std::vector<std::vector<I>> a){int n=a.size();if(!n)return 1;I prev=1;int sign=1;for(int k=0;k<n-1;k++){int p=k;while(p<n&&!a[p][k])p++;if(p==n)return 0;if(p!=k){std::swap(a[p],a[k]);sign=-sign;}I q=a[k][k];for(int i=k+1;i<n;i++)for(int j=k+1;j<n;j++){I z=a[i][j]*q-a[i][k]*a[k][j];if(z%prev)throw std::runtime_error("Bareiss exact division");a[i][j]=z/prev;}for(int i=k+1;i<n;i++)a[i][k]=0;prev=q;}return sign*a[n-1][n-1];}
I activeGramWitness(int f){int n=fr[f].B.size();Mat U=n<=12?fr[f].B:fr[f].A;int d=U.size();std::vector<I>s(d);for(int i=0;i<d;i++)for(I x:U[i])s[i]+=x;std::vector<std::vector<I>>a(d,std::vector<I>(d));for(int i=0;i<d;i++)for(int j=0;j<d;j++)a[i][j]=n<=12?9*dot(U[i],U[j])-s[i]*s[j]:-15*dot(U[i],U[j])+s[i]*s[j];return absI(determinant(a));}
I smallRemainder(I d){d=absI(d);if(!d)throw std::runtime_error("zero rank or Gram determinant");for(int p=2;p<1000;p++)while(d%p==0)d/=p;if(d>=((I)1<<80))throw std::runtime_error("unproved exceptional prime >=2^80");return d;}
I rankMinor(const Mat&M){Mat reduced=red(M);int d=reduced.size();Mat independent;if((int)M.size()==d)independent=M;else for(const Row&r:M){Mat proposed=independent;proposed.push_back(r);if(red(proposed).size()>independent.size())independent.push_back(r);if((int)independent.size()==d)break;}std::vector<int>cols;for(const Row&r:reduced){int c=0;while(c<24&&!r[c])c++;if(c==24)throw std::runtime_error("zero rank row");cols.push_back(c);}std::vector<std::vector<I>>a(d,std::vector<I>(d));for(int i=0;i<d;i++)for(int j=0;j<d;j++)a[i][j]=independent[i][cols[j]];I det=absI(determinant(a));smallRemainder(det);return det;}
int main(int argc,char**argv){try{if(argc!=4)throw std::runtime_error("usage INPUT FINAL_BASES OUT");std::string D=argv[1];json w=load(D+"/word_p12.json"),g=load(D+"/graph_p12.json"),fj=load(D+"/frames_p12.json"),k=load(D+"/kchron_p12.json"),sn=load(D+"/sinks.json"),bases=load(argv[2]);std::set<int>active,loadedRaw;std::map<std::string,long long>category;json literalCertificates=json::array();std::map<int,int>override;std::set<int>omitted;if(w.contains("omitted_ops"))for(auto i:w["omitted_ops"])omitted.insert(i.get<int>());for(auto b:bases){int i=b[0];if(i<0||i>=(int)w["ops"].size()||override.count(i))throw std::runtime_error("override operation index");Mat B=parseMat(b[1]);int f=addB(B);rankMinor(B);override[i]=f;}
auto raw=[&](int old){if(!orig.count(old)){const auto&z=fj["frames"][std::to_string(old)];Mat literal;int f;if(z.contains("b")){literal=parseMat(z["b"]);f=addB(literal);}else if(z.contains("a")){literal=parseMat(z["a"]);f=addA(literal);}else throw std::runtime_error("frame lacks b/a");if((int)fr[f].B.size()!=z["dim"].get<int>())throw std::runtime_error("advertised original frame dimension mismatch");I d=rankMinor(literal);literalCertificates.push_back({{"original_frame",old},{"schema",z.contains("b")?"basis_b":"annihilator_a"},{"rank_minor_abs",si(d)},{"after_small_factor_removal",si(smallRemainder(d))}});orig[old]=f;loadedRaw.insert(old);}return orig.at(old);};auto use=[&](int f,const std::string&c){active.insert(f);category[c]++;};use(addB({}),"empty");use(raw(w["full_frame"]),"full");for(int i=0;i<(int)w["ops"].size();i++)if(!omitted.count(i))use(override.count(i)?override.at(i):raw(w["op_frame"][i]),"active_operation");for(auto f:w["source_frame"])use(raw(f.get<int>()),"source");for(auto z:w["gauges"])use(raw(z["frame"]),"gauge");for(auto f:w["root_frame"])use(raw(f.get<int>()),"root_or_terminal_root");for(auto z:k["entries"]){use(raw(z["mix_frame"]),"original_source_mix");use(raw(z["deliver_frame"]),"source_delivery");}if(w.contains("retimed_partner_mixes"))for(auto z:w["retimed_partner_mixes"])use(raw(z["mix_frame"]),"retimed_source_mix");for(int t=0;t<g["v"].get<int>();t++){Row cov{};for(I&x:cov)x=-1;for(auto c:g["labels"][t])cov[c.get<int>()]+=3;use(addA({cov}),"terminal_covector_kernel");}
json witnesses=json::array();long long pivots=0;I maxPivot=0;for(int f:active){for(const Mat*M:{&fr[f].B,&fr[f].A})for(const Row&r:*M){int c=0;while(c<24&&!r[c])c++;if(c==24)throw std::runtime_error("zero reduced basis row");I p=absI(r[c]);if(p>=((I)1<<80))throw std::runtime_error("pivot not below retained-prime threshold");if(p>maxPivot)maxPivot=p;pivots++;}I bdet=rankMinor(fr[f].B),adet=rankMinor(fr[f].A),gram=activeGramWitness(f);I rem=smallRemainder(gram);witnesses.push_back({{"frame",f},{"dimension",fr[f].B.size()},{"basis_rank_minor_abs",si(bdet)},{"annihilator_rank_minor_abs",si(adet)},{"scaled_gram_determinant_abs",si(gram)},{"gram_after_small_factor_removal",si(rem)}});}
json result={{"status","PASS_ALL_ACTIVE_FINAL_FRAME_RETAINED_PRIMES"},{"prime_range","every prime p > 2^80"},{"final_basis_override_entries",bases.size()},{"all_distinct_active_frames",active.size()},{"freshly_loaded_inherited_original_frames",loadedRaw.size()},{"active_occurrences_by_category",category},{"literal_basis_and_annihilator_pivots_checked",pivots},{"largest_pivot_abs",si(maxPivot)},{"literal_input_rank_certificates",literalCertificates},{"active_frame_certificates",witnesses},{"unused_historical_frames_checked",false},{"inherited_prime_certificates_freshly_closed",true},{"scope","Every active final operation and retained source/gauge/root/mix/delivery/terminal-covector frame: exact rational dimension and literal rank minors, reduced basis/annihilator pivots, scaled restricted-Gram units for all primes p>2^80. No frame-path/scalar/profile/price transfer from this check alone."}};std::ofstream(argv[3])<<result.dump(2)<<"\n";result.erase("literal_input_rank_certificates");result.erase("active_frame_certificates");std::cout<<result.dump(2)<<"\n";return 0;}catch(std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}

