#include "new-frame-algebra.hpp"
using Q=boost::multiprecision::cpp_rational;
void need(bool b,const std::string&s){if(!b)throw std::runtime_error(s);}struct Factor{std::string op;int i,j;I n,d;};
struct Chart{std::vector<std::vector<I>>B,C;I den;std::vector<Factor>ops;};
Factor ratio(std::string op,int i,int j,I n,I d){I g=gcdI(n,d);n/=g;d/=g;if(d<0){d=-d;n=-n;}return {op,i,j,n,d};}
Chart inverseI(std::vector<std::vector<I>>B){int n=B.size();std::vector<std::vector<I>>M(n,std::vector<I>(2*n));for(int i=0;i<n;i++){for(int j=0;j<n;j++)M[i][j]=B[i][j];M[i][n+i]=1;}I previous=1;std::vector<Factor>ops;for(int k=0;k<n;k++){int pivot=k;while(pivot<n&&!M[pivot][k])pivot++;need(pivot<n,"singular chart");if(pivot!=k){std::swap(M[k],M[pivot]);ops.push_back({"swap",k,pivot,1,1});}I p=M[k][k];if(p!=previous)ops.push_back(ratio("scale",k,k,previous,p));for(int i=0;i<n;i++)if(i!=k){I u=M[i][k];if(u)ops.push_back(ratio("add",i,k,-u,previous));for(int j=0;j<2*n;j++)if(j!=k){I value=p*M[i][j]-u*M[k][j];need(value%previous==0,"fraction-free exact division");M[i][j]=value/previous;}M[i][k]=0;}previous=p;}I d=M[0][0];need(d!=0,"chart invertibility");std::vector<std::vector<I>>C(n,std::vector<I>(n));for(int i=0;i<n;i++)for(int j=0;j<n;j++){need(M[i][j]==d*int(i==j),"chart reduced block");C[i][j]=M[i][n+j];}I common=absI(d);for(auto&r:C)for(I x:r)common=gcdI(common,x);d/=common;for(auto&r:C)for(I&x:r)x/=common;if(d<0){d=-d;for(auto&r:C)for(I&x:r)x=-x;}return {B,C,d,ops};}
int main(int argc,char**argv){try{need(argc==3,"source-bank INPUT OUTPUT");std::string D=argv[1];json w=load(D+"/word_p12.json"),g=load(D+"/graph_p12.json"),fj=load(D+"/frames_p12.json"),sinks=load(D+"/sinks.json");json copyBorrow=load(D+"/BORROW.json"),gaugeBorrow=load(D+"/GAUGE-BORROW.json");need(copyBorrow==w["borrowed_sources"]&&gaugeBorrow==w["gauge_source_aliases"],"literal source alias metadata");std::set<int>borrowed,sourceIDs;for(auto rows:{copyBorrow,gaugeBorrow})for(auto e:rows){need(borrowed.insert(e["role"].get<int>()).second&&sourceIDs.insert(e["source"].get<int>()).second,"distinct physical source aliases and original sources");}int R=0;auto roleID=[&](int x){R=std::max(R,x+1);};for(auto o:w["ops"]){roleID(o[0]);roleID(o[1]);}for(auto q:w["pairs"]){roleID(q[0]);roleID(q[1]);}for(auto q:w["rootroles"])roleID(q);for(auto q:w["gauges"])roleID(q["role"]);need(g["h"].get<int>()==24,"frozen dimension24 bank construction");std::set<int>initialVirtual;for(auto p:w["pairs"])initialVirtual.insert(p[1].get<int>());for(auto gaugeEntry:w["gauges"]){if(initialVirtual.count(gaugeEntry["role"].get<int>())||borrowed.count(gaugeEntry["role"].get<int>()))continue;int old=gaugeEntry["frame"].get<int>();if(orig.count(old))continue;auto z=fj["frames"].at(std::to_string(old));int id=z.contains("b")?addB(parseMat(z["b"])):addA(parseMat(z["a"]));need(fr[id].B.size()==z["dim"].get<int>(),"frame rank");orig[old]=id;}
std::set<int>virtuals,removed;for(auto p:w["pairs"])virtuals.insert(p[1].get<int>());for(auto e:sinks)removed.insert(w["rootroles"][e["root"].get<int>()].get<int>());std::map<int,int>gauge;std::map<int,int>chartcount;for(auto z:w["gauges"]){int s=z["role"];if(!virtuals.count(s)&&!borrowed.count(s)){need(!removed.count(s),"gauge terminal overlap");int f=orig[z["frame"].get<int>()];gauge[s]=f;chartcount[f]++;}}
std::map<int,std::vector<int>>families;for(int s=0;s<R;s++)if(!virtuals.count(s)&&!removed.count(s)){if(borrowed.count(s))continue;int r=gauge.count(s)?24-fr[gauge[s]].B.size():24;families[r].push_back(s);}long long physical=0;for(auto[r,ss]:families){need(r==4||r==5||r==6||r==11||r==12||r==24,"supported residual rank");physical+=ss.size();}need(physical==R-(long long)virtuals.size()-removed.size()-borrowed.size(),"complete source-owned physical inventory");int maxops=0;I maxnum=0,maxden=0;json charts=json::array();for(auto[f,count]:chartcount){auto A=fr[f].A,B=fr[f].B;Mat residual;for(auto a:A){I sum=0;for(I x:a)sum+=x;Row row{};for(int j=0;j<24;j++)row[j]=15*a[j]-sum;I div=0;for(I x:row)div=gcdI(div,x);need(div!=0,"residual row");for(I&x:row)x/=div;residual.push_back(row);}need(residual.size()+B.size()==24,"chart dimensions");for(auto&a:residual)for(auto&b:B){I sa=0,sb=0;for(I x:a)sa+=x;for(I x:b)sb+=x;need(9*dot(a,b)-sa*sb==0,"residual gauge orthogonality");}Mat all=residual;all.insert(all.end(),B.begin(),B.end());std::vector<std::vector<I>>basis(24,std::vector<I>(24));for(int i=0;i<24;i++)for(int j=0;j<24;j++)basis[i][j]=all[j][i];Chart c=inverseI(basis);for(int i=0;i<24;i++)for(int j=0;j<24;j++){I bc=0,cb=0;for(int k=0;k<24;k++){bc+=c.B[i][k]*c.C[k][j];cb+=c.C[i][k]*c.B[k][j];}need(bc==c.den*int(i==j)&&cb==c.den*int(i==j),"two inverse identities");}
std::vector<std::vector<Q>>replay(24,std::vector<Q>(24));for(int i=0;i<24;i++)for(int j=0;j<24;j++)replay[i][j]=c.B[i][j];for(auto op:c.ops){maxnum=std::max(maxnum,absI(op.n));maxden=std::max(maxden,op.d);Q q=Q(op.n)/Q(op.d);if(op.op=="swap")std::swap(replay[op.i],replay[op.j]);else for(int j=0;j<24;j++){if(op.op=="scale")replay[op.i][j]*=q;else replay[op.i][j]+=q*replay[op.j][j];}}for(int i=0;i<24;i++)for(int j=0;j<24;j++)need(replay[i][j]==int(i==j),"elementary factor replay");maxops=std::max(maxops,(int)c.ops.size());maxden=std::max(maxden,c.den);json bj=json::array(),cj=json::array(),factors=json::array();for(int i=0;i<24;i++){json br=json::array(),cr=json::array();for(int j=0;j<24;j++){br.push_back(si(c.B[i][j]));cr.push_back(si(c.C[i][j]));}bj.push_back(br);cj.push_back(cr);}for(auto op:c.ops)factors.push_back({op.op,op.i,op.j,si(op.n),si(op.d)});charts.push_back({{"frame",f},{"occurrences",count},{"residual_rank",residual.size()},{"basis",bj},{"inverse_numerator",cj},{"denominator",si(c.den)},{"elementary_factors",factors},{"factors",c.ops.size()}});}
std::cerr<<"Actual charts="<<chartcount.size()<<" maxops="<<maxops<<" maxnum="<<maxnum<<" maxden="<<maxden<<"\n";need(maxnum<((I)1<<80)&&maxden<((I)1<<80),"units at all retained primes");std::vector<std::pair<std::vector<int>,int>>patterns;auto push=[&](std::vector<int>w,long long n){need(n>=0&&n<2147483647,"pattern capacity");if(n)patterns.push_back({w,(int)n});};std::vector<int>mix(4,5);mix.insert(mix.end(),13,4);push(mix,18*families[5].size());std::vector<int>mix11(4,11);mix11.insert(mix11.end(),7,4);push(mix11,18*families[11].size());push(std::vector<int>(18,4),4LL*families[4].size()-7LL*families[11].size()-13LL*families[5].size());push(std::vector<int>(12,6),6*families[6].size());push(std::vector<int>(6,12),12*families[12].size());push(std::vector<int>(3,24),24*families[24].size());long long stageBanks=0;json patternLedger=json::array(),familyLedger=json::object();for(auto[w,n]:patterns){stageBanks+=n;patternLedger.push_back({{"widths",w},{"count_per_stage",n}});}for(auto[r,ss]:families)if(!ss.empty())familyLedger[std::to_string(r)]=ss.size();long long assignments=0,banks=0;json normalizers=json::array(),controls=json::array();for(int stage=0;stage<3;stage++){std::map<int,int>used;std::set<std::pair<int,int>>occupancy;long long nb=0;for(auto[widths,count]:patterns){int sum=0;for(int r:widths)sum+=r;need(sum==72,"bank coordinate partition");int outside=stage==0?24:0,offset=0;std::set<std::pair<int,int>>distinct;json witness=json::array();for(int b=0;b<(int)widths.size();b++){int r=widths[b];std::vector<int>src,dst;for(int j=0;j<r;j++){src.push_back(24*stage+j);dst.push_back(offset+j);}for(int j=0;j<72;j++){if(!(j>=24*stage&&j<24*stage+r))src.push_back(j);if(!(j>=offset&&j<offset+r))dst.push_back(j);}std::vector<int>pi(72);for(int j=0;j<72;j++)pi[src[j]]=dst[j];need(std::set<int>(pi.begin(),pi.end()).size()==72,"normalizer permutation");need(distinct.insert({pi[outside],b+1}).second,"normalizer column distinctness");witness.push_back({pi[outside],b+1});offset+=r;}normalizers.push_back({{"stage",stage},{"widths",widths},{"outside_column",outside},{"distinct_scaled_columns",witness}});
for(int n=0;n<count;n++){int off=0;for(int r:widths){int q=used[r]++,role=families[r].at(q/72),replica=q%72;need(occupancy.insert({role,replica}).second,"repeated role-copy-stage assignment");assignments++;off+=r;}need(off==72,"literal complete bank");nb++;}
if(stage==0){auto endpoint=[&](std::vector<int>ids){std::vector<int>x(144);for(int i=0;i<144;i++)x[i]=i;for(int b:ids){int off=0;for(int i=0;i<b;i++)off+=widths[i];for(int i=off;i<off+widths[b];i++)std::swap(x[i],x[72+i]);}return x;};std::vector<int>ids,full(144),identity(144);for(int b=0;b<(int)widths.size();b++)ids.push_back(b);for(int i=0;i<144;i++){full[i]=(i+72)%144;identity[i]=i;}need(endpoint(ids)==full,"complete bank swap");auto twice=ids;for(auto it=ids.rbegin();it!=ids.rend();++it)twice.push_back(*it);need(endpoint(twice)==identity,"restored arbitrary correlated dirty contents");auto omit=ids;omit.pop_back();need(endpoint(omit)!=full,"omitted block control");auto repeat=ids;repeat.push_back(0);need(endpoint(repeat)!=full,"repeated block control");controls.push_back({{"widths",widths},{"omitted_last","REJECTED"},{"repeated_first","REJECTED"}});}}
need(nb==stageBanks&&occupancy.size()==72*physical,"stage bank stock");for(auto[r,roles]:families)need(used[r]==72*roles.size(),"complete family allocation");banks+=nb;}
long long literal=banks+72*2*g["v"].get<int>();long long K=2LL*3*72*((literal-1)+physical*72*(maxops+71+72));need(assignments==physical*72*3&&banks==stageBanks*3&&literal==banks+144LL*g["v"].get<int>()&&K<(1LL<<40),"complete actual bank/routing invoice");json out={{"status","PASS_NATIVE_COMPLETE_BANKS_CHARTS_NORMALIZERS"},{"charts",charts},{"residual_families",familyLedger},{"bank_patterns",patternLedger},{"physical_dirty_roles",physical},{"copy_elision_sources",copyBorrow.size()},{"gauge_owned_sources",gaugeBorrow.size()},{"max_factors",maxops},{"max_factor_numerator",si(maxnum)},{"max_denominator",si(maxden)},{"assignments",assignments},{"banks_total",banks},{"literal_stock",literal},{"borrowed_physical_slots",borrowed.size()},{"physical_replicas",72},{"arithmetic_normalization",24},{"selector_calls",K},{"normalizers",normalizers},{"controls",controls},{"scope","Complete residual banks replace remaining auxiliary entrance exteriors only; all source-owned correlated gauge entrances excluded. Chart algebra is ring-general after checked unit bounds; all-size restored selector and compiler remain inherited."}};std::ofstream(argv[2])<<out.dump(2)<<"\n";std::cout<<json{{"status",out["status"]},{"charts",charts.size()},{"max_factors",maxops},{"assignments",assignments},{"literal_stock",literal},{"selector_calls",K}}.dump(2)<<"\n";return 0;}catch(std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}






