#include "new-frame-algebra.hpp"
void need(bool b,const std::string&s){if(!b)throw std::runtime_error(s);}
struct Event{std::string tag;int op,f;};using H=std::map<int,long long>;
int main(int argc,char**argv){try{need(argc==3,"passive-boundary INPUT OUTPUT");std::string D=argv[1];auto w=load(D+"/word_p12.json"),g=load(D+"/graph_p12.json"),fj=load(D+"/frames_p12.json"),k=load(D+"/kchron_p12.json"),sel=load(D+"/BORROW.json"),sinks=load(D+"/sinks.json");
auto frame=[&](int f){if(orig.count(f))return orig[f];auto z=fj["frames"].at(std::to_string(f));int id=z.contains("b")?addB(parseMat(z["b"])):addA(parseMat(z["a"]));need(fr[id].B.size()==z["dim"].get<int>(),"literal frame rank");return orig[f]=id;};
int N=w["ops"].size(),R=18908;std::vector<int>F(N),phys(R),pos(N);for(int r=0;r<R;r++)phys[r]=r;for(int i=0;i<N;i++)F[i]=w["op_frame"][i];std::map<int,Mat>override;for(auto z:load(D+"/current-bases.json"))override[z[0].get<int>()]=parseMat(z[1]);auto opframe=[&](int i){return override.count(i)?addB(override[i]):frame(F[i]);};
std::set<int>phase,source,gauged,virtuals,terminal,borrowed,passiveSources,carrierSources,allPairSources,borrowedOriginalSources;int tick=0;for(auto p:w["phase1"]){phase.insert(p.get<int>());pos[p.get<int>()]=tick++;}for(int i=0;i<N;i++)if(!phase.count(i))pos[i]=tick++;for(auto&[n,s]:w["sources"].items())source.insert(s.get<int>());std::map<int,json>gauges,kp;for(auto z:w["gauges"]){gauged.insert(z["role"].get<int>());gauges[z["role"].get<int>()]=z;}std::map<int,int>recipient;for(auto p:w["pairs"]){int a=p[0],b=p[1];need(!recipient.count(a),"unique donor");recipient[a]=b;virtuals.insert(b);phys[b]=a;}for(auto z:sinks)terminal.insert(w["rootroles"][z["root"].get<int>()].get<int>());for(auto e:k["entries"]){int a=e["carrier"],b=e["passive"];need(allPairSources.insert(a).second&&allPairSources.insert(b).second,"disjoint external partner pairs");carrierSources.insert(a);passiveSources.insert(b);kp[b]=e;}
std::vector<std::vector<int>>touch(R);for(int i=0;i<N;i++){int a=w["ops"][i][0],b=w["ops"][i][1];need(phys[a]!=phys[b],"distinct physical shear slots");touch[a].push_back(i);touch[b].push_back(i);}std::vector<std::vector<std::pair<int,int>>>roots(R);for(int j=0;j<(int)w["rootroles"].size();j++)roots[w["rootroles"][j].get<int>()].push_back({j,w["root_frame"][j].get<int>()});
auto hist=[&](int start,const std::vector<Event>&es){H h;int prev=start;for(auto e:es){need(prev<0||sub(prev,e.f),"nonnested physical path: "+e.tag+" op "+std::to_string(e.op));int d=fr[e.f].B.size()-(prev<0?0:fr[prev].B.size());if(d)h[d]++;prev=e.f;}return h;};
H delta;json results=json::array();int aliases=0;long long inclusions=0;std::set<int>omitted,earlyops;for(auto r:sel){int s=r["role"],n=r["source"],i=r["omit_copy"],early=r["early"],carrier=r["partner"];need(borrowed.insert(s).second&&borrowedOriginalSources.insert(n).second,"unique borrowed role and original source");need(!gauged.count(s)&&!source.count(s)&&!virtuals.count(s)&&!terminal.count(s),"borrowed physical eligibility");need(!touch[s].empty()&&touch[s][0]==i&&w["ops"][i][0].get<int>()==s&&w["ops"][i][2].get<int>()==n&&phase.count(i),"literal original first source copy");need(w["ops"][i][1].get<int>()==w["sources"][std::to_string(n)].get<int>(),"omitted copy uses retained actual source");need(omitted.insert(i).second&&earlyops.insert(early).second,"unique removed and retimed events");auto e=kp.at(n);need(e["carrier"].get<int>()==carrier,"literal carrier pair");need(!carrierSources.count(n),"borrowed original source never an external carrier");int retained=w["sources"][std::to_string(n)];for(int q:touch[retained])if(pos[q]<pos[i])need(w["ops"][q][0].get<int>()!=retained,"retained source clean signal unchanged before omitted copy");int line=frame(w["source_frame"][n]),mix=frame(e["mix_frame"]);need(fr[line].B.size()==1,"original singleton source line");need(sub(frame(w["source_frame"][carrier]),mix),"carrier line to early mix");
std::vector<int>rs{s};if(recipient.count(s)){int b=recipient[s];aliases++;need(r["aliased_to"].get<int>()==b&&gauges.count(b)&&phys[b]==s,"literal donor recipient alias");int last=-1;for(int op:touch[s])last=std::max(last,pos[op]);need(last<w["reads"][std::to_string(b)].get<int>(),"donor completes before recipient gauge");rs.push_back(b);}else need(r["aliased_to"].is_null(),"no fictitious donor alias");
std::vector<Event>es;for(int ix=0;ix<(int)rs.size();ix++){int role=rs[ix];if(ix)es.push_back({"alias-gauge",role,frame(gauges[role]["frame"])});for(int op:touch[role])es.push_back({"op",op,opframe(op)});for(auto[j,f]:roots[role])es.push_back({"root",j,frame(f)});}es.push_back({"full",s,frame(w["full_frame"])});auto old=hist(-1,es);std::vector<Event>rev;bool inserted=false;for(auto ev:es){if(ev.tag=="op"&&ev.op==i)continue;int cut=ev.tag=="op"?pos[ev.op]:ev.tag=="alias-gauge"?w["reads"][std::to_string(ev.op)].get<int>():ev.tag=="root"?(g["roots"][ev.op]["kind"]=="center"?(int)phase.size():N+ev.op):N+(int)w["rootroles"].size()+1;if(!inserted&&cut>=pos[early]){rev.push_back({"early",early,mix});inserted=true;}rev.push_back(ev);}need(inserted,"early chronological cut on physical path role "+std::to_string(s));for(auto ev:rev){if(ev.tag=="early")break;if(ev.tag=="op")need(phys[w["ops"][ev.op][0].get<int>()]!=s,"borrowed source written before early capture");}auto fresh=hist(line,rev);inclusions+=es.size()+rev.size();std::vector<Event>pass;for(int j=1;j<(int)e["passive_chain"].size();j++)pass.push_back({"original-passive",j,frame(e["passive_chain"][j])});auto ext=hist(frame(e["passive_chain"][0]),pass);need(ext==H{{1,1},{22,1}},"literal old external passive chain");H local=fresh;for(auto[d,c]:old)local[d]-=c;for(auto[d,c]:ext)local[d]-=c;long long mass=0;for(auto[d,c]:local){delta[d]+=c;mass+=d*c;}need(mass==-24,"local paid rank mass");std::vector<int>dims{(int)fr[line].B.size()};for(auto ev:rev)dims.push_back(fr[ev.f].B.size());H reflected;for(int j=dims.size()-1;j>0;j--)if(dims[j]!=dims[j-1])reflected[dims[j]-dims[j-1]]++;need(reflected==fresh,"complement reversed physical chain");auto jh=[](const H&h){json z=json::object();for(auto[d,c]:h)if(c)z[std::to_string(d)]=c;return z;};results.push_back({{"role",s},{"source",n},{"carrier",carrier},{"omitted_copy",i},{"early_operation",early},{"alias",recipient.count(s)?json(recipient[s]):json(nullptr)},{"old_aux_histogram",jh(old)},{"new_external_source_histogram",jh(fresh)},{"local_delta",jh(local)}});}
need(sel==w["borrowed_sources"],"literal borrowing metadata equals selected construction");std::set<int>listed;for(auto z:w["omitted_ops"])listed.insert(z.get<int>());need(listed==omitted,"all and only literal omitted source copies");for(auto it=delta.begin();it!=delta.end();)if(!it->second)it=delta.erase(it);else ++it;need(sel.size()==440&&aliases==67&&delta==H{{2,-440},{22,-440}},"literal global source splice invoice");json out={{"status","PASS_NATIVE_440_SOURCE_PHYSICAL_BOUNDARIES"},{"borrowed_sources",440},{"donor_alias_chains",aliases},{"checked_path_steps",inclusions},{"local_histogram_delta",{{"2",-440},{"22",-440}}},{"shared_histogram_delta",{{"2",-1320},{"22",-1320}}},{"shared_rank_mass_delta",-31680},{"shared_stock_delta",-440},{"shared_deficit_delta",0},{"original_source_lines_preserved",true},{"donor_recipient_chronology_preserved",true},{"all_early_values_original",true},{"reflected_chains_verified",true},{"results",results},{"scope","Exact sufficient physical source-path construction and paid histogram; complete dirty/source scalar replay is a separate native audit."}};std::ofstream(argv[2])<<out.dump(2)<<"\n";out.erase("results");std::cout<<out.dump(2)<<"\n";return 0;}catch(std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}



