#!/usr/bin/env python3
"""Verify every unique pinned Lean module once, with complete theorem/lemma audits.

Requires an existing Lean4.21.0/Lake + pinned Mathlib project; installs nothing.
The static inventory is reviewed data, never regenerated by this command.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

HERE=Path(__file__).resolve().parent
ROOTS=('next-proof','transfer-proof','full-transfer','stream-transfer/counters')
ALLOWED={'propext','Classical.choice','Quot.sound'}
AUDIT=re.compile(r"^'([^']+)' (?:depends on axioms: \[([^\]]*)\]|does not depend on any axioms)",re.M)
DECL=re.compile(r'^\s*(?:@\[[^\]]*\]\s*)*(theorem|lemma)\s+([A-Za-z_][A-Za-z_0-9\']*)\b',re.M)


def require(ok,message):
    if not ok:
        raise SystemExit(message)


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def code_only(source):
    """Remove nested block comments, line comments and string contents, preserving lines."""
    out=[]; i=0; depth=0; string=False
    while i<len(source):
        if depth:
            if source.startswith('/-',i):depth+=1;out.extend('  ');i+=2
            elif source.startswith('-/',i):depth-=1;out.extend('  ');i+=2
            else:out.append('\n' if source[i]=='\n' else ' ');i+=1
        elif string:
            if source[i]=='\\' and i+1<len(source):out.extend('  ');i+=2
            elif source[i]=='"':string=False;out.append(' ');i+=1
            else:out.append('\n' if source[i]=='\n' else ' ');i+=1
        elif source.startswith('/-',i):depth=1;out.extend('  ');i+=2
        elif source.startswith('--',i):
            end=source.find('\n',i)
            if end<0:end=len(source)
            out.extend(' '*(end-i));i=end
        elif source[i]=='"':string=True;out.append(' ');i+=1
        else:out.append(source[i]);i+=1
    require(depth==0 and not string,'Unterminated comment/string')
    return ''.join(out)


def collect():
    files=[]
    for root in ROOTS:
        folder=HERE/root
        require(folder.is_dir(),'Missing source root: '+root)
        files.extend(sorted(folder.rglob('*.lean')))
    grouped={}
    for file in files:
        require(not file.is_symlink(),'Symlinked proof source: '+str(file))
        grouped.setdefault(file.stem,[]).append(file)
    modules={}
    for name,paths in sorted(grouped.items()):
        raw=paths[0].read_bytes()
        require(all(p.read_bytes()==raw for p in paths),'Conflicting duplicate basename: '+name)
        code=code_only(raw.decode())
        require(not re.search(r'\b(sorry|admit|native_decide)\b',code),'Proof escape: '+name)
        require(not re.search(r'^\s*(?:axiom|constant)\s',code,re.M),'New axiom: '+name)
        require(not re.search(r'^\s*(?:private|protected)\s+(?:theorem|lemma)\b',code,re.M),'Unsupported private/protected theorem inventory: '+name)
        namespaces=re.findall(r'^\s*namespace\s+(\S+)\s*$',code,re.M)
        require(namespaces==[name],'Review namespace parser for '+name)
        decl=DECL.findall(code)
        names=[name+'.'+n for _,n in decl]
        require(len(names)==len(set(names)) and names,'Duplicate/empty declaration inventory: '+name)
        printed=[n if '.' in n else name+'.'+n for n in re.findall(r'^\s*#print\s+axioms\s+(\S+)\s*$',code,re.M)]
        require(len(printed)==len(set(printed)) and set(printed)<=set(names),'Unexpected existing axiom print: '+name)
        imports=[]
        for line in re.findall(r'^\s*import\s+([^\n]+)',code,re.M):imports.extend(line.split())
        require(len(imports)==len(set(imports)),'Duplicate imports: '+name)
        modules[name]={'paths':[str(p.relative_to(HERE)) for p in paths],
            'sha256':hashlib.sha256(raw).hexdigest(),'imports':imports,
            'theorems':names,'theorem_count':sum(k=='theorem' for k,_ in decl),
            'lemma_count':sum(k=='lemma' for k,_ in decl),'existing_axiom_prints':printed,
            'additional_audits':[n for n in names if n not in printed]}
    for name,record in modules.items():
        for imp in record['imports']:
            require(imp in modules or imp=='Std' or imp.startswith('Mathlib.'),'Unresolved/nonpinned import '+imp+' in '+name)
    done=set();order=[]
    while len(done)<len(modules):
        ready=sorted(n for n,r in modules.items() if n not in done and all(i not in modules or i in done for i in r['imports']))
        require(ready,'Local import cycle')
        for n in ready:done.add(n);order.append(n)
    manifests={}
    for root in ROOTS:
        for filename in ('theorem-manifest.json','proof-manifest.json','declaration-scope-map.json'):
            for p in sorted((HERE/root).rglob(filename)):
                manifests[str(p.relative_to(HERE))]=digest(p)
    return {'schema_version':1,'lean_toolchain':'leanprover/lean4:v4.21.0',
        'mathlib':{'url':'https://github.com/leanprover-community/mathlib4','rev':'308445d7985027f538e281e18df29ca16ede2ba3','inputRev':'v4.21.0'},
        'allowed_axioms':sorted(ALLOWED),'source_roots':list(ROOTS),'modules':modules,
        'compile_order':order,'component_manifests':manifests,
        'source_file_count':len(files),'unique_module_count':len(modules),
        'unique_declaration_count':sum(len(r['theorems']) for r in modules.values()),
        'additional_helper_audit_count':sum(len(r['additional_audits']) for r in modules.values()),
        'reused_earlier_dirtywrapper_declarations':len(modules['DirtyWrapper']['theorems']),
        'scope':'Audits every named theorem/lemma in these modules, including helpers omitted from historical selected audits. Duplicate basenames are compiled once only after byte equality. This is not a complete multiplication theorem.'}


def parse_audits(text,expected,module):
    entries=AUDIT.findall(text)
    require(len(entries)==len(expected) and {n for n,_ in entries}==set(expected),'Incomplete or duplicate axiom audit: '+module)
    result={n:sorted({x.strip() for x in a.split(',') if x.strip()}) for n,a in entries}
    require(all(set(a)<=ALLOWED for a in result.values()),'Nonstandard axiom: '+module)
    return result


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--lake-project',required=True,type=Path,help='Existing pinned Mathlib project')
    parser.add_argument('--output',required=True,type=Path,help='Directory outside this publication package')
    parser.add_argument('--sources-only',action='store_true',help='Check immutable source inventory and pins, without compilation')
    args=parser.parse_args()
    project=args.lake_project.resolve();output=args.output.resolve()
    require(output!=HERE and HERE not in output.parents,'--output must be outside the publication package')
    inventory_path=HERE/'lean-inventory.json';inventory=json.loads(inventory_path.read_text())
    actual=collect()
    require(actual==inventory,'Static Lean inventory or component-manifest mismatch; review changed files')
    require((project/'lean-toolchain').read_text().strip()==inventory['lean_toolchain'],'Wrong project Lean pin')
    pkgs=json.loads((project/'lake-manifest.json').read_text())['packages'];ml=[p for p in pkgs if p['name']=='mathlib']
    require(len(ml)==1 and all(ml[0].get(k)==v for k,v in inventory['mathlib'].items()),'Wrong Mathlib pin')
    output.mkdir(parents=True,exist_ok=True)
    print('PASS source inventory:',inventory['source_file_count'],'files,',inventory['unique_module_count'],'unique modules,',inventory['unique_declaration_count'],'declarations',flush=True)
    if args.sources_only:return
    env=os.environ.copy();env.pop('LEAN_PATH',None)
    lakeenv=json.loads(subprocess.check_output(['lake','env','python3','-c','import os,json; print(json.dumps(dict(os.environ)))'],cwd=project,env=env,text=True))
    version=subprocess.check_output(['lean','--version'],cwd=project,env=lakeenv,text=True).strip()
    require(re.search(r'Lean \(version 4\.21\.0(?:[, )])',version),'Wrong actual compiler: '+version)
    report={'status':'PASS','compiler':version,'mathlib':inventory['mathlib'],
        'inventory_sha256':digest(inventory_path),'verifier_sha256':digest(Path(__file__)),
        'source_file_count':inventory['source_file_count'],'unique_module_count':inventory['unique_module_count'],
        'unique_declaration_count':inventory['unique_declaration_count'],
        'additional_helper_audit_count':inventory['additional_helper_audit_count'],
        'reused_earlier_dirtywrapper_declarations':inventory['reused_earlier_dirtywrapper_declarations'],
        'compile_order':inventory['compile_order'],'modules':{}}
    with tempfile.TemporaryDirectory(prefix='machine-transfer-lean-') as directory:
        tmp=Path(directory);lakeenv['LEAN_PATH']=str(tmp)+os.pathsep+lakeenv.get('LEAN_PATH','')
        for name in inventory['compile_order']:
            record=inventory['modules'][name];source=HERE/record['paths'][0]
            local=tmp/(name+'.lean');shutil.copy2(source,local)
            built=subprocess.run(['lean','--root='+str(tmp),'-o',str(tmp/(name+'.olean')),str(local)],cwd=project,env=lakeenv,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
            log=output/(name+'.build.log');log.write_text(built.stdout)
            require(built.returncode==0,'Compile failed: '+name+'; see '+str(log))
            parse_audits(built.stdout,record['existing_axiom_prints'],name+' existing prints')
            # A separate generated shim audits ALL declarations without changing any proof source.
            audit=tmp/('Audit_'+name+'.lean')
            audit.write_text('import '+name+'\n\n'+'\n'.join('#print axioms '+n for n in record['theorems'])+'\n')
            checked=subprocess.run(['lean','--root='+str(tmp),str(audit)],cwd=project,env=lakeenv,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
            auditlog=output/(name+'.axioms.log');auditlog.write_text(checked.stdout)
            require(checked.returncode==0,'Axiom shim failed: '+name+'; see '+str(auditlog))
            axioms=parse_audits(checked.stdout,record['theorems'],name)
            report['modules'][name]={'sha256':record['sha256'],'paths':record['paths'],'declarations':axioms,
                'build_log_sha256':digest(log),'axiom_log_sha256':digest(auditlog),
                'additional_helper_audits':record['additional_audits']}
            print('PASS',name,len(axioms),'audits',flush=True)
    require(collect()==inventory,'Package changed during build')
    (output/'verification.json').write_text(json.dumps(report,indent=2)+'\n')
    print('PASS all',inventory['unique_declaration_count'],'unique declaration audits',flush=True)

if __name__=='__main__':main()
