"""Design T (w3 cube-layer redesign, PR #310 idea, ported to h = 20 as in #346) -- own reimplementation.
Per cube: X pairs along 011 mix in place at their 2-dim M frame; each of the 8 non-011 same-parity pairs ("tetra
edges") gets a 2-dim T frame span(chi_a, chi_b) holding two line registers La, Lb and the partner single S:
S += La; La += Lb; Lb += S  ->  (La, Lb, S) = (x_a+x_b, x_a+x_b, x_a). The two pair-sum copies feed the two planes
containing the edge; S leaves T to its dim-19 delivery frame. The 12 planes are formed as BH += LO at the plane frame;
LO (if not a recycled pair carrier) leaves to FULL. Death helpers are reused as LO / line ids; unused ones are freed
(initial frame FULL, no records). All forward cube-layer gates and their LIFO-matched FULL inverses are removed; the
new forward gates are inverted at FULL at the end. Completion reads (frame-0 cat-4 reads of sigma-0 helpers) are
dropped here and regenerated by comp.py from the exact F2 residual.
usage: dt.py IN_SNAP OUT_DIR"""
import sys,os,json,pickle,collections,math
import numpy as np
from fractions import Fraction
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from snapio import Snap,H
import classify

def kernel_int(B):
    """Integer basis of the annihilator {a : a.b = 0 for b in B} (rows), over Q, cleared denominators."""
    M=[[Fraction(x) for x in b] for b in B];m=len(M);piv=[];r=0
    for c in range(H):
        pr=next((i for i in range(r,m) if M[i][c]!=0),None)
        if pr is None: continue
        M[r],M[pr]=M[pr],M[r];pv=M[r][c];M[r]=[x/pv for x in M[r]]
        for i in range(m):
            if i!=r and M[i][c]!=0:
                f_=M[i][c];M[i]=[a-f_*b for a,b in zip(M[i],M[r])]
        piv.append(c);r+=1
        if r==m: break
    out=[]
    for fc in [c for c in range(H) if c not in piv]:
        x=[Fraction(0)]*H;x[fc]=Fraction(1)
        for i,pc in enumerate(piv): x[pc]=-M[i][fc]
        den=1
        for q in x: den=den*q.denominator//math.gcd(den,q.denominator)
        out.append([int(q*den) for q in x])
    return out

XOR=lambda a,b: tuple(p^q for p,q in zip(a,b))
ALLB=[(i,j,k) for i in (0,1) for j in (0,1) for k in (0,1)]

def run(S,info,part,OUT,strict=True):
    v,n,ZERO,FULL=S.v,S.n,S.ZERO,S.FULL;rec=S.rec;NR=len(rec);dim=S.dim;init=S.init;bits=S.bits;cube_of=S.cube_of
    # frames by item set (existing 1/2-dim item frames)
    byset={}
    for k_ in S.F:
        f=int(k_)
        if 1<=dim[f]<=2:
            I=S.items_in(f)
            if I and len(I)==dim[f]: byset.setdefault(I,f)
    newframes={};nextid=[max(int(k) for k in S.F)+1]
    def frame_for(items):
        I=frozenset(items)
        if I in byset: return byset[I]
        B=[S.chi[i].tolist() for i in sorted(I)];fid=nextid[0];nextid[0]+=1
        newframes[fid]={'B':B,'A':kernel_int(B),'dim':len(B)};dim[fid]=len(B);byset[I]=fid;S._ic[fid]=I
        return fid
    def is_cubeframe(f,cube):
        I=S.items_in(f);return bool(I) and all(cube_of[i]==cube for i in I)
    role={}
    for cube,C in info.items():
        for x in C['X']: role[x]=('X',cube)
        for pl,(r,last,e) in C['BH'].items(): role[r]=('BH',cube)
        for r in C['single']: role[r]=('S',cube)
        for r in C['carrier']: role[r]=('C',cube)
        for r in C['death']: role[r]=('D',cube)
        for r in C['upper']: role[r]=('U',cube)
        for r in C['other']: role[r]=('Y' if v<=r<2*v else 'M',cube)
    moves=S.moves
    adds=np.nonzero(rec[:,0]==1)[0]
    xplane_keep=set()
    for k in adds:
        a,b,f=int(rec[k,1]),int(rec[k,2]),int(rec[k,4])
        if 1<=dim[f]<=3 and role.get(b,('?',))[0]=='BH' and role.get(a,('?',))[0]=='X': xplane_keep.add(a)
    sdeliv={}
    for k in adds:
        a,b=int(rec[k,1]),int(rec[k,2])
        if v<=a<2*v and role.get(b,('?',))[0]=='S' and dim[int(rec[k,4])]==H-1: sdeliv[b]=a-v
    xx={}
    for k in adds:
        a,b=int(rec[k,1]),int(rec[k,2])
        if a<v and b<v and dim[int(rec[k,4])]<H:
            assert frozenset((a,b)) not in xx;xx[frozenset((a,b))]=int(k)
    todo=sorted(info.keys())
    remove=np.zeros(NR,bool);modify={};insert_before=collections.defaultdict(list);newblock=[];fwd=[]
    def MOVE(r,old,new):
        assert dim[new]>=dim[old],(r,old,new);return [0,r,old,new,dim[new]-dim[old],0]
    def ADD(a,b,f,c=1,z=40): return [1,a,b,c,f,z]
    stats=collections.Counter()
    GPOOL=[]
    for cube in todo: GPOOL.extend(sorted(info[cube]['death']))
    used_ids=set()
    def take_id(own):
        while own:
            r=own.pop()
            if r not in used_ids: used_ids.add(r);return r
        while GPOOL:
            r=GPOOL.pop()
            if r not in used_ids: used_ids.add(r);return r
        raise Exception('global pool empty')
    for cube in todo:
        C=info[cube];byb=C['byb']
        # 011 mix pairs (X registers)
        mixpairs=[]
        for b in ALLB:
            if b[1]==0:
                A_,B_=byb[b],byb[XOR(b,(0,1,1))];k=xx[frozenset((A_,B_))]
                car,pas=int(rec[k,1]),int(rec[k,2]);early=dim[int(rec[k,4])]==2
                Mf=int(rec[k,4]) if early else frame_for((A_,B_))
                mixpairs.append(dict(A=car,B=pas,k=k,early=early,M=Mf))
        mixof={frozenset((mp['A'],mp['B'])):mp for mp in mixpairs}
        # planes
        planes=[]
        for pl,(r,last,e) in C['BH'].items():
            pids=[f for f in part[r]['frames'] if dim[f]==3];bs=[bits[i] for i in pl]
            if len({b[0] for b in bs})==1 or len({b[1]^b[2] for b in bs})==1: dirn=(0,1,1)
            elif len({b[1] for b in bs})==1 or len({b[0]^b[2] for b in bs})==1: dirn=(1,0,1)
            else: dirn=(1,1,0)
            rest=set(pl);edges=[]
            while rest:
                a=min(rest);bb=[i for i in rest if XOR(bits[a],bits[i])==dirn][0];edges.append(frozenset((a,bb)));rest-={a,bb}
            planes.append(dict(items=pl,BH=r,pids=pids,first=pids[0],dirn=dirn,edges=edges))
        tedges={};medges={}
        for p in planes:
            for e in p['edges']: (medges if p['dirn']==(0,1,1) else tedges).setdefault(e,[]).append(p)
        assert len(tedges)==8 and all(len(x)==2 for x in tedges.values()),(cube,len(tedges))
        assert len(medges)==4 and all(len(x)==2 for x in medges.values())
        # singles: target t gets x_s, s = t^011; candidate tetra edges {s,t^101},{s,t^110}
        singles=[]
        for r,d in C['single'].items():
            t=sdeliv[r];c=d['exit_content'];assert len(c)==1;si=c[0];tb=bits[t];assert XOR(tb,(0,1,1))==bits[si]
            singles.append((r,t,si,[frozenset((si,byb[XOR(tb,(1,0,1))])),frozenset((si,byb[XOR(tb,(1,1,0))]))]))
        match={}
        def aug(i,used):
            for e in singles[i][3]:
                if e in used: continue
                used.add(e)
                if e not in match or aug(match[e],used): match[e]=i;return True
            return False
        for i in range(len(singles)): assert aug(i,set()),'no matching'
        carriers=[]
        for r in C['carrier']:
            c=part[r]['exit_content']
            if len(c)==1: carriers.append((r,'line',c[0]))
            elif len(c)==2:
                e=frozenset(c)
                if XOR(bits[c[0]],bits[c[1]])==(0,1,1): carriers.append((r,'M',e))
                else: assert e in tedges;carriers.append((r,'T',e))
            elif len(c)==3: carriers.append((r,'drop',None))
            else: raise Exception(('carrier content',len(c)))
        pool=list(C['death'])
        T_regs={}
        for e,pls in tedges.items():
            a,b=sorted(e);T_regs[e]=dict(La=a,Lb=b,pa=pls[0],pb=pls[1])
        pidx={id(p):i for i,p in enumerate(planes)}
        arrivals=collections.defaultdict(list)
        for e,tr in T_regs.items():
            arrivals[pidx[id(tr['pa'])]].append(('L',e,tr['La']));arrivals[pidx[id(tr['pb'])]].append(('L',e,tr['Lb']))
        for e,pls in medges.items():
            for p in pls: arrivals[pidx[id(p)]].append(('M',e,None))
        regid={};recyc={}
        for (r,kind,c) in [x for x in carriers if x[1] in ('M','T')]:
            last=part[r]['frames'][-1]
            for pi,p in enumerate(planes):
                if last in p['pids'] and c in p['edges'] and pi not in recyc: recyc[pi]=(r,kind,c);break
        rc_=set(x[0] for x in recyc.values());carriers=[x for x in carriers if x[0] not in rc_]
        for pi,p in enumerate(planes):
            arr=arrivals[pi];assert len(arr)==2;bh,lo=arr
            if pi in recyc:
                ce=recyc[pi][2]
                if bh[1]==ce: bh,lo=lo,bh
                assert lo[1]==ce
            kb=(bh[0],bh[1],bh[2] if bh[0]=='L' else pi);kl=(lo[0],lo[1],lo[2] if lo[0]=='L' else pi)
            regid[kb]=p['BH']
            if pi in recyc: regid[kl]=recyc[pi][0];p['lo_carrier']=recyc[pi][0]
            else: regid[kl]=take_id(pool)
            p['bh_key']=kb;p['lo_key']=kl
        # old cube-layer MOVEs removed
        for p in planes:
            for k in moves[p['BH']]:
                nf=int(rec[k,3])
                if is_cubeframe(nf,cube):
                    remove[k]=True
                    if nf==p['first']: break
        for r,t,si,_ in singles:
            k=part[r]['exit'][2]
            for kk in moves[r]:
                if kk<k: remove[kk]=True
        for r,kind,c in carriers:
            k=part[r]['exit'][2]
            for kk in moves[r]:
                if kk<k: remove[kk]=True
        Mof={}
        for mp in mixpairs:
            for x in (mp['A'],mp['B']): Mof[x]=mp['M']
        xalias={}
        for x in C['X']:
            k=part[x]['exit'][2];cur={Mof[x]};last=Mof[x]
            for kk in moves[x]:
                if kk<k:
                    o_,nw=int(rec[kk,2]),int(rec[kk,3])
                    if o_ in cur and o_!=nw and dim[nw]==dim[o_]: cur.add(nw);last=nw;stats['xalias']+=1;continue
                    if x in xplane_keep and o_ in cur and dim[nw]==3 and is_cubeframe(nw,cube): cur={nw};last=nw;stats['xplane']+=1;continue
                    remove[kk]=True
            xalias[x]=last
        # new cube-layer block
        blk=[];linefr={i:init[i] for i in C['items']}
        for e,tr in T_regs.items():
            for item in (tr['La'],tr['Lb']):
                r=regid[('L',e,item)];blk.append(MOVE(r,ZERO,linefr[item]));g=ADD(r,item,linefr[item]);blk.append(g);fwd.append(g)
        for r,kind,c in carriers:
            if kind=='line': blk.append(MOVE(r,ZERO,linefr[c]));g=ADD(r,c,linefr[c]);blk.append(g);fwd.append(g)
        for mp in mixpairs:
            for x in (mp['A'],mp['B']): blk.append(MOVE(x,linefr[x],mp['M']))
        for e,pls in medges.items():
            mp=mixof[e]
            for p in pls:
                r=regid[('M',e,pidx[id(p)])];blk.append(MOVE(r,ZERO,mp['M']))
                for x in (mp['A'],mp['B']): g=ADD(r,x,mp['M']);blk.append(g);fwd.append(g)
        for r,kind,c in carriers:
            if kind=='M':
                mp=mixof[c];blk.append(MOVE(r,ZERO,mp['M']))
                for x in (mp['A'],mp['B']): g=ADD(r,x,mp['M']);blk.append(g);fwd.append(g)
        Tframe={}
        for e,tr in T_regs.items():
            Tf=frame_for(e);Tframe[e]=Tf
            La=regid[('L',e,tr['La'])];Lb=regid[('L',e,tr['Lb'])]
            blk.append(MOVE(La,linefr[tr['La']],Tf));blk.append(MOVE(Lb,linefr[tr['Lb']],Tf))
            si=match.get(e)
            if si is None: raise Exception('tetra edge without single')
            sr,t,sitem,_=singles[si];blk.append(MOVE(sr,ZERO,Tf))
            a_=La if sitem==tr['La'] else Lb;b_=Lb if a_==La else La
            for g in (ADD(sr,a_,Tf),ADD(a_,b_,Tf),ADD(b_,sr,Tf)): blk.append(g);fwd.append(g)
            for r,kind,c in carriers:
                if kind=='T' and c==e: blk.append(MOVE(r,ZERO,Tf));g=ADD(r,La,Tf);blk.append(g);fwd.append(g)
        for pi,p in enumerate(planes):
            bk,lk=p['bh_key'],p['lo_key']
            src=lambda key: Tframe[key[1]] if key[0]=='L' else mixof[key[1]]['M']
            rb,rl=regid[bk],regid[lk]
            blk.append(MOVE(rb,src(bk),p['first']));blk.append(MOVE(rl,src(lk),p['first']))
            g=ADD(rb,rl,p['first']);blk.append(g);fwd.append(g)
            if 'lo_carrier' in p:
                k=part[rl]['exit'][2];rr=rec[k].tolist();rr[2]=p['first'];rr[4]=dim[rr[3]]-dim[rr[2]];modify[k]=rr
                for kk in moves[rl]:
                    if kk<k: remove[kk]=True
            else: blk.append(MOVE(rl,p['first'],FULL))
        newblock.extend(blk)
        for r,t,si,_ in singles:
            k=part[r]['exit'][2];e_=[e for e,i in match.items() if singles[i][0]==r][0]
            rr=rec[k].tolist();rr[2]=Tframe[e_];rr[4]=dim[rr[3]]-dim[rr[2]];modify[k]=rr
        for r,kind,c in carriers:
            k=part[r]['exit'][2]
            src=ZERO if kind=='drop' else (linefr[c] if kind=='line' else (mixof[c]['M'] if kind=='M' else Tframe[c]))
            rr=rec[k].tolist();rr[2]=src;rr[4]=dim[rr[3]]-dim[rr[2]];modify[k]=rr
        for mp in mixpairs:
            A_,B_=mp['A'],mp['B']
            if mp['early']:
                for x in (A_,B_):
                    k=part[x]['exit'][2];rr=rec[k].tolist()
                    if dim[rr[3]]==3: raise Exception('X exit into plane')
                    rr[2]=xalias[x];rr[4]=dim[rr[3]]-dim[rr[2]];modify[k]=rr
            else:
                assert xalias[A_]==mp['M'] and xalias[B_]==mp['M']
                kA=part[A_]['exit'][2];kB=part[B_]['exit'][2];E=int(rec[kA,3]);assert int(rec[mp['k'],4])==E
                mixrec=rec[mp['k']].tolist();mixrec[4]=mp['M'];insert_before[kA].append(mixrec)
                rr=rec[kA].tolist();rr[2]=mp['M'];rr[4]=dim[rr[3]]-dim[rr[2]];modify[kA]=rr;remove[mp['k']]=True
                remove[kB]=True;nxt=[kk for kk in moves[B_] if kk>kB];assert nxt
                k2=nxt[0];rr=rec[k2].tolist();assert rr[2]==int(rec[kB,3]);rr[2]=mp['M'];rr[4]=dim[rr[3]]-dim[rr[2]];modify[k2]=rr
                stats['retimed_mix']+=1
        for r in C['death']:
            for kk in moves[r]: remove[kk]=True
        stats['cubes']+=1
    unused=set(GPOOL)-used_ids  # GPOOL was consumed; recompute below
    allD=set()
    for cube in todo: allD|=set(info[cube]['death'])
    unused=allD-used_ids
    tset=set(todo);deaths=allD
    fwd_removed=np.zeros(NR,bool)
    for k in adds:
        a,b,f=int(rec[k,1]),int(rec[k,2]),int(rec[k,4])
        if dim[f]==H: continue
        if a in deaths or b in deaths:
            if v<=a<2*v and dim[f]==0 and int(rec[k,5])==4: continue
            fwd_removed[k]=True;continue
        if 1<=dim[f]<=3:
            ra=role.get(a,('?',None));rb=role.get(b,('?',None))
            if ra[1] in tset or rb[1] in tset:
                if ra[0] in ('U','Y','M'): continue
                if ra[0]=='X' and rb[0]=='X': continue
                if ra[0]=='X' and a in xplane_keep and rb[0]=='BH': continue
                fwd_removed[k]=True
    stack=collections.defaultdict(list);inv_of={}
    for k in adds:
        a,b,f=int(rec[k,1]),int(rec[k,2]),int(rec[k,4])
        if v<=a<2*v: continue
        if dim[f]!=H: stack[(a,b)].append(int(k))
        elif stack[(a,b)]: inv_of[stack[(a,b)].pop()]=int(k)
    nomatch=0
    for k in np.nonzero(fwd_removed)[0]:
        remove[k]=True
        if int(k) in inv_of: remove[inv_of[int(k)]]=True
        else: nomatch+=1
    for k in adds:
        a,b,f=int(rec[k,1]),int(rec[k,2]),int(rec[k,4])
        if (a in deaths or b in deaths) and dim[f]==H: remove[k]=True
    comp=(rec[:,0]==1)&(rec[:,5]==4)&(rec[:,1]>=v)&(rec[:,1]<2*v)
    for k in np.nonzero(comp)[0]:
        if dim[int(rec[k,4])]==0 and dim[init[int(rec[k,2])]]==0: remove[k]=True
    out=list(newblock)
    for k in range(NR):
        if k in insert_before: out.extend(insert_before[k])
        if remove[k] and k not in modify: continue
        out.append(modify.get(k,rec[k].tolist()))
    for (o,a,b,c,f,z) in reversed(fwd): out.append([1,a,b,-c,FULL,41])
    out=np.array(out,dtype=np.int32)
    print('DT: cubes',len(todo),'new frames',len(newframes),'freed',len(unused),'removed fwd ADDs',int(fwd_removed.sum()),'w/o inverse',nomatch,dict(stats),'records',NR,'->',len(out))
    write(S,OUT,out,{r:FULL for r in unused},newframes)
    return dict(unused=sorted(unused),newframes=list(newframes),nomatch=nomatch)

def write(S,OUT,out,initmod,newframes):
    os.makedirs(OUT,exist_ok=True)
    st=dict(S.st);ni=dict(S.st['initial'])
    for r,f in initmod.items(): ni[str(r)]=f
    st['initial']=ni;st['record_count']=len(out)
    json.dump(st,open(OUT+'/249-states.json','w'))
    np.ascontiguousarray(out,dtype='<i4').tofile(OUT+'/249-records.bin')
    fr2={'h':S.fr['h'],'frames':dict(S.F)}
    for fid,ff in newframes.items(): fr2['frames'][str(fid)]=ff
    json.dump(fr2,open(OUT+'/frames.json','w'))

if __name__=='__main__':
    S=Snap(sys.argv[1]);part=classify.interface(S);info,cnt=classify.roles(S,part);print(sorted(cnt.items()))
    run(S,info,part,sys.argv[2])
