#include <bits/stdc++.h>
#include <json.hpp>
#include <boost/multiprecision/cpp_int.hpp>
using namespace std;using J=nlohmann::json;using Q=boost::multiprecision::cpp_rational;using Z=boost::multiprecision::cpp_int;using M=vector<vector<Q>>;
J ld(string p){ifstream f(p);if(!f)throw runtime_error("missing "+p);J j;f>>j;return j;}
Q rat(J j){return j.is_string()?Q(j.get<string>()):Q(j.get<long long>());}M eye(int n){M a(n,vector<Q>(n));for(int i=0;i<n;i++)a[i][i]=1;return a;}M tr(M a){M b(a[0].size(),vector<Q>(a.size()));for(int i=0;i<a.size();i++)for(int j=0;j<a[0].size();j++)b[j][i]=a[i][j];return b;}M mul(M a,M b){M c(a.size(),vector<Q>(b[0].size()));for(int i=0;i<a.size();i++)for(int k=0;k<b.size();k++)if(a[i][k]!=0)for(int j=0;j<b[0].size();j++)c[i][j]+=a[i][k]*b[k][j];return c;}
Z maxnum=1,maxden=1;void admit(Q q){Z n=abs(numerator(q)),d=denominator(q);maxnum=max(maxnum,n);maxden=max(maxden,d);if(n>=(Z(1)<<80)||d>=(Z(1)<<80))throw runtime_error("finite prime guard exceeded");}
M inverse(M a,int &ops,Q &det){int n=a.size();M b=eye(n);det=1;ops=0;for(int k=0;k<n;k++){int t=k;while(t<n&&a[t][k]==0)t++;if(t==n)throw runtime_error("singular");if(t!=k){swap(a[k],a[t]);swap(b[k],b[t]);det=-det;ops++;}Q p=a[k][k];admit(p);det*=p;if(p!=1){ops++;for(int j=0;j<n;j++){a[k][j]/=p;b[k][j]/=p;admit(a[k][j]);admit(b[k][j]);}}for(int i=0;i<n;i++)if(i!=k&&a[i][k]!=0){ops++;Q c=a[i][k];admit(c);for(int j=0;j<n;j++){a[i][j]-=c*a[k][j];b[i][j]-=c*b[k][j];admit(a[i][j]);admit(b[i][j]);}}}if(a!=eye(n))throw runtime_error("inverse failure");return b;}
M nullspace(M a){int n=a[0].size(),row=0;vector<int>piv;for(int col=0;col<n&&row<a.size();col++){int t=row;while(t<a.size()&&a[t][col]==0)t++;if(t==a.size())continue;swap(a[row],a[t]);Q p=a[row][col];admit(p);for(auto &q:a[row]){q/=p;admit(q);}for(int i=0;i<a.size();i++)if(i!=row){Q c=a[i][col];for(int j=0;j<n;j++)a[i][j]-=c*a[row][j];}piv.push_back(col);row++;}if(row!=a.size())throw runtime_error("basis rank failure");M out;for(int free=0;free<n;free++)if(find(piv.begin(),piv.end(),free)==piv.end()){vector<Q>v(n);v[free]=1;for(int i=0;i<row;i++)v[piv[i]]=-a[i][free];out.push_back(v);}return out;}
J mj(M a){J out=J::array();for(auto r:a){J z=J::array();for(Q q:r)z.push_back(q.str());out.push_back(z);}return out;}
struct Pattern{vector<int>w;int count;};
int main(int ac,char**av){if(ac!=8)throw runtime_error("args: baseline_export initial_json new_frames_json output_dir label plan_json final_json");string inp=av[1],out=av[4];auto st=ld(inp+"/249-states.json"),fj=ld(inp+"/frames.json")["frames"],ini=ld(av[2]),nf=ld(av[3]),plan=ld(av[6]),fin=ld(av[7]);int n=st["n"],v=st["v"];map<int,int>dims;for(auto it=fj.begin();it!=fj.end();it++)dims[stoi(it.key())]=it.value()["dim"];for(auto it=nf.begin();it!=nf.end();it++)dims[stoi(it.key())]=it.value()["dim"];
M G=eye(24);for(auto&r:G)for(auto&q:r)q-=Q(1)/9;J charts=J::array();int maxops=0;for(auto it=nf.begin();it!=nf.end();it++){int d=it.value()["dim"];M U;for(auto row:it.value()["B"]){vector<Q>r;for(auto x:row)r.push_back(rat(x));U.push_back(r);}if(U.size()!=d)throw runtime_error("dim");auto UG=mul(U,G);auto V=nullspace(UG);M B=tr(V);for(int i=0;i<24;i++)for(int j=0;j<d;j++)B[i].push_back(U[j][i]);int ops,gops;Q det,gdet;auto inv=inverse(B,ops,det);auto H=mul(UG,tr(U));auto HI=inverse(H,gops,gdet);M P=eye(24),sig=mul(mul(tr(U),HI),UG);for(int i=0;i<24;i++)for(int j=0;j<24;j++)P[i][j]-=sig[i][j];M expected=eye(24);for(int i=24-d;i<24;i++)expected[i][i]=0;if(mul(B,inv)!=eye(24)||mul(inv,B)!=eye(24)||mul(mul(inv,P),B)!=expected)throw runtime_error("projector chart identity");if(mul(mul(tr(B),G),B).size()!=24)throw runtime_error("weighted split");for(auto row:mul(UG,tr(V)))for(Q q:row)if(q!=0)throw runtime_error("orthogonality");maxops=max(maxops,ops);charts.push_back({{"frame",stoi(it.key())},{"dimension",d},{"B",mj(B)},{"inverse",mj(inv)},{"determinant",det.str()},{"gram_determinant",gdet.str()},{"row_factor_count",ops}});}if(maxops>548)throw runtime_error("inherited factor budget exceeded");
map<int,vector<int>>fam;int sumdim=0,changed=0,deleted=0;
for(int i=0;i<st["regs"].size();i++){
 int role=2*v+i,physical=st["regs"][i],f=ini.at(to_string(role)),old=st["initial"].at(to_string(role));int fe=fin.at(to_string(role));
 int r=dims.at(fe)-dims.at(f);if(r<0)throw runtime_error("endpoint below entrance");sumdim+=dims.at(f)-dims.at(old);changed+=f!=old;
 if(r==0){deleted++;continue;}fam[r].push_back(physical);
}
map<int,int>expected;for(auto it=plan["census"].begin();it!=plan["census"].end();it++)expected[stoi(it.key())]=it.value();if(int(plan["replicas"])!=40)throw runtime_error("replicas");
if(fam.size()!=expected.size()||deleted!=1455||sumdim!=35280)throw runtime_error("actual residual census or saved rank");
for(auto[r,k]:expected)if(fam[r].size()!=k)throw runtime_error("actual residual count");
vector<Pattern>pat;auto add=[&](vector<int>w,int count){if(count<0||accumulate(w.begin(),w.end(),0)!=120)throw runtime_error("pattern");if(count)pat.push_back({w,count});};
auto rep=[](int r,int k){return vector<int>(k,r);};auto mix=[&](int r,int k,int four){auto w=rep(r,k);w.insert(w.end(),four,4);return w;};
for(auto&pp:plan["patterns"]){vector<int>w;for(int x:pp["widths"])w.push_back(x);add(w,pp["count"]);}
struct Slot{int bank,off,r,block;};map<int,vector<Slot>>slots;int banks=0;J pj=J::array();for(auto pp:pat){pj.push_back({{"widths",pp.w},{"count",pp.count}});for(int b=0;b<pp.count;b++){int off=0;for(int j=0;j<pp.w.size();j++){int r=pp.w[j];slots[r].push_back({banks+b,off,r,j});off+=r;}}banks+=pp.count;}for(auto[r,rows]:fam)if(slots[r].size()!=40*rows.size())throw runtime_error("slots census mismatch");{long long coords=0;for(auto[r,rows]:fam)coords+=40ll*rows.size()*r;if(coords!=120ll*banks)throw runtime_error("bank stock invariant");}uint64_t hash=1469598103934665603ull;auto hm=[&](uint64_t x){for(int j=0;j<8;j++){hash^=(x>>(8*j))&255;hash*=1099511628211ull;}};long long assignments=0,mass=0,columns=0,controls=0;for(int stage=0;stage<5;stage++){vector<bitset<120>>occ(banks);for(auto[r,rows]:fam)for(int i=0;i<rows.size();i++)for(int rep=0;rep<40;rep++){auto s=slots[r].at(40*i+rep);for(int j=s.off;j<s.off+r;j++){if(occ[s.bank][j])throw runtime_error("collision");occ[s.bank][j]=1;}for(int x:{stage,rep,rows[i],s.bank,s.off,r,s.block+1})hm(x);assignments++;mass+=r;}for(auto&bits:occ)if(bits.count()!=120)throw runtime_error("unfilled");}
for(auto pp:pat){for(bool rev:{false,true})for(int col=0;col<240;col++){array<int,240>s{};s[col]=1;vector<pair<int,int>>bl;int o=0;for(int r:pp.w){bl.push_back({o,r});o+=r;}if(rev)reverse(bl.begin(),bl.end());for(auto[o,r]:bl)for(int j=o;j<o+r;j++)swap(s[j],s[120+j]);for(int j=0;j<240;j++)if(s[j]!=(j==(col+120)%240))throw runtime_error("endpoint");columns++;}for(int mode=0;mode<2;mode++)for(int broken=0;broken<pp.w.size();broken++){long long bad=0;for(int col=0;col<240;col++){array<int,240>s{};s[col]=1;int o=0;for(int b=0;b<pp.w.size();b++){int r=pp.w[b],times=(b==broken?(mode==0?0:2):1);for(int t=0;t<times;t++)for(int j=o;j<o+r;j++)swap(s[j],s[120+j]);o+=r;}for(int j=0;j<240;j++)if(s[j]!=(j==(col+120)%240)){bad++;break;}}if(bad!=2*pp.w[broken])throw runtime_error("control");controls+=bad;}}
J census=J::object();for(auto[r,rows]:fam)census[to_string(r)]=rows.size();long long stock=281600+5*banks,selector=2ll*5*40*((stock-1)+15132ll*120*787);J result={{"status","PASS_GENERIC_EXACT_CHARTS_ACTUAL_BANK_ALLOCATION"},{"label",av[5]},{"new_exact_charts",charts.size()},{"new_entrance_rank",sumdim},{"new_gauged_roles",changed},{"max_new_chart_factors",maxops},{"max_intermediate_numerator",maxnum.str()},{"max_intermediate_denominator",maxden.str()},{"prime_guard", "every elimination pivot and emitted coefficient has numerator and denominator magnitude below2^80"},{"actual_helper_roles",n-2*v-deleted},{"deleted_inert_roles",deleted},{"residual_families",census},{"bank_patterns",pj},{"banks_per_stage",banks},{"literal_stock",stock},{"normalized_stock",Q(stock)/5==Q(stock/5)?J(stock/5):J(Q(Q(stock)/5).str())},{"saved_literal_banks",869415-stock},{"actual_role_replica_stage_assignments",assignments},{"assignment_fnv1a64",to_string(hash)},{"covered_address_rank_mass",mass},{"endpoint_address_columns",columns},{"nonzero_omission_repeat_control_columns",controls},{"max_block_scalar",30},{"normalizer_factor_ceiling",787},{"selector_charge",selector},{"scope","Exact chart and role census, residual conjugacy, complete bank tiling, and finite selector charge. Full physical word, global columns, and pricing checked separately."}};ofstream(out+"/BANK-REVIEW.json")<<result.dump(2)<<"\n";ofstream(out+"/BANK-CHARTS.json")<<charts.dump()<<"\n";cout<<result.dump(2)<<"\n";
}
