// SPDX-License-Identifier: Apache-2.0
#include <bits/stdc++.h>
#include <json.hpp>
using namespace std;using J=nlohmann::json;using E=array<int,6>;using I=long long;
J read(string p){ifstream f(p);if(!f)throw runtime_error("missing "+p);J j;f>>j;return j;}
int main(int ac,char**av){try{if(ac!=3)throw runtime_error("TARGET OUTPREFIX");string d=av[1],o=av[2];J m=read(d+"/meta.json"),ini=read(d+"/initial.json"),fin=read(d+"/final.json"),fr=read(d+"/frames.json");if(fr.contains("frames"))fr=fr["frames"];int n=m["n"],v=m["v"],Z=m["ZERO"],F=m["FULL"];vector<E>w;E e;ifstream f(d+"/records.bin",ios::binary);while(f.read((char*)e.data(),24))w.push_back(e);if(!f.eof())throw runtime_error("partial records");vector<I>T(size_t(n+1)*v),D(size_t(n+1)*v);auto trow=[&](int r){return T.data()+size_t(r)*v;};auto drow=[&](int r){return D.data()+size_t(r)*v;};for(int t=0;t<v;t++)trow(v+t)[t]=1;long long ops=0;auto ax=[&](int dst,int src,int c){auto a=trow(dst),b=trow(src);for(int k=0;k<v;k++){__int128 x=(__int128)a[k]+(__int128)c*b[k];if(x>INT64_MAX||x<INT64_MIN)throw runtime_error("signed adjoint overflow");a[k]=(I)x;}ops++;};
 for(auto it=w.rbegin();it!=w.rend();it++){auto[op,a,b,c,ff,z]=*it;if(op==1){if(v<=a&&a<2*v&&2*v<=b&&b<n&&ff==Z){auto du=drow(b),su=trow(a);for(int k=0;k<v;k++){__int128 q=(__int128)du[k]+(__int128)c*su[k];if(q>INT64_MAX||q<INT64_MIN)throw runtime_error("transported read overflow");du[k]=(I)q;}}ax(b,a,c);}if(op==3)fill(trow(n),trow(n)+v,0);if(op==2){ax(a,n,1);fill(trow(n),trow(n)+v,0);}}
 vector<int>last(n,-1),first(n,INT_MAX),frame(n,-1),reads(n);set<int>copy;map<int,long long>readCategories,coeffs;
 for(int i=0;i<(int)w.size();i++){auto[op,a,b,c,ff,z]=w[i];if(op==1){coeffs[c]++;if(v<=a&&a<2*v&&2*v<=b&&b<n&&ff==Z){last[b]=i;reads[b]++;readCategories[z]++;continue;}for(int r:{a,b})if(r>=2*v&&r<n&&first[r]==INT_MAX){first[r]=i;frame[r]=ff;}}if(op==2||op==3){copy.insert(a);if(a<n&&first[a]==INT_MAX){first[a]=i;frame[a]=c;}}}
 J cold=J::array();int signedzero=0,postequalsnegativeD=0;for(int r=2*v;r<n;r++){bool zero=true;for(int k=0;k<v;k++)zero&=trow(r)[k]==0;signedzero+=zero;if(ini[to_string(r)]!=Z||fin[to_string(r)]!=F||last[r]<0||last[r]>=first[r]||frame[r]<0||copy.count(r))continue;postequalsnegativeD+=zero;cold.push_back({{"reg",r},{"last_read",last[r]},{"first_touch",first[r]},{"first_frame",frame[r]},{"first_dim",fr[to_string(frame[r])]["dim"]},{"read_count",reads[r]},{"signed_total_response_zero",zero}});}
 for(auto p:vector<pair<string,vector<I>*>>{{"-total.bin",&T},{"-reads.bin",&D}}){ofstream out(o+p.first,ios::binary);out.write((char*)p.second->data(),p.second->size()*sizeof(I));}vector<array<uint64_t,15>>f2(n);for(int r=0;r<n;r++)for(int k=0;k<v;k++)if(drow(r)[k]&1)f2[r][k/64]^=1ull<<(k%64);ofstream fb(o+"-f2.bin",ios::binary);fb.write((char*)f2.data(),f2.size()*sizeof(f2[0]));J out={{"meta",m},{"signed_total_zero_helper_columns",signedzero},{"eligible_cold_helpers",cold.size()},{"cold_total_zero",postequalsnegativeD},{"cold",cold},{"read_categories",J::object()},{"integer_coefficients",J::object()},{"adjoint_additions",ops},{"records",w.size()},{"response_layout","native little-endian signed int64 [n+1][v]; total=complete signed target adjoint; reads=earlyZEROhelper->target READ contributions transported through exact subsequent target shears"},{"F2_layout","uint64[n][15], eachrow read-response modulo2"},{"claim","Extraction only; no improvement claimed"}};for(auto kv:readCategories)out["read_categories"][to_string(kv.first)]=kv.second;for(auto kv:coeffs)out["integer_coefficients"][to_string(kv.first)]=kv.second;ofstream(o+".json")<<out.dump(2)<<"\n";cout<<"cold "<<cold.size()<<" signedzero "<<signedzero<<" coldzero "<<postequalsnegativeD<<" records "<<w.size()<<"\n";
 }catch(exception&e){cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
