// SPDX-License-Identifier: Apache-2.0
#include <bits/stdc++.h>
#include <json.hpp>
using namespace std;using J=nlohmann::json;using I=long long;using V=vector<I>;J rd(string p){ifstream f(p);J j;f>>j;return j;}vector<I>bin(string p){ifstream f(p,ios::binary|ios::ate);size_t n=f.tellg();f.seekg(0);vector<I>b(n/8);f.read((char*)b.data(),n);return b;}struct C{int r,l,t,fr,dim;};
int main(int ac,char**av){try{if(ac!=5)throw runtime_error("TARGET RESPONSEPREFIX SECONDS OUT");string dir=av[1],pre=av[2];auto j=rd(pre+".json"),fr=rd(dir+"/frames.json");int n=j["meta"]["n"],v=j["meta"]["v"];auto T=bin(pre+"-total.bin"),D=bin(pre+"-reads.bin");vector<C>cs;for(auto&x:j["cold"])cs.push_back({x["reg"],x["last_read"],x["first_touch"],x["first_frame"],x["first_dim"]});vector<uint64_t>wt(v),qhash(n),dhash(n);mt19937_64 rng(917421);for(auto&w:wt)w=rng();unordered_map<uint64_t,vector<int>>byD;for(int k=0;k<(int)cs.size();k++){int r=cs[k].r;for(int t=0;t<v;t++){dhash[r]+=uint64_t(D[size_t(r)*v+t])*wt[t];qhash[r]+=uint64_t(T[size_t(r)*v+t]-D[size_t(r)*v+t])*wt[t];}byD[dhash[r]].push_back(k);}auto price=[](int r){return r? r*expm1(.000801725878336075*log(100.0/r))+3.2e-11*pow(100.0,.000801725878336075):0.;};
 struct G{int a,b,sa,sb;V cap;set<int>p;double cost=0;};map<string,G>groups;long long probes=0,exact=0,timing=0,capok=0;auto deadline=chrono::steady_clock::now()+chrono::seconds(stoi(av[3]));
 auto contains=[&](const V&line,int fid){for(auto&a:fr[to_string(fid)]["A"]){__int128 dot=0;for(int z=0;z<20;z++)dot+=(__int128)line[z]*a[z].get<I>();if(dot)return false;}return true;};
  for(int a=0;a<(int)cs.size();a++)for(int sa:{-1,1}){probes++;auto it=byD.find(sa*qhash[cs[a].r]);if(it==byD.end())continue;for(int p:it->second){if(p==a)continue;auto P=cs[p],A=cs[a];int cut=max(P.l,A.l);if(cut>=min(P.t,A.t))continue;timing++;bool ok=true;for(int z=0;z<v;z++)if((__int128)sa*(T[size_t(A.r)*v+z]-D[size_t(A.r)*v+z])!=D[size_t(P.r)*v+z]){ok=false;break;}if(!ok)continue;exact++;for(auto&r:fr[to_string(P.fr)]["B"]){V cap=r.get<V>();I gcdv=0;for(I z:cap)gcdv=gcd(gcdv,abs(z));if(gcdv)for(auto&z:cap)z/=gcdv;for(I z:cap)if(z){if(z<0)for(auto&u:cap)u=-u;break;}if(!contains(cap,A.fr))continue;__int128 sum=0,sq=0;for(I z:cap){sum+=z;sq+=9*(__int128)z*z;}if(sq==sum*sum)continue;capok++;string key=J::array({A.r,-1,sa,0,cap}).dump();auto&gr=groups[key];gr.a=A.r;gr.b=-1;gr.sa=sa;gr.sb=0;gr.cap=cap;gr.p.insert(P.r);}}}unordered_map<int,C>info;for(auto c:cs)info[c.r]=c;vector<G>good;for(auto&kv:groups){auto g=kv.second;g.cost=price(1)+price(info[g.a].dim-1)-price(info[g.a].dim)+(g.b>=0?price(1)+price(info[g.b].dim-1)-price(info[g.b].dim):0);for(int p:g.p)g.cost+=price(info[p].dim-1)-price(info[p].dim);if(g.cost< -1e-12)good.push_back(g);}sort(good.begin(),good.end(),[](auto&a,auto&b){if(a.cost!=b.cost)return a.cost<b.cost;return tie(a.a,a.b,a.sa,a.sb,a.cap)<tie(b.a,b.b,b.sa,b.sb,b.cap);});J gs=J::array();for(auto&g:good){J piv=J::array();for(int p:g.p)piv.push_back(p);gs.push_back({{"donors",{g.a,g.b}},{"coefficients",{g.sa,g.sb}},{"basis",J::array({g.cap})},{"pivots",piv},{"paid_moment_delta_screen",g.cost}});}J out={{"source",j["meta"]["raw_sha256"]},{"cold_helpers",cs.size()},{"fingerprint_probes",probes},{"timing_admitted_checks",timing},{"exact_signed_relation_checks",exact},{"common_cap_relations",capok},{"groups",groups.size()},{"positive_groups",gs},{"best_screen_delta",good.empty()?0:good[0].cost},{"claim","Exact signed sparse relations and cap containment; floating group invoice only, full emitted-word and bank admission mandatory"}};ofstream(av[4])<<out.dump(2)<<"\n";cout<<"DONE positive "<<good.size()<<" best "<<(good.empty()?0:good[0].cost)<<"\n";
}catch(exception&e){cerr<<e.what()<<"\n";return 1;}}
