#include <json.hpp>
#include <array>
#include <vector>
#include <map>
#include <set>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <numeric>
#include <chrono>
#include <cmath>
using namespace std;using J=nlohmann::json;using R=array<uint64_t,15>;using V=vector<long long>;using Mat=vector<V>;struct E{int op,a,b,c,f,z;};J rd(string p){ifstream f(p);if(!f)throw runtime_error("missing "+p);J j;f>>j;return j;}int lead(const R&r){for(int k=14;k>=0;k--)if(r[k])return k*64+63-__builtin_clzll(r[k]);return-1;}vector<int>sx(vector<int>a,vector<int>b){vector<int>z;set_symmetric_difference(a.begin(),a.end(),b.begin(),b.end(),back_inserter(z));return z;}struct B{R r;vector<int>ids;};
struct Dinic{struct Edge{int v,rev;long double c;};vector<vector<Edge>>g;vector<int>l,it;Dinic(int n):g(n),l(n),it(n){}void add(int a,int b,long double c){g[a].push_back({b,(int)g[b].size(),c});g[b].push_back({a,(int)g[a].size()-1,0});}long double dfs(int a,int t,long double f){if(a==t)return f;for(int&i=it[a];i<g[a].size();i++){auto&e=g[a][i];if(e.c>1e-17&&l[e.v]==l[a]+1){auto z=dfs(e.v,t,min(f,e.c));if(z>1e-17){e.c-=z;g[e.v][e.rev].c+=z;return z;}}}return 0;}void flow(int s,int t){while(1){fill(l.begin(),l.end(),-1);vector<int>q{s};l[s]=0;for(size_t i=0;i<q.size();i++)for(auto&e:g[q[i]])if(e.c>1e-17&&l[e.v]<0){l[e.v]=l[q[i]]+1;q.push_back(e.v);}if(l[t]<0)return;fill(it.begin(),it.end(),0);while(dfs(s,t,1e9)>1e-17){}}}};
struct Relation{int p;vector<int>d;vector<long long>c;bool signedok=false;};
int main(int ac,char**av){try{if(ac!=5)throw runtime_error("INPUT RESPONSE-DIR SECONDS OUT");string dir=av[1],respdir=av[2];auto meta=rd(dir+"/meta.json"),fr=rd(dir+"/frames.json"),ini=rd(dir+"/initial.json"),fin=rd(dir+"/final.json"),rr=rd(respdir+"/response351-v2.json");int n=meta["n"],v=meta["v"],zero=meta["ZERO"],full=meta["FULL"];vector<long long>T((n+1)*v),D(T.size());ifstream ft(respdir+"/response351-v2-total.bin",ios::binary),fd(respdir+"/response351-v2-reads.bin",ios::binary);if(!ft.read((char*)T.data(),T.size()*8)||!fd.read((char*)D.data(),D.size()*8))throw runtime_error("short signed matrix");vector<R>M(n),P(n);for(int s=0;s<n;s++)for(int j=0;j<v;j++){if((T[s*v+j]-D[s*v+j])&1)M[s][j/64]|=1ull<<(j%64);if(D[s*v+j]&1)P[s][j/64]|=1ull<<(j%64);}vector<E>w;E e;ifstream fw(dir+"/records.bin",ios::binary);while(fw.read((char*)&e,sizeof e))w.push_back(e);vector<int>first(n,-1),frame(n,-1),last(n,-1),dim(n,-1);vector<bool>copy(n),other(n);for(int i=0;i<w.size();i++){e=w[i];if(e.op==0&&e.a<n&&first[e.a]<0){first[e.a]=i;frame[e.a]=e.c;dim[e.a]=fr[to_string(e.c)]["dim"];}if(e.op==1){bool read=e.a>=v&&e.a<2*v&&e.b>=2*v&&e.b<n&&e.f==zero;if(read){last[e.b]=i;continue;}for(int r:{e.a,e.b})if(r>=2*v&&r<n&&first[r]<0)other[r]=true;}if((e.op==2||e.op==3)&&e.a<n)copy[e.a]=true;}
vector<int>eligible;map<int,Mat>A;for(auto&s:rr["cold"]){int r=s["reg"];if(ini[to_string(r)]!=zero||fin[to_string(r)]!=full||copy[r]||other[r]||first[r]<0||last[r]<0||last[r]>=first[r]||dim[r]<=0)continue;eligible.push_back(r);if(!A.count(frame[r]))A[frame[r]]=fr[to_string(frame[r])]["A"].get<Mat>();}
vector<V>caps;set<V>seen;auto addcap=[&](V q){long long g=0;for(auto x:q)g=gcd(g,x);if(!g)return;for(auto&x:q)x/=g;for(auto x:q)if(x){if(x<0)for(auto&y:q)y=-y;break;}if(seen.insert(q).second)caps.push_back(q);};for(auto it=fr.begin();it!=fr.end();it++)if(it.value()["dim"]==1)addcap(it.value()["B"][0].get<V>());for(int i=0;i<20;i++)for(int j=i+1;j<20;j++){V q(20);q[i]=1;q[j]=-1;addcap(q);}auto deadline=chrono::steady_clock::now()+chrono::seconds(stoi(av[3]));long long cuts=0,bases=0,relations=0,signchecks=0,validsigned=0;long double exponent=.000801725878336075L,weight[21]={},best=0,bestSigned=0;for(int r=1;r<=20;r++)weight[r]=r*expm1l(exponent*logl(100.0L/r))+(32.0L*100*100/1e16L)*powl(100.0L,exponent);J nomination=J::object(),signedNomination=J::object(),stats=J::array(),signedCandidates=J::array();int processed=0;
auto eval=[&](const vector<Relation>&rels){set<int>ds;for(auto&r:rels)for(int d:r.d)ds.insert(d);vector<int>don(ds.begin(),ds.end());map<int,int>di;int np=rels.size(),nd=don.size(),s=np+nd,t=s+1;Dinic net(t+1);for(int j=0;j<nd;j++){di[don[j]]=np+j;int f=dim[don[j]];net.add(np+j,t,weight[1]+weight[f-1]-weight[f]);}for(int j=0;j<np;j++){int f=dim[rels[j].p];net.add(s,j,weight[f]-weight[f-1]);for(int d:rels[j].d)net.add(j,di[d],1e6);}net.flow(s,t);vector<bool>reach(t+1);vector<int>qq{s};reach[s]=true;for(size_t j=0;j<qq.size();j++)for(auto&e:net.g[qq[j]])if(e.c>1e-17&&!reach[e.v]){reach[e.v]=true;qq.push_back(e.v);}J piv=J::array(),donj=J::array();map<int,int>hist;for(int j=0;j<np;j++)if(reach[j]){auto&r=rels[j];J z={{"pivot",r.p},{"donors",r.d}};if(r.signedok)z["coefficients"]=r.c;piv.push_back(z);hist[dim[r.p]]--;if(dim[r.p]>1)hist[dim[r.p]-1]++;}for(int j=0;j<nd;j++)if(reach[np+j]){int d=don[j];donj.push_back(d);hist[1]++;hist[dim[d]]--;if(dim[d]>1)hist[dim[d]-1]++;}long double delta=0;int mass=0;J hh=J::object();for(auto[k,c]:hist)if(c){hh[to_string(k)]=c;delta+=c*weight[k];mass+=k*c;}return pair<long double,J>{delta,J{{"pivots",piv},{"distinct_donors",donj},{"histogram_delta",hh},{"rank_mass_delta",mass},{"paid_moment_delta_discovery",(double)delta}}};};
for(int ci=0;ci<caps.size();ci++){if(chrono::steady_clock::now()>deadline)break;auto cap=caps[ci];__int128 norm=0,sum=0;for(auto x:cap){norm+=9*(__int128)x*x;sum+=x;}if(norm-sum*sum==0)continue;map<int,pair<vector<int>,vector<int>>>ev;int members=0,maxactive=0;long long capcuts=0;long double capbest=0;J capnom=J::object();for(int r:eligible){bool ok=true;for(auto&a:A[frame[r]]){__int128 z=0;for(int j=0;j<20;j++)z+=(__int128)a[j]*cap[j];if(z){ok=false;break;}}if(ok){ev[last[r]+1].first.push_back(r);ev[first[r]].second.push_back(r);members++;}}set<int>active;for(auto&[cut,vs]:ev){for(int r:vs.second)active.erase(r);for(int r:vs.first)active.insert(r);if(active.size()<2)continue;if(chrono::steady_clock::now()>deadline)break;cuts++;capcuts++;maxactive=max(maxactive,(int)active.size());vector<int>order(active.begin(),active.end());stable_sort(order.begin(),order.end(),[&](int a,int b){return dim[a]!=dim[b]?dim[a]<dim[b]:a<b;});map<int,B>gb;set<int>donors;for(int r:order){R a=M[r];vector<int>ids{r};while(lead(a)>=0){int k=lead(a);if(!gb.count(k)){gb[k]={a,ids};donors.insert(r);break;}for(int j=0;j<15;j++)a[j]^=gb[k].r[j];ids=sx(ids,gb[k].ids);}}bases++;vector<Relation>rels;for(int r:order)if(!donors.count(r)){R a=P[r];vector<int>ids;while(lead(a)>=0){int k=lead(a);if(!gb.count(k))break;for(int j=0;j<15;j++)a[j]^=gb[k].r[j];ids=sx(ids,gb[k].ids);}if(lead(a)<0){rels.push_back({r,ids,{}});relations++;}}if(rels.empty())continue;auto[delta,nom]=eval(rels);if(delta<best-1e-15L){best=delta;nom["basis"]=cap;nom["cut_record_index"]=cut;nom["cohort_members"]=active.size();nom["status"]="F2_NOMINATION_REQUIRES_SIGNED_AND_WORD_ADMISSION";nomination=nom;cout<<"PARITY BEST cap "<<ci<<" cut "<<cut<<" pivots "<<nom["pivots"].size()<<" donors "<<nom["distinct_donors"].size()<<" delta "<<(double)delta<<"\n"<<flush;}
if(delta<-1e-15L){vector<Relation>sr;for(auto r:rels){int k=r.d.size();if(k>12)continue;vector<int>nz;for(int j=0;j<v&&nz.size()<12;j++)if(D[r.p*v+j])nz.push_back(j);for(unsigned mask=0;mask<(1u<<k);mask++){bool ok=true;for(int j:nz){__int128 z=0;for(int u=0;u<k;u++)z+=(mask>>u&1?-1:1)*(__int128)(T[r.d[u]*v+j]-D[r.d[u]*v+j]);if(z!=D[r.p*v+j]){ok=false;break;}}if(!ok)continue;signchecks++;for(int j=0;j<v;j++){__int128 z=0;for(int u=0;u<k;u++)z+=(mask>>u&1?-1:1)*(__int128)(T[r.d[u]*v+j]-D[r.d[u]*v+j]);if(z!=D[r.p*v+j]){ok=false;break;}}if(ok){r.signedok=true;for(int u=0;u<k;u++)r.c.push_back(mask>>u&1?-1:1);sr.push_back(r);validsigned++;break;}}}if(!sr.empty()){auto[sd,sn]=eval(sr);if(sd<capbest-1e-15L){capbest=sd;capnom=sn;capnom["basis"]=cap;capnom["cut_record_index"]=cut;capnom["cohort_members"]=active.size();capnom["status"]="EXACT_SIGNED_SUFFIX_ROWS_LITERAL_WORD_ADMISSION_PENDING";}if(sd<bestSigned-1e-15L){bestSigned=sd;sn["basis"]=cap;sn["cut_record_index"]=cut;sn["cohort_members"]=active.size();sn["status"]="EXACT_SIGNED_SUFFIX_RELATIONS_PAID_DISCOVERY_WORD_ADMISSION_PENDING";signedNomination=sn;cout<<"SIGNED BEST cap "<<ci<<" cut "<<cut<<" delta "<<(double)sd<<"\n"<<flush;}}}
}if(capbest<-1e-15L)signedCandidates.push_back(capnom);stats.push_back({{"cap_index",ci},{"basis",cap},{"members",members},{"max_active",maxactive},{"cuts",capcuts}});processed++;if(ci%100==0)cout<<"caps "<<processed<<"/"<<caps.size()<<" cuts "<<cuts<<" delta "<<(double)best<<"\n"<<flush;}
J out={{"status","BOUNDED_ACTUAL351_COMMON_CAP_SUFFIX_MATROID"},{"input_raw_sha256",meta["raw_sha256"]},{"eligible_cold_helpers",eligible.size()},{"cap_library_size",caps.size()},{"caps_processed",processed},{"cut_cohorts",cuts},{"donor_bases",bases},{"representable_parity_relations",relations},{"exact_signed_full_row_checks",signchecks},{"exact_signed_relations",validsigned},{"best_F2_moment_delta",(double)best},{"best_signed_moment_delta",(double)bestSigned},{"F2_candidate",nomination},{"signed_candidate",signedNomination},{"best_signed_per_cap",signedCandidates},{"cap_stats",stats},{"kappa_claim",false},{"scope","Actual virgin zero-entrance physical intervals, first MOVE, cold noCOPY no other prefix touches; rank-one rational cap containment; arbitrary donor-basis rank and weighted closure. F2 nominations alone are not sufficient. Signed rows checked all960 columns where indicated; literal changed-word geometry/dirt/bank/finance still required."}};ofstream(av[4])<<out.dump(2)<<"\n";cout<<"DONE eligible "<<eligible.size()<<" caps "<<processed<<" cuts "<<cuts<<" F2 "<<(double)best<<" signed "<<(double)bestSigned<<"\n";
}catch(exception&e){cerr<<e.what()<<"\n";return 1;}}
