#include <json.hpp>
#include <vector>
#include <map>
#include <set>
#include <array>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
using namespace std;using J=nlohmann::json;using I=long long;using V=vector<I>;using Mat=vector<V>;constexpr int P=1000003;struct E{int op,a,b,c,f,z;};J rd(string p){ifstream f(p);if(!f)throw runtime_error("missing input");J j;f>>j;return j;}int mod(I a){a%=P;if(a<0)a+=P;return a;}int pw(int x,int e){int r=1;while(e){if(e&1)r=(I)r*x%P;x=(I)x*x%P;e>>=1;}return r;}struct Basis{vector<int>row,coeff;};
struct Dinic{struct Edge{int v,rev;long double c;};vector<vector<Edge>>g;vector<int>l,it;Dinic(int n):g(n),l(n),it(n){}void add(int a,int b,long double c){g[a].push_back({b,(int)g[b].size(),c});g[b].push_back({a,(int)g[a].size()-1,0});}long double dfs(int a,int t,long double f){if(a==t)return f;for(int&i=it[a];i<g[a].size();i++){auto&e=g[a][i];if(e.c>1e-17&&l[e.v]==l[a]+1){auto z=dfs(e.v,t,min(f,e.c));if(z>1e-17){e.c-=z;g[e.v][e.rev].c+=z;return z;}}}return 0;}void flow(int s,int t){while(1){fill(l.begin(),l.end(),-1);vector<int>q{s};l[s]=0;for(size_t i=0;i<q.size();i++)for(auto&e:g[q[i]])if(e.c>1e-17&&l[e.v]<0){l[e.v]=l[q[i]]+1;q.push_back(e.v);}if(l[t]<0)return;fill(it.begin(),it.end(),0);while(dfs(s,t,1e9)>1e-17){}}}};
int main(int ac,char**av){try{if(ac!=7)throw runtime_error("INPUT RESPONSE SCAN MODE SECONDS OUT");string dir=av[1],rdx=av[2],mode=av[4];auto meta=rd(dir+"/meta.json"),fr=rd(dir+"/frames.json"),ini=rd(dir+"/initial.json"),fin=rd(dir+"/final.json"),rr=rd(rdx+"/response351-v2.json"),scan=rd(av[3]);int n=meta["n"],v=meta["v"],Z=meta["ZERO"],FULL=meta["FULL"];vector<I>T((n+1)*v),D(T.size());ifstream(rdx+"/response351-v2-total.bin",ios::binary).read((char*)T.data(),T.size()*8);ifstream(rdx+"/response351-v2-reads.bin",ios::binary).read((char*)D.data(),D.size()*8);vector<E>w;E e;ifstream f(dir+"/records.bin",ios::binary);while(f.read((char*)&e,sizeof e))w.push_back(e);vector<int>first(n,-1),ff(n,-1),last(n,-1),dim(n),reads(n);vector<bool>copy(n),other(n),tz(n,true);for(int r=0;r<n;r++)for(int j=0;j<v;j++)if(T[r*v+j])tz[r]=false;for(int k=0;k<w.size();k++){e=w[k];if(e.op==0&&e.a<n&&first[e.a]<0){first[e.a]=k;ff[e.a]=e.c;dim[e.a]=fr[to_string(e.c)]["dim"];}if(e.op==1){if(v<=e.a&&e.a<2*v&&2*v<=e.b&&e.b<n&&e.f==Z){last[e.b]=k;reads[e.b]++;}else for(int r:{e.a,e.b})if(r>=2*v&&r<n&&first[r]<0)other[r]=true;}if((e.op==2||e.op==3)&&e.a<n)copy[e.a]=true;}
vector<int>eligible;map<int,vector<int>>byframe;map<int,Mat>A;for(auto z:rr["cold"]){int r=z["reg"];if(ini[to_string(r)]!=Z||fin[to_string(r)]!=FULL||copy[r]||other[r]||first[r]<0||last[r]>=first[r])continue;eligible.push_back(r);byframe[ff[r]].push_back(r);if(!A.count(ff[r]))A[ff[r]]=fr[to_string(ff[r])]["A"].get<Mat>();}vector<pair<int,Mat>>caps;map<Mat,int>seen;if(mode=="same"){for(auto&[fid,rs]:byframe)if(rs.size()>1)caps.push_back({fid,fr[to_string(fid)]["B"].get<Mat>()});}
else if(mode=="rank2"){for(auto it=fr.begin();it!=fr.end();it++)if(it.value()["dim"]==2){Mat B=it.value()["B"];if(!seen.count(B)){seen[B]=stoi(it.key());caps.push_back({stoi(it.key()),B});}}}
else if(mode=="rank1"){for(auto&z:scan["best_signed_per_cap"]){Mat B=z["basis"][0].is_array()?z["basis"].get<Mat>():Mat{z["basis"].get<V>()};if(!seen.count(B)){seen[B]=-1;caps.push_back({-1,B});}}}else throw runtime_error("mode");auto deadline=chrono::steady_clock::now()+chrono::seconds(stoi(av[5]));long long cuts=0,fullchecks=0,valid=0,basis_trials=0;long double a=.000803782713332805L,W[21]={},best=0;for(int r=1;r<=20;r++)W[r]=r*expm1l(a*logl(100.0L/r))+(32.0L*100*100/1e16L)*powl(100.0L,a);J positives=J::array(),bestnom=J::object();int processed=0;
for(auto&[fid,cap]:caps){if(chrono::steady_clock::now()>deadline)break;int rank=cap.size();vector<int>members;if(mode=="same")members=byframe[fid];else for(int r:eligible){bool yes=dim[r]>=rank;for(auto&q:cap)for(auto&b:A[ff[r]]){__int128 z=0;for(int k=0;k<20;k++)z+=(__int128)q[k]*b[k];if(z){yes=false;break;}}if(yes)members.push_back(r);}if(members.size()<2){processed++;continue;}map<int,pair<vector<int>,vector<int>>>events;for(int r:members){events[last[r]+1].first.push_back(r);events[first[r]].second.push_back(r);}set<int>active;set<int>chosenCuts;for(auto&z:scan["best_signed_per_cap"]){Mat zcap=z["basis"][0].is_array()?z["basis"].get<Mat>():Mat{z["basis"].get<V>()};if(zcap==cap){int cc=z["cut_record_index"];chosenCuts.insert(cc);}}long double capbest=0;J capnom;for(auto&[cut,vs]:events){for(int r:vs.second)active.erase(r);for(int r:vs.first)active.insert(r);if(active.size()<2||!chosenCuts.count(cut))continue;if(chrono::steady_clock::now()>deadline)break;cuts++;for(int seed=0;seed<32;seed++){if(chrono::steady_clock::now()>deadline)break;basis_trials++;vector<int>order(active.begin(),active.end());auto hash=[&](int r){uint64_t x=uint64_t(r)+uint64_t(seed)*0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);};stable_sort(order.begin(),order.end(),[&](int x,int y){if(seed<28&&dim[x]!=dim[y])return dim[x]<dim[y];if(seed==0)return x<y;if(seed==1)return x>y;if(seed==2&&reads[x]!=reads[y])return reads[x]<reads[y];if(seed==3&&reads[x]!=reads[y])return reads[x]>reads[y];return hash(x)<hash(y);});int m=order.size();map<int,Basis>bs;set<int>donors;for(int s=0;s<m;s++){int r=order[s];vector<int>x(v),co(m);co[s]=1;for(int j=0;j<v;j++)x[j]=mod(T[r*v+j]-D[r*v+j]);for(int j=0;j<v;j++)if(x[j]){auto it=bs.find(j);if(it==bs.end()){int iv=pw(x[j],P-2);for(int k=j;k<v;k++)x[k]=(I)x[k]*iv%P;for(int k=0;k<m;k++)co[k]=(I)co[k]*iv%P;bs[j]={move(x),move(co)};donors.insert(r);break;}int q=x[j];auto&b=it->second;for(int k=j;k<v;k++)x[k]=mod(x[k]-(I)q*b.row[k]);for(int k=0;k<m;k++)co[k]=mod(co[k]-(I)q*b.coeff[k]);}}
J rels=J::array();set<int>used;long double profit=0;for(int r:order)if(!donors.count(r)){vector<int>x(v),co(m);for(int j=0;j<v;j++)x[j]=mod(D[r*v+j]);bool ok=true;for(int j=0;j<v;j++)if(x[j]){auto it=bs.find(j);if(it==bs.end()){ok=false;break;}int q=x[j];auto&b=it->second;for(int k=j;k<v;k++)x[k]=mod(x[k]-(I)q*b.row[k]);for(int k=0;k<m;k++)co[k]=mod(co[k]+(I)q*b.coeff[k]);}if(!ok)continue;vector<int>ds;vector<I>cs;for(int j=0;j<m;j++)if(co[j]){int c=co[j]>P/2?co[j]-P:co[j];if(abs(c)>8||!donors.count(order[j])){ok=false;break;}ds.push_back(order[j]);cs.push_back(c);}if(!ok)continue;fullchecks++;for(int j=0;j<v;j++){__int128 z=0;for(int k=0;k<ds.size();k++)z+=(__int128)cs[k]*(T[ds[k]*v+j]-D[ds[k]*v+j]);if(z!=D[r*v+j]){ok=false;break;}}if(!ok)continue;valid++;rels.push_back({{"pivot",r},{"donors",ds},{"coefficients",cs}});for(int d:ds)used.insert(d);profit+=W[dim[r]]-W[dim[r]-rank];}
// Exact identical-first-frame donors cost zero. For other caps, use a conservatively paid full relation set.
vector<int>du(used.begin(),used.end());map<int,int>dix;int np=rels.size(),nd=du.size(),src=np+nd,snk=src+1;Dinic net(snk+1);for(int j=0;j<nd;j++){dix[du[j]]=np+j;net.add(np+j,snk,W[rank]+W[dim[du[j]]-rank]-W[dim[du[j]]]);}for(int j=0;j<np;j++){int pp=rels[j]["pivot"];net.add(src,j,W[dim[pp]]-W[dim[pp]-rank]);for(auto dd:rels[j]["donors"])net.add(j,dix[dd],1e6);}net.flow(src,snk);vector<bool>reach(snk+1);vector<int>qq{src};reach[src]=true;for(size_t j=0;j<qq.size();j++)for(auto&ee:net.g[qq[j]])if(ee.c>1e-17&&!reach[ee.v]){reach[ee.v]=true;qq.push_back(ee.v);}J selected=J::array();set<int>selectedDonors;profit=0;for(int j=0;j<np;j++)if(reach[j]){selected.push_back(rels[j]);int pp=rels[j]["pivot"];profit+=W[dim[pp]]-W[dim[pp]-rank];}for(int j=0;j<nd;j++)if(reach[np+j])selectedDonors.insert(du[j]);rels=selected;used=selectedDonors;long double delta=-profit;for(int d:used)delta+=W[rank]+W[dim[d]-rank]-W[dim[d]];if(delta<capbest-1e-15L){capbest=delta;map<int,int>hist;int units=0,nonzero=0;for(auto z:rels){int r=z["pivot"];hist[dim[r]]--;if(dim[r]>rank)hist[dim[r]-rank]++;for(auto c:z["coefficients"])units+=abs(c.get<int>());}for(int d:used){hist[rank]++;hist[dim[d]]--;if(dim[d]>rank)hist[dim[d]-rank]++;nonzero+=!tz[d];}J hh=J::object();int mass=0;for(auto[k,c]:hist)if(c){hh[to_string(k)]=c;mass+=k*c;}capnom={{"basis_seed",seed},{"basis",cap},{"cap_rank",rank},{"registered_frame",fid},{"cut_record_index",cut},{"pivots",rels},{"distinct_donors",used},{"nonzero_total_response_donors",nonzero},{"histogram_delta",hh},{"rank_mass_delta",mass},{"finite_setup_unit_ADDs",units},{"paid_moment_delta_discovery",(double)delta}};if(delta<best){best=delta;bestnom=capnom;cout<<"BEST mode "<<mode<<" frame "<<fid<<" rank "<<rank<<" cut "<<cut<<" pivots "<<rels.size()<<" donor "<<used.size()<<" nonzeroT "<<nonzero<<" delta "<<(double)delta<<"\n"<<flush;}}
}}if(capbest<0)positives.push_back(capnom);processed++;if(processed%100==0)cout<<"caps "<<processed<<" cuts "<<cuts<<" delta "<<(double)best<<"\n"<<flush;}
J out={{"status","BOUNDED_DETERMINISTIC_DONOR_BASIS_EXCHANGES"},{"mode",mode},{"source_raw_sha256",meta["raw_sha256"]},{"eligible",eligible.size()},{"cap_library",caps.size()},{"caps_processed",processed},{"cut_cohorts",cuts},{"donor_basis_exchange_trials",basis_trials},{"exact_signed_full_checks",fullchecks},{"exact_signed_relations",valid},{"best_moment_delta",(double)best},{"best_candidate",bestnom},{"best_signed_per_cap",positives},{"kappa_claim",false},{"scope","Native prime-field Gaussian nomination, bounded integer coefficients <=8, exact960integer response verification. Actual cold intervals and registered cap containment. Weighted partial closure charges every distinct selected donor; literal word admission remains required."}};ofstream(av[6])<<out.dump(2)<<"\n";cout<<"DONE "<<mode<<" caps "<<processed<<" cuts "<<cuts<<" exact "<<valid<<" best "<<(double)best<<"\n";
}catch(exception&e){cerr<<e.what()<<"\n";return 1;}}