#include <bits/stdc++.h>
#include <json.hpp>
using namespace std;using J=nlohmann::json;struct E{int k,a,b,c,f,z;bool operator==(const E&o)const{return tie(k,a,b,c,f,z)==tie(o.k,o.a,o.b,o.c,o.f,o.z);}};vector<E>read(string p){ifstream f(p,ios::binary);if(!f)throw runtime_error("missing word");E e;vector<E>w;while(f.read((char*)&e,sizeof e))w.push_back(e);if(!f.eof())throw runtime_error("bad record");return w;}J ld(string p){J j;ifstream f(p);if(!f)throw runtime_error("missing selection");f>>j;return j;}
void check(const vector<E>&old,const vector<E>&nw,const J&sel){set<int>used,indices;map<int,vector<E>>before,after;for(auto s:sel){int i=s.at("old_record"),T=s.at("anchor"),F=s.at("new_frame");bool bef=s.at("before");if(i<0||T<0||i>=old.size()||T>=old.size()||!indices.insert(i).second)throw runtime_error("selection index");auto e=old[i],a=old[T];if(e.k!=1||e.a==e.b||e.f!=s.at("old_frame")||J::array({e.a,e.b,e.c})!=s.at("incidence")||a.k!=1||a.f!=F||!((a.a==e.a)||(a.a==e.b)||(a.b==e.a)||(a.b==e.b)))throw runtime_error("gate/anchor binding");if(!used.insert(e.a).second||!used.insert(e.b).second)throw runtime_error("overlapping operands");if((bef&&T<=i)||(!bef&&T>=i))throw runtime_error("direction");int lo=bef?i+1:T+1,hi=bef?T:i;for(int t=lo;t<hi;t++){auto x=old[t];if(x.k==1&&(x.b==e.a||x.a==e.b))throw runtime_error("crossed scalar dependence");if((x.k==2||x.k==3)&&x.a==e.a)throw runtime_error("crossed copy dependence");}e.f=F;e.z=56;(bef?before:after)[T].push_back(e);}for(auto s:sel)if(indices.count(s.at("anchor").get<int>()))throw runtime_error("moved anchor");vector<E>expected,got;for(int i=0;i<old.size();i++){for(auto e:before[i])expected.push_back(e);if(old[i].k&&!indices.count(i))expected.push_back(old[i]);for(auto e:after[i])expected.push_back(e);}for(auto e:nw)if(e.k)got.push_back(e);if(expected!=got)throw runtime_error("exact scalar/COPY projection mismatch");}
int main(int ac,char**av){if(ac!=4)throw runtime_error("BASE NEW OUTJSON");auto old=read(string(av[1])+"/COHORT249-RECORDS.bin"),nw=read(string(av[2])+"/COHORT249-RECORDS.bin");auto sel=ld(string(av[2])+"/REORDER-SELECTION.json");if(sel.empty())throw runtime_error("nonempty witness required");check(old,nw,sel);int controls=0;auto rejected=[&](auto fn){try{fn();}catch(const exception&){controls++;return;}throw runtime_error("negative control accepted");};
rejected([&](){auto j=sel;j.push_back(j[0]);check(old,nw,j);});
rejected([&](){auto j=sel;j[0]["before"]=!j[0]["before"].get<bool>();check(old,nw,j);});
rejected([&](){auto w=nw;auto it=find_if(w.begin(),w.end(),[](E e){return e.k==1&&e.z==56;});if(it==w.end())throw runtime_error("no moved add");it->c+=2;check(old,w,sel);});
rejected([&](){auto w=nw;auto it=find_if(w.begin(),w.end(),[](E e){return e.k==1&&e.z==56;});if(it==w.end())throw runtime_error("no moved add");w.erase(it);check(old,w,sel);});
rejected([&](){auto w=nw;auto it=find_if(w.begin(),w.end(),[](E e){return e.k==1&&e.z==56;});if(it==w.end())throw runtime_error("no moved add");it->f^=1;check(old,w,sel);});
bool mutated=false;for(auto s:sel){int i=s["old_record"],T=s["anchor"];bool bef=s["before"];int l=bef?i+1:T+1,h=bef?T:i;for(int t=l;t<h;t++)if(old[t].k==1){auto w=old;w[t].a=old[i].b;rejected([&](){check(w,nw,sel);});mutated=true;break;}if(mutated)break;}if(!mutated)throw runtime_error("no interval mutation available");J r={{"status","PASS_INDEPENDENT_EXACT_COMMUTATION_AND_SCALAR_PROJECTION"},{"moved_adds",sel.size()},{"all_dirty_input_integer_ring_identity",true},{"disjoint_operands",true},{"unchanged_copy_lifetimes",true},{"exact_anchor_frame_binding",true},{"negative_controls_rejected",controls},{"controls",{"overlap","direction","F2_invisible_coefficient","missing_ADD","wrong_frame","crossed_source_write"}},{"scope","Universal ring commutation lemma applied to this exact source-bound sequence; physical/source-span/bank/precision/47 checks remain separate."}};ofstream(av[3])<<r.dump(2)<<"\n";cout<<r.dump()<<"\n";}
