#include <bits/stdc++.h>
#include <json.hpp>
#include <boost/multiprecision/cpp_int.hpp>
using namespace std;using J=nlohmann::json;using Q=boost::multiprecision::cpp_rational;using I=boost::multiprecision::cpp_int;
struct Ev{int k,a,b,c,f,z;};struct F{int d;vector<vector<long long>>B,A;};J ld(string p){J j;ifstream(p)>>j;return j;}vector<long long>clearrow(vector<Q>r){I l=1;for(auto x:r){I a=l,b=denominator(x);while(b!=0){I t=a%b;a=b;b=t;}l=l/a*denominator(x);}vector<long long>v;for(auto x:r){Q q=x*l;I a=numerator(q);if(a>LLONG_MAX||a<LLONG_MIN)throw runtime_error("overflow");v.push_back(a.convert_to<long long>());}return v;}
F frame(J rows){F f;for(auto row:rows){vector<Q>r;for(auto x:row)r.push_back(Q(x.is_string()?x.get<string>():x.dump()));f.B.push_back(clearrow(r));}f.d=f.B.size();vector<vector<Q>>m;for(auto r:f.B){vector<Q>a;for(auto x:r)a.push_back(Q(x));m.push_back(a);}int p=0;vector<int>pc;for(int c=0;c<24;c++){int k=p;while(k<m.size()&&m[k][c]==0)k++;if(k==m.size())continue;swap(m[k],m[p]);Q d=m[p][c];for(auto&x:m[p])x/=d;for(int i=0;i<m.size();i++)if(i!=p){d=m[i][c];for(int j=0;j<24;j++)m[i][j]-=d*m[p][j];}pc.push_back(c);p++;}if(p!=f.d)throw runtime_error("dependent frame");for(int c=0;c<24;c++)if(find(pc.begin(),pc.end(),c)==pc.end()){vector<Q>r(24);r[c]=1;for(int i=0;i<p;i++)r[pc[i]]=-m[i][c];f.A.push_back(clearrow(r));}return f;}
int main(int ac,char**av){if(ac!=7)return 2;string X=av[1],L=av[2],O=av[4];auto st=ld(X+"/249-states.json"),sf=ld(X+"/frames.json"),nf=ld(L+"/COHORT249-FRAMES.json"),sel=ld(av[3]),iniJ=ld(L+"/COHORT249-INITIAL.json");int n=st["n"],v=st["v"],zero=st["ZERO"];map<int,F>fs;for(auto j:{sf["frames"],nf})for(auto it=j.begin();it!=j.end();it++)fs[stoi(it.key())]={it.value()["dim"],it.value()["B"],it.value()["A"]};map<pair<int,int>,bool>cache;auto sub=[&](int a,int b){auto key=make_pair(a,b);if(cache.count(key))return cache[key];bool ok=fs.at(a).d<=fs.at(b).d;for(auto&r:fs.at(a).B)for(auto&s:fs.at(b).A){I d=0;for(int k=0;k<24;k++)d+=I(r[k])*s[k];if(d)ok=false;}return cache[key]=ok;};vector<Ev>old;Ev e;ifstream input(L+"/COHORT249-RECORDS.bin",ios::binary);while(input.read((char*)&e,sizeof e))old.push_back(e);vector<string>cats=st["physical"]["category_names"].get<vector<string>>();while(cats.size()<38)cats.push_back("extension_"+to_string(cats.size()));map<string,vector<int>>events;for(int i=0;i<old.size();i++){auto e=old[i];if(e.k==1&&e.z<28)events[J::array({e.k,e.a,e.b,e.c,cats.at(e.z)}).dump()].push_back(i);}vector<Ev>base;ifstream basein(X+"/249-records.bin",ios::binary);while(basein.read((char*)&e,sizeof e))base.push_back(e);map<string,vector<int>>baseevents;vector<pair<int,string>>baseorder;for(int i=0;i<base.size();i++){auto e=base[i];if(e.k==1){auto k=J::array({e.k,e.a,e.b,e.c,cats.at(e.z)}).dump();baseevents[k].push_back(i);baseorder.push_back({i,k});}}
int cut=-1;int dirty=find(cats.begin(),cats.end(),"dirty_read")-cats.begin();
for(int i=0;i<(int)old.size();i++){auto e=old[i];if(e.k==1&&e.z==dirty&&e.f==zero)cut=i;}
if(cut<0)throw runtime_error("no actual D0 prefix cut");vector<Ev>reference;ifstream refinput(av[5],ios::binary);while(refinput.read((char*)&e,sizeof e))reference.push_back(e);auto oldnew=ld(av[6]);map<array<int,5>,vector<int>> currentEvents;for(int i=0;i<old.size();i++){auto t=old[i];if(t.k)currentEvents[{t.k,t.a,t.b,t.c,t.z}].push_back(i);}auto anchor=[&](int at){for(int k=at;k>=0;k--){auto t=reference.at(k);if(!t.k)continue;if(!oldnew.contains(to_string(t.a))||!oldnew.contains(to_string(t.b)))continue;t.a=oldnew[to_string(t.a)];t.b=oldnew[to_string(t.b)];auto found=currentEvents.find({t.k,t.a,t.b,t.c,t.z});if(found!=currentEvents.end()&&found->second.size()==1)return found->second[0];}throw runtime_error("no unique surviving boundary anchor");};cut=anchor(sel["cut_record"]);if(cut<0)throw runtime_error("anchorcut");
int fid=max(300000,fs.rbegin()->first+1);vector<int>owner(v,-1),dep(v,-1),ini(n+1,zero),fin(n+1,zero);
for(int s=0;s<n;s++){ini[s]=iniJ[to_string(s)];fin[s]=st["final"][to_string(s)];}
J groups=J::array(),bindings=J::array();map<int,vector<int>>closes;int rejected=0;
for(auto r:sel["groups"]){
 auto f=frame(r["close_basis"]);fs[fid]=f;int firstAbove=old.size(),lastBelow=cut;bool valid=true;
 set<int>targets=r["targets"].get<set<int>>();for(int t:targets)if(owner[t]>=0||!sub(fid,fin[v+t]))valid=false;
 for(int i=cut+1;i<(int)old.size()&&valid;i++){auto e=old[i];if(e.k==1&&e.a>=v&&e.a<2*v&&targets.count(e.a-v)){
  bool below=sub(e.f,fid),above=sub(fid,e.f);if(!below&&!above){valid=false;break;}
  if(!above)lastBelow=max(lastBelow,i);if(!below)firstAbove=min(firstAbove,i);
 }}
 int close=anchor(r["close_after_record"]);if(close<lastBelow||close>=firstAbove||close<=cut)valid=false;
 if(!valid){fs.erase(fid);rejected++;continue;}
 int j=groups.size();r["frame"]=fid;r["cut_record"]=cut;r["close_after_record"]=close;r["close_rank"]=f.d;
 r["retained"]=r["targets"];r["dependent"]=J::object();nf[to_string(fid)]={{"dim",f.d},{"B",f.B},{"A",f.A}};
 for(int t:targets)owner[t]=j;groups.push_back(r);closes[close].push_back(j);fid++;
}
cerr<<"Actual cut "<<cut<<" admissible geometric groups "<<groups.size()<<" rejected "<<rejected<<"\n";
int W=(n+63)/64;vector<uint64_t>M(size_t(n+1)*W),responses(size_t(v)*W);auto row=[&](int s){return M.data()+size_t(s)*W;};auto response=[&](int s){return responses.data()+size_t(s)*W;};for(int i=0;i<n;i++)row(i)[i/64]=1ULL<<(i%64);int center=-1,relations=0;for(int i=0;i<old.size();i++){auto e=old[i];if(e.k==1){int b=e.b==n?center:e.b;if(b<0)throw runtime_error("COPY inactive");if(i>cut){if(b>=v&&b<2*v&&owner[b-v]>=0&&i<=groups[owner[b-v]]["close_after_record"].get<int>())throw runtime_error("active target read");if(e.a>=v&&e.a<2*v&&owner[e.a-v]>=0&&i<=groups[owner[e.a-v]]["close_after_record"].get<int>()){if(b>=v&&b<2*v)throw runtime_error("target prefix input");for(int k=0;k<W;k++)response(e.a-v)[k]^=row(b)[k];}}if(!(e.c&1))throw runtime_error("even scalar");for(int k=0;k<W;k++)row(e.a)[k]^=row(b)[k];}else if(e.k==2){if(center!=-1)throw runtime_error("copy overlap");center=e.a;}else if(e.k==3)center=-1;for(int j:closes[i])for(auto it=groups[j]["dependent"].begin();it!=groups[j]["dependent"].end();it++){int t=stoi(it.key());for(int k=0;k<W;k++){uint64_t z=response(t)[k];for(int p:it.value())z^=response(p)[k];if(z)throw runtime_error("literal prefix dependency group "+to_string(j));}relations++;}}

// Minimum-cost syndrome information set for each actual target interval.
vector<int> lastDim(v,0); vector<long double> splitCost(v,0);
auto psi=[](int r){return r?pow((long double)r/120,1-.0007121L):0.L;};
for(int i=cut+1;i<(int)old.size();i++){auto e=old[i];if(e.k==1&&e.a>=v&&e.a<2*v){int t=e.a-v,j=owner[t];if(j>=0&&i<=groups[j]["close_after_record"].get<int>()){int d=fs.at(e.f).d;if(d<lastDim[t])throw runtime_error("target rank order");splitCost[t]+=psi(d-lastDim[t]);lastDim[t]=d;}}}
J opt=J::array();int changedGroups=0;long double totalGain=0;fill(dep.begin(),dep.end(),-1);relations=0;
for(int j=0;j<(int)groups.size();j++){
 auto &g=groups[j];vector<int>ts=g["targets"].get<vector<int>>();int h=ts.size(),end=fs.at(g["frame"].get<int>()).d;if(h>63)throw runtime_error("target information-set cap");
 vector<long double>w(h);for(int k=0;k<h;k++){int t=ts[k];if(lastDim[t]>end)throw runtime_error("close rank");w[k]=splitCost[t]+psi(end-lastDim[t])-psi(end);}
 vector<int>order(h);iota(order.begin(),order.end(),0);stable_sort(order.begin(),order.end(),[&](int a,int b){return w[a]<w[b];});
 map<int,pair<vector<uint64_t>,uint64_t>,greater<int>> bas;J retained=J::array(),deps=J::object();long double nw=0,ow=0;
 auto firstbit=[&](const vector<uint64_t>&a){for(int k=W-1;k>=0;k--)if(a[k])return 64*k+63-__builtin_clzll(a[k]);return -1;};
 for(int z:order){vector<uint64_t>a(response(ts[z]),response(ts[z])+W);uint64_t coeff=0;for(auto &[k,b]:bas)if((a[k/64]>>(k%64))&1){for(int t=0;t<W;t++)a[t]^=b.first[t];coeff^=b.second;}int k=firstbit(a);if(k>=0){bas[k]={a,coeff^(1ULL<<z)};retained.push_back(ts[z]);nw+=w[z];}else{J donors=J::array();for(int t=0;t<h;t++)if((coeff>>t)&1)donors.push_back(ts[t]);deps[to_string(ts[z])]=donors;}}
 for(int t:g["retained"]){auto it=find(ts.begin(),ts.end(),t);if(it==ts.end())throw runtime_error("old retained outside group");ow+=w[it-ts.begin()];}
 int oldgates=0,newgates=0;for(auto it=g["dependent"].begin();it!=g["dependent"].end();it++)oldgates+=it.value().size();for(auto it=deps.begin();it!=deps.end();it++)newgates+=it.value().size();
 bool take=nw<ow-1e-17L||(abs(nw-ow)<1e-17L&&newgates<oldgates);
 if(take){g["retained"]=retained;g["dependent"]=deps;changedGroups++;totalGain+=ow-nw;}
 set<int>keep;for(int t:g["retained"])keep.insert(t);
 for(auto it=g["dependent"].begin();it!=g["dependent"].end();it++){int t=stoi(it.key());if(keep.count(t))throw runtime_error("new basis overlap");dep[t]=j;for(int d:it.value())if(!keep.count(d))throw runtime_error("new donor not basis");for(int k=0;k<W;k++){uint64_t x=response(t)[k];for(int d:it.value())x^=response(d)[k];if(x)throw runtime_error("new syndrome dependency");}relations++;}
 opt.push_back({{"group",j},{"changed",take},{"old_screen_cost",(double)ow},{"new_screen_cost",(double)(take?nw:ow)},{"old_half_scalar_count",oldgates},{"new_half_scalar_count",take?newgates:oldgates},{"basis_rank",bas.size()}});
}
ofstream(O+"/TARGET-BASIS-OPTIMIZATION.json")<<J({{"status","EXACT_RESPONSE_BASIS_WITH_APPROXIMATE_COST_ORDER"},{"changed_groups",changedGroups},{"screen_moment_gain",(double)totalGain},{"groups",opt},{"scope","Basis identities exact; cost ordering is heuristic until full physical histogram and rational price."}}).dump(2);

vector<Ev>out;auto state=ini;map<int,long long>H,oldH;for(auto e:old)if(e.k==0&&e.f)oldH[e.f]++;else if(e.k==2)oldH[e.z]++;auto moveTo=[&](int s,int f){if(state[s]==f)return;if(!sub(state[s],f))throw runtime_error("nonnested actual role "+to_string(s)+" "+to_string(state[s])+" to "+to_string(f));int r=fs[f].d-fs[state[s]].d;out.push_back({0,s,state[s],f,r,0});if(r)H[r]++;state[s]=f;};auto add=[&](int a,int b,int c,int f,int z){moveTo(a,f);moveTo(b,f);out.push_back({1,a,b,c,f,z});};int inserted=0,deleted=0,first=-1;auto batch=[&](int j,bool setup){auto r=groups[j];bool nonzero=false;for(auto it=r["dependent"].begin();it!=r["dependent"].end();it++)if(!it.value().empty())nonzero=true;if(!nonzero)return;int f=setup?zero:r["frame"].get<int>();for(int t:r["targets"])moveTo(v+t,f);for(auto it=r["dependent"].begin();it!=r["dependent"].end();it++)for(int p:it.value()){int a=v+stoi(it.key());if(setup&&first<0)first=out.size();add(a,v+p,setup?-1:1,f,setup?34:35);inserted++;}};center=-1;for(int i=0;i<old.size();i++){auto e=old[i];if(e.k==1){int j=e.a>=v&&e.a<2*v?dep[e.a-v]:-1;if(j>=0&&i>cut&&i<=groups[j]["close_after_record"].get<int>())deleted++;else add(e.a,e.b,e.c,e.f,e.z);}else if(e.k==2){moveTo(e.a,e.c);state[e.b]=e.f;out.push_back(e);H[e.z]++;center=e.a;}else if(e.k==3){if(state[e.a]!=e.c||state[e.b]!=e.f)throw runtime_error("COPY close frame");out.push_back(e);center=-1;}if(i==cut){if(center!=-1)throw runtime_error("cut COPY");for(int t=0;t<v;t++)if(owner[t]>=0&&state[v+t]!=zero)throw runtime_error("setup target not zero");for(int j=0;j<groups.size();j++)batch(j,true);}for(int j:closes[i])batch(j,false);}for(int s=0;s<n;s++)moveTo(s,fin[s]);long long mass=0,oldmass=0;J hist=J::object(),delta=J::object();for(auto[r,c]:H){mass+=r*c;hist[to_string(r)]=c;}for(auto[r,c]:oldH)oldmass+=r*c;set<int>ranks;for(auto[r,c]:H)ranks.insert(r);for(auto[r,c]:oldH)ranks.insert(r);for(int r:ranks)if(H[r]!=oldH[r])delta[to_string(r)]=H[r]-oldH[r];if(mass!=oldmass)throw runtime_error("rank mass changed");
auto replay=[&](bool rev,int omit){fill(M.begin(),M.end(),0);for(int i=0;i<n;i++)row(i)[i/64]=1ULL<<(i%64);for(int i=0;i<out.size();i++){int at=rev?out.size()-1-i:i;auto e=out[at];if(at==omit)continue;if(e.k==1&&(e.c&1)){for(int k=0;k<W;k++)row(e.a)[k]^=row(e.b)[k];}else if(e.k==(rev?3:2))copy(row(e.a),row(e.a)+W,row(e.b));else if(e.k==(rev?2:3))for(int k=0;k<W;k++)if(row(e.a)[k]!=row(e.b)[k])throw runtime_error("copy erase columns");}long long bad=0;for(int s=0;s<n;s++)for(int k=0;k<W;k++){uint64_t ex=s/64==k?1ULL<<(s%64):0;if(s>=v&&s<2*v&&(s-v)/64==k)ex^=1ULL<<((s-v)%64);bad+=row(s)[k]!=ex;}return bad;};if(replay(false,-1)||replay(true,-1))throw runtime_error("full endpoint columns");auto wrong=replay(false,first);int restore=-1;for(int i=0;i<out.size();i++)if(out[i].k==1&&out[i].z==35){restore=i;break;}auto wrongRestore=replay(false,restore);if(first>=0&&(!wrong||!wrongRestore))throw runtime_error("vacuous negative");ofstream bout(O+"/COHORT249-RECORDS.bin",ios::binary);bout.write((char*)out.data(),out.size()*sizeof(Ev));ofstream(O+"/COHORT249-FRAMES.json")<<nf.dump();ofstream(O+"/COHORT249-INITIAL.json")<<iniJ.dump();auto oldsel=ld(L+"/COHORT249-SELECTION.json");ofstream(O+"/COHORT249-SELECTION.json")<<oldsel.dump(2);auto receipt=ld(L+"/COHORT249-REPLAY.json");receipt["kernel_precursor_receipt"]=receipt;receipt["status"]="PASS_KERNEL_AND_TARGET_PREFIX_COMPOSED_NATIVE_WORD";receipt["precursor_controls_scope"]="Original omitted_Q and omitted_Qinverse fields apply only to kernel_precursor_receipt. TARGET268-RECEIPT gives fresh target setup and restore controls.";receipt["kernel_delta"]=receipt["delta"];for(auto it=delta.begin();it!=delta.end();it++){long long prev=receipt["delta"].value(it.key(),0LL);long long value=prev+it.value().get<long long>();if(value)receipt["delta"][it.key()]=value;else receipt["delta"].erase(it.key());}receipt["histogram"]=hist;receipt["new_rank_mass"]=mass;receipt["new_records"]=out.size();receipt["target_prefix_composed"]=true;ofstream(O+"/COHORT249-REPLAY.json")<<receipt.dump(2);J report={{"status","PASS_NATIVE_TARGET_PREFIX_ON_CURRENT_KERNEL_WORD"},{"groups",groups.size()},{"relations",relations},{"deleted_prefix_adds",deleted},{"inserted_setup_restore_adds",inserted},{"cut",cut},{"bindings",bindings},{"histogram_delta",delta},{"new_rank_mass",mass},{"all_formal_columns_each_direction",n},{"negative_control_wrong_words",wrong},{"omitted_target_restore_wrong_words",wrongRestore},{"new_frames",groups.size()},{"scope","Exact current F2 prefix relations and full arbitrary-column endpoints, actual nested MOVE emission and target covectors. Fresh all-used Gram/chart/five-stage/price audits required."}};ofstream(O+"/TARGET268-RECEIPT.json")<<report.dump(2);ofstream(O+"/TARGET268-GROUPS.json")<<groups.dump();cout<<"PASS groups "<<groups.size()<<" relations "<<relations<<" deletes "<<deleted<<" inserts "<<inserted<<" mass "<<mass<<"\n";}





