#include <bits/stdc++.h>
#include <json.hpp>
#include <boost/multiprecision/cpp_int.hpp>
using namespace std;using J=nlohmann::json;using Q=boost::multiprecision::cpp_rational;
J ld(string p){J x;ifstream(p)>>x;return x;}using M=vector<vector<Q>>;
M eye(int n){M a(n,vector<Q>(n));for(int i=0;i<n;i++)a[i][i]=1;return a;}M mul(M a,M b){int n=a.size();M c(n,vector<Q>(n));for(int i=0;i<n;i++)for(int k=0;k<n;k++)if(a[i][k]!=0)for(int j=0;j<n;j++)c[i][j]+=a[i][k]*b[k][j];return c;}
M inverse(M a,int &ops,Q &det){int n=a.size();M b=eye(n);det=1;ops=0;for(int k=0;k<n;k++){int t=k;while(t<n&&a[t][k]==0)t++;if(t==n)throw runtime_error("singular chart");if(t!=k){swap(a[k],a[t]);swap(b[k],b[t]);det=-det;ops++;}Q p=a[k][k];det*=p;if(p!=1){ops++;for(int j=0;j<n;j++){a[k][j]/=p;b[k][j]/=p;}}for(int i=0;i<n;i++)if(i!=k&&a[i][k]!=0){ops++;Q c=a[i][k];for(int j=0;j<n;j++){a[i][j]-=c*a[k][j];b[i][j]-=c*b[k][j];}}}if(a!=eye(n))throw runtime_error("inverse failure");return b;}
struct Pattern{vector<int>w;int count;};
int main(int ac,char**av){string dir=av[1],out=av[2];auto st=ld(dir+"/temporal/CURRENT249-EXPORT/249-states.json"),fj=ld(dir+"/temporal/CURRENT249-EXPORT/frames.json")["frames"],ini=ld(dir+"/lead/COHORT249-INITIAL.json"),sel=ld(dir+"/lead/COHORT249-SELECTION.json"),nf=ld(dir+"/lead/COHORT249-FRAMES.json");map<int,int> dims;for(auto it=fj.begin();it!=fj.end();it++)dims[stoi(it.key())]=it.value()["dim"];for(auto it=nf.begin();it!=nf.end();it++)dims[stoi(it.key())]=it.value()["dim"];map<int,vector<int>>fam;map<int,int>gauge;int n=st["n"],v=st["v"];for(int i=0;i<(int)st["regs"].size();i++){int physical=st["regs"][i],f=ini.at(to_string(2*v+i)),r=24-dims.at(f);fam[r].push_back(physical);if(r!=24)gauge[physical]=f;}map<int,int> expected{{4,2200},{6,22},{7,5},{11,48},{12,23},{15,2},{23,132},{24,14155}};for(auto[r,k]:expected)if(fam[r].size()!=k)throw runtime_error("new actual family mismatch");if(fam.size()!=expected.size())throw runtime_error("extra rank family");
int maxops=0;J charts=J::array();for(auto z:sel){vector<int>u;for(auto x:z["basis"][0])u.push_back(stoi(x.get<string>()));int sum=accumulate(u.begin(),u.end(),0),norm=0,p=-1;for(int i=0;i<24;i++){norm+=u[i]*u[i];if(u[i]&&p<0)p=i;}if(sum||norm!=4||abs(u[p])!=1)throw runtime_error("new gauge norm");M B(24,vector<Q>(24));vector<int>ix;for(int i=0;i<24;i++)if(i!=p)ix.push_back(i);for(int j=0;j<23;j++){B[ix[j]][j]=1;B[p][j]=-Q(u[ix[j]])/u[p];}for(int i=0;i<24;i++)B[i][23]=u[i];Q det;int ops;auto inv=inverse(B,ops,det);if(mul(B,inv)!=eye(24)||mul(inv,B)!=eye(24)||abs(det)!=4)throw runtime_error("two sided chart inverse");M P=eye(24);for(int i=0;i<24;i++)for(int j=0;j<24;j++)P[i][j]-=Q(u[i])*u[j]/4;M expectedP=eye(24);expectedP[23][23]=0;if(mul(mul(inv,P),B)!=expectedP)throw runtime_error("new residual projector chart identity");for(int j=0;j<23;j++){Q dot=0;for(int i=0;i<24;i++)dot+=u[i]*B[i][j];if(dot!=0)throw runtime_error("weighted split");}maxops=max(maxops,ops);J Bj=J::array(),Ij=J::array();for(int i=0;i<24;i++){J r=J::array(),s=J::array();for(int j=0;j<24;j++){r.push_back(B[i][j].str());s.push_back(inv[i][j].str());}Bj.push_back(r);Ij.push_back(s);}charts.push_back({{"role",z["role_a"]},{"frame",z["new_frame_id"]},{"B",Bj},{"inverse",Ij},{"determinant",det.str()},{"row_factor_count",ops},{"pivot",p}});}
vector<Pattern>pat;auto add=[&](initializer_list<pair<int,int>> terms,int count){vector<int>w;for(auto[r,k]:terms)for(int j=0;j<k;j++)w.push_back(r);if(accumulate(w.begin(),w.end(),0)!=120)throw runtime_error("pattern wrong total");pat.push_back({w,count});};add({{11,8},{4,8}},240);add({{7,4},{4,23}},50);add({{4,30}},2523);add({{6,20}},44);add({{12,10}},92);add({{15,8}},10);add({{24,5}},113240);add({{23,4},{4,7}},1320);
struct Slot{int bank,off,r,block,pattern;};map<int,vector<Slot>>slots;int banks=0;J pj=J::array();for(int p=0;p<(int)pat.size();p++){auto pp=pat[p];pj.push_back({{"widths",pp.w},{"count",pp.count}});for(int b=0;b<pp.count;b++){int off=0;for(int j=0;j<(int)pp.w.size();j++){int r=pp.w[j];slots[r].push_back({banks+b,off,r,j,p});off+=r;}}banks+=pp.count;}if(banks!=117519)throw runtime_error("banks count");for(auto[r,rows]:fam)if(slots[r].size()!=40*rows.size())throw runtime_error("literal slots census mismatch");
uint64_t hash=1469598103934665603ull;auto mix=[&](uint64_t x){for(int j=0;j<8;j++){hash^=(x>>(8*j))&255;hash*=1099511628211ull;}};long long assignments=0,rankMass=0,columns=0,controls=0;J changed=J::array();for(int stage=0;stage<5;stage++){vector<bitset<120>>occupancy(banks);for(auto[r,rows]:fam)for(int i=0;i<(int)rows.size();i++)for(int rep=0;rep<40;rep++){auto s=slots[r].at(40*i+rep);for(int j=s.off;j<s.off+r;j++){if(occupancy[s.bank][j])throw runtime_error("bank collision");occupancy[s.bank][j]=1;}for(int x:{stage,rep,rows[i],s.bank,s.off,r,s.block+1})mix(x);assignments++;rankMass+=r;if(r==23)changed.push_back({{"stage",stage},{"replica",rep},{"role",rows[i]},{"bank_family",281600+stage*banks+s.bank},{"block",s.block},{"offset",s.off},{"rank",r},{"scalar",s.block+1},{"frame",gauge.at(rows[i])}});}for(auto &bits:occupancy)if(bits.count()!=120)throw runtime_error("bank endpoint unfilled");}
// Exact D_P endpoint on all240 arbitrary address columns for each distinct layout.
for(auto pp:pat){for(bool rev:{false,true})for(int col=0;col<240;col++){array<int,240>state{};state[col]=1;int off=0;vector<pair<int,int>> blocks;for(int r:pp.w){blocks.push_back({off,r});off+=r;}if(rev)reverse(blocks.begin(),blocks.end());for(auto[o,r]:blocks)for(int j=o;j<o+r;j++)swap(state[j],state[120+j]);for(int j=0;j<240;j++)if(state[j]!=(j==(col+120)%240))throw runtime_error("complete endpoint column");columns++;}for(int mode=0;mode<2;mode++)for(int broken=0;broken<(int)pp.w.size();broken++){long long bad=0;for(int col=0;col<240;col++){array<int,240> state{};state[col]=1;int off=0;for(int b=0;b<(int)pp.w.size();b++){int r=pp.w[b],times=(b==broken?(mode==0?0:2):1);for(int t=0;t<times;t++)for(int j=off;j<off+r;j++)swap(state[j],state[120+j]);off+=r;}for(int j=0;j<240;j++)if(state[j]!=(j==(col+120)%240)){bad++;break;}}if(bad!=2*pp.w[broken])throw runtime_error("nonzero control support mismatch");controls+=bad;}}
J census=J::object();for(auto[r,rows]:fam)census[to_string(r)]=rows.size();J result={{"status","PASS_ACTUAL249_COHORT_BANK_ALLOCATION_AND_NEW_CHARTS"},{"actual_helper_roles",n-2*v},{"residual_families",census},{"new_exact_charts",charts.size()},{"max_new_chart_factors",maxops},{"new_chart_abs_determinant",4},{"bank_patterns",pj},{"banks_per_stage",banks},{"literal_stock",281600+5*banks},{"old_literal_stock",869415},{"saved_literal_banks",220},{"actual_role_replica_stage_assignments",assignments},{"assignment_fnv1a64",to_string(hash)},{"covered_address_rank_mass",rankMass},{"endpoint_address_columns",columns},{"nonzero_omission_repeat_control_columns",controls},{"max_block_scalar",30},{"all_new_denominators_divide",4},{"scope","Actual full role census and complete stage-private bank assignment; all132 newly introduced rank1 gauge charts and240-column block endpoints checked exactly. Retained old charts are inherited from pinned249 admission. Does not itself replay whole GL-cover scalar driver or all47 pricing inequalities."}};ofstream(out+"/COHORT-BANK-REVIEW.json")<<result.dump(2)<<"\n";ofstream(out+"/COHORT-BANK-NEW-CHARTS.json")<<charts.dump()<<"\n";ofstream(out+"/COHORT-BANK-NEW-ASSIGNMENTS.json")<<changed.dump()<<"\n";cout<<result.dump(2)<<"\n";}
