#include <algorithm>
#include <cassert>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <vector>
#include "json.hpp"
using namespace std;using J=nlohmann::json;struct Ev{int k,a,b,c,f,z;};struct Frame{int d;vector<vector<long long>>B,A;};
int main(int argc,char**argv){string dir=argv[1],outdir=argv[3];J st,fj,cc;ifstream(dir+"/249-states.json")>>st;ifstream(dir+"/frames.json")>>fj;ifstream(argv[2])>>cc;map<int,Frame>fs;int nextid=200000;for(auto it=fj["frames"].begin();it!=fj["frames"].end();it++){Frame f;f.d=it.value()["dim"];f.B=it.value()["B"].get<vector<vector<long long>>>();f.A=it.value()["A"].get<vector<vector<long long>>>();fs[stoi(it.key())]=move(f);}fj.clear();map<pair<int,int>,bool>cache;auto sub=[&](int a,int b){auto key=make_pair(a,b);auto it=cache.find(key);if(it!=cache.end())return it->second;bool ok=fs[a].d<=fs[b].d;if(ok)for(auto&x:fs[a].B){for(auto&y:fs[b].A){__int128 t=0;for(int i=0;i<24;i++)t+=(__int128)x[i]*y[i];if(t){ok=false;break;}}if(!ok)break;}return cache[key]=ok;};vector<Ev>ev;Ev x;ifstream in(dir+"/249-records.bin",ios::binary);while(in.read((char*)&x,sizeof x))ev.push_back(x);int n=st["n"],v=st["v"],zero=st["ZERO"],full=st["FULL"],cut=-1;for(int i=0;i<(int)ev.size();i++)if(ev[i].k==1&&ev[i].a==3491&&ev[i].b==3488&&ev[i].c==-1&&ev[i].z==25){if(cut>=0)throw runtime_error("ambiguous cut");cut=i;}if(cut<0)throw runtime_error("cut absent");vector<int>ini(n+1,zero),fin(n+1,full);for(auto it=st["initial"].begin();it!=st["initial"].end();it++)ini[stoi(it.key())]=it.value();for(auto it=st["final"].begin();it!=st["final"].end();it++)fin[stoi(it.key())]=it.value();J chosen=J::array(),newframes=J::object();set<int>used;map<int,pair<int,int>>gauges;for(auto z:cc["candidates"]){int a=z["a"],b=z["b"];if(!z["new_targets"].empty()||z["E_dimension"]!=1||used.count(a)||used.count(b)||ini[a]!=zero||ini[b]!=zero||fin[a]!=full||fin[b]!=full)continue;Frame f;f.d=1;for(auto rows:{0,1}){auto jj=rows?z["annihilator"]:z["basis"];vector<vector<long long>>data;for(auto rr:jj){vector<long long>r;for(auto vv:rr)r.push_back(stoll(vv.get<string>()));data.push_back(r);}if(rows)f.A=data;else f.B=data;}long long sum=0,norm=0;for(auto a:f.B[0]){sum+=a;norm+=a*a;}long long gram=9*norm-sum*sum;if(!gram)continue;if(sum!=0||norm!=4)continue;int F=nextid++;fs[F]=f;if(!sub(F,z["first_a"])||!sub(F,z["first_b"]))throw runtime_error("false intersection");for(int i=0;i<=cut;i++){auto e=ev[i];if(e.k&&((e.k==1&&e.a==a)||(e.k==1&&e.a==b)||(e.k!=1&&(e.a==a||e.a==b))))throw runtime_error("cohort touched before cut");if(e.k==1&&e.b==a&&!(e.z==4&&e.f==zero&&e.a>=v&&e.a<2*v))throw runtime_error("bad removed read");}
used.insert(a);used.insert(b);gauges[a]={b,F};z["new_frame_id"]=F;z["cleared_gram_determinant"]=gram;z["role_a"]=st["regs"][a-2*v];z["role_b"]=st["regs"][b-2*v];chosen.push_back(z);newframes[to_string(F)]={{"B",f.B},{"A",f.A},{"dim",1}};}
if(chosen.empty())throw runtime_error("no selected pairs");vector<int>state=ini;for(auto&[a,bf]:gauges)state[a]=bf.second;vector<int>newini=state;vector<Ev>out;long long removed=0,weighted=0;map<int,long long>H,oldH;for(auto e:ev){if(e.k==0&&e.f)oldH[e.f]++;else if(e.k==2)oldH[e.z]++;}auto moveTo=[&](int s,int f){if(state[s]==f)return;if(!sub(state[s],f)){cerr<<"bad move "<<s<<" "<<state[s]<<" "<<f<<"\n";throw runtime_error("non-nesting");}int r=fs[f].d-fs[state[s]].d;out.push_back({0,s,state[s],f,r,0});if(r)H[r]++;state[s]=f;};auto add=[&](int a,int b,int c,int f,int z){moveTo(a,f);moveTo(b,f);out.push_back({1,a,b,c,f,z});weighted+=abs(c);};for(int i=0;i<(int)ev.size();i++){auto e=ev[i];if(e.k==1){if(gauges.count(e.b)&&e.z==4&&e.f==zero&&i<=cut){removed++;}else add(e.a,e.b,e.c,e.f,e.z);}else if(e.k==2){moveTo(e.a,e.c);state[e.b]=e.f;out.push_back(e);H[e.z]++;}else if(e.k==3){if(state[e.a]!=e.c||state[e.b]!=e.f)throw runtime_error("copy endpoint");out.push_back(e);}if(i==cut)for(auto&[a,bf]:gauges)add(bf.first,a,1,bf.second,28);}
for(int s=0;s<n;s++)moveTo(s,fin[s]);for(auto&[a,bf]:gauges)add(bf.first,a,-1,full,29);for(int s=0;s<n;s++)if(state[s]!=fin[s])throw runtime_error("final frame mismatch");
// Full arbitrary formal F2 columns. COPY has its actual own temporary row.
auto replay=[&](const vector<Ev>&word,bool reverse,int omitcat){int words=(n+63)/64;vector<uint64_t>M((size_t)(n+1)*words);auto row=[&](int s){return &M[(size_t)s*words];};for(int s=0;s<n;s++)row(s)[s/64]|=1ull<<(s%64);for(int k=0;k<(int)word.size();k++){auto e=word[reverse?word.size()-1-k:k];if(e.z==omitcat&&e.k==1)continue;if(e.k==1&&(e.c&1)){for(int j=0;j<words;j++)row(e.a)[j]^=row(e.b)[j];}else if(e.k==(reverse?3:2)){copy(row(e.a),row(e.a)+words,row(e.b));}else if(e.k==(reverse?2:3)){for(int j=0;j<words;j++)if(row(e.a)[j]!=row(e.b)[j])throw runtime_error("copy erase mismatch");}}long long bad=0;for(int s=0;s<n;s++)for(int j=0;j<words;j++){uint64_t expected=(s/64==j)?1ull<<(s%64):0;if(s>=v&&s<2*v&&(s-v)/64==j)expected^=1ull<<((s-v)%64);bad+=row(s)[j]!=expected;}return bad;};if(replay(out,false,-1)||replay(out,true,-1))throw runtime_error("full columns fail");auto badQ=replay(out,false,28),badQi=replay(out,false,29);if(!badQ||!badQi)throw runtime_error("vacuous control");long long mass=0,oldmass=0;J hist=J::object(),delta=J::object();for(auto[r,c]:H){hist[to_string(r)]=c;mass+=r*c;}for(auto[r,c]:oldH)oldmass+=r*c;set<int>rs;for(auto[r,c]:H)rs.insert(r);for(auto[r,c]:oldH)rs.insert(r);for(int r:rs)if(H[r]!=oldH[r])delta[to_string(r)]=H[r]-oldH[r];if(oldmass-mass!=(long long)chosen.size())throw runtime_error("rank bill mismatch");ofstream bout(outdir+"/COHORT249-RECORDS.bin",ios::binary);bout.write((char*)out.data(),out.size()*sizeof(Ev));J ii=J::object();for(int s=0;s<n;s++)ii[to_string(s)]=newini[s];ofstream(outdir+"/COHORT249-INITIAL.json")<<ii.dump()<<"\n";ofstream(outdir+"/COHORT249-FRAMES.json")<<newframes.dump()<<"\n";ofstream(outdir+"/COHORT249-SELECTION.json")<<chosen.dump(2)<<"\n";J receipt={{"status","PASS_FULL_CURRENT249_COHORT_REWRITE_F2_COLUMNS_AND_FRAMES"},{"new_gauges",chosen.size()},{"new_entrance_rank",chosen.size()},{"cut_record",cut},{"old_records",ev.size()},{"new_records",out.size()},{"removed_initial_reads",removed},{"added_Q_Qinverse_passes",2*chosen.size()},{"forward_formal_columns",n},{"inverse_formal_columns",n},{"omitted_Q_nonzero_wrong_words",badQ},{"omitted_Qinverse_nonzero_wrong_words",badQi},{"histogram",hist},{"delta",delta},{"old_rank_mass",oldmass},{"new_rank_mass",mass},{"all_new_gram_determinants",36},{"bank_completion_not_replayed",true},{"global_kappa_claimed",false}};ofstream(outdir+"/COHORT249-REPLAY.json")<<receipt.dump(2)<<"\n";cerr<<"PASS "<<chosen.size()<<" pairs, mass "<<oldmass<<" -> "<<mass<<" removed reads "<<removed<<"\n";}
